// Generated by gencpp from file tauv_msgs/ControllerCommand.msg
// DO NOT EDIT!


#ifndef TAUV_MSGS_MESSAGE_CONTROLLERCOMMAND_H
#define TAUV_MSGS_MESSAGE_CONTROLLERCOMMAND_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tauv_msgs
{
template <class ContainerAllocator>
struct ControllerCommand_
{
  typedef ControllerCommand_<ContainerAllocator> Type;

  ControllerCommand_()
    : a_x(0.0)
    , a_y(0.0)
    , a_z(0.0)
    , a_roll(0.0)
    , a_pitch(0.0)
    , a_yaw(0.0)
    , f_x(0.0)
    , f_y(0.0)
    , f_z(0.0)
    , f_roll(0.0)
    , f_pitch(0.0)
    , f_yaw(0.0)
    , use_f_x(false)
    , use_f_y(false)
    , use_f_z(false)
    , use_f_roll(false)
    , use_f_pitch(false)
    , use_f_yaw(false)
    , setpoint_z(0.0)
    , setpoint_roll(0.0)
    , setpoint_pitch(0.0)
    , use_setpoint_z(false)
    , use_setpoint_roll(false)
    , use_setpoint_pitch(false)  {
    }
  ControllerCommand_(const ContainerAllocator& _alloc)
    : a_x(0.0)
    , a_y(0.0)
    , a_z(0.0)
    , a_roll(0.0)
    , a_pitch(0.0)
    , a_yaw(0.0)
    , f_x(0.0)
    , f_y(0.0)
    , f_z(0.0)
    , f_roll(0.0)
    , f_pitch(0.0)
    , f_yaw(0.0)
    , use_f_x(false)
    , use_f_y(false)
    , use_f_z(false)
    , use_f_roll(false)
    , use_f_pitch(false)
    , use_f_yaw(false)
    , setpoint_z(0.0)
    , setpoint_roll(0.0)
    , setpoint_pitch(0.0)
    , use_setpoint_z(false)
    , use_setpoint_roll(false)
    , use_setpoint_pitch(false)  {
  (void)_alloc;
    }



   typedef float _a_x_type;
  _a_x_type a_x;

   typedef float _a_y_type;
  _a_y_type a_y;

   typedef float _a_z_type;
  _a_z_type a_z;

   typedef float _a_roll_type;
  _a_roll_type a_roll;

   typedef float _a_pitch_type;
  _a_pitch_type a_pitch;

   typedef float _a_yaw_type;
  _a_yaw_type a_yaw;

   typedef float _f_x_type;
  _f_x_type f_x;

   typedef float _f_y_type;
  _f_y_type f_y;

   typedef float _f_z_type;
  _f_z_type f_z;

   typedef float _f_roll_type;
  _f_roll_type f_roll;

   typedef float _f_pitch_type;
  _f_pitch_type f_pitch;

   typedef float _f_yaw_type;
  _f_yaw_type f_yaw;

   typedef uint8_t _use_f_x_type;
  _use_f_x_type use_f_x;

   typedef uint8_t _use_f_y_type;
  _use_f_y_type use_f_y;

   typedef uint8_t _use_f_z_type;
  _use_f_z_type use_f_z;

   typedef uint8_t _use_f_roll_type;
  _use_f_roll_type use_f_roll;

   typedef uint8_t _use_f_pitch_type;
  _use_f_pitch_type use_f_pitch;

   typedef uint8_t _use_f_yaw_type;
  _use_f_yaw_type use_f_yaw;

   typedef float _setpoint_z_type;
  _setpoint_z_type setpoint_z;

   typedef float _setpoint_roll_type;
  _setpoint_roll_type setpoint_roll;

   typedef float _setpoint_pitch_type;
  _setpoint_pitch_type setpoint_pitch;

   typedef uint8_t _use_setpoint_z_type;
  _use_setpoint_z_type use_setpoint_z;

   typedef uint8_t _use_setpoint_roll_type;
  _use_setpoint_roll_type use_setpoint_roll;

   typedef uint8_t _use_setpoint_pitch_type;
  _use_setpoint_pitch_type use_setpoint_pitch;





  typedef boost::shared_ptr< ::tauv_msgs::ControllerCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tauv_msgs::ControllerCommand_<ContainerAllocator> const> ConstPtr;

}; // struct ControllerCommand_

typedef ::tauv_msgs::ControllerCommand_<std::allocator<void> > ControllerCommand;

typedef boost::shared_ptr< ::tauv_msgs::ControllerCommand > ControllerCommandPtr;
typedef boost::shared_ptr< ::tauv_msgs::ControllerCommand const> ControllerCommandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tauv_msgs::ControllerCommand_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tauv_msgs::ControllerCommand_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tauv_msgs::ControllerCommand_<ContainerAllocator1> & lhs, const ::tauv_msgs::ControllerCommand_<ContainerAllocator2> & rhs)
{
  return lhs.a_x == rhs.a_x &&
    lhs.a_y == rhs.a_y &&
    lhs.a_z == rhs.a_z &&
    lhs.a_roll == rhs.a_roll &&
    lhs.a_pitch == rhs.a_pitch &&
    lhs.a_yaw == rhs.a_yaw &&
    lhs.f_x == rhs.f_x &&
    lhs.f_y == rhs.f_y &&
    lhs.f_z == rhs.f_z &&
    lhs.f_roll == rhs.f_roll &&
    lhs.f_pitch == rhs.f_pitch &&
    lhs.f_yaw == rhs.f_yaw &&
    lhs.use_f_x == rhs.use_f_x &&
    lhs.use_f_y == rhs.use_f_y &&
    lhs.use_f_z == rhs.use_f_z &&
    lhs.use_f_roll == rhs.use_f_roll &&
    lhs.use_f_pitch == rhs.use_f_pitch &&
    lhs.use_f_yaw == rhs.use_f_yaw &&
    lhs.setpoint_z == rhs.setpoint_z &&
    lhs.setpoint_roll == rhs.setpoint_roll &&
    lhs.setpoint_pitch == rhs.setpoint_pitch &&
    lhs.use_setpoint_z == rhs.use_setpoint_z &&
    lhs.use_setpoint_roll == rhs.use_setpoint_roll &&
    lhs.use_setpoint_pitch == rhs.use_setpoint_pitch;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tauv_msgs::ControllerCommand_<ContainerAllocator1> & lhs, const ::tauv_msgs::ControllerCommand_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tauv_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::tauv_msgs::ControllerCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tauv_msgs::ControllerCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tauv_msgs::ControllerCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tauv_msgs::ControllerCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tauv_msgs::ControllerCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tauv_msgs::ControllerCommand_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tauv_msgs::ControllerCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ad1b57ce703dafd167a4f28711d03e4e";
  }

  static const char* value(const ::tauv_msgs::ControllerCommand_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xad1b57ce703dafd1ULL;
  static const uint64_t static_value2 = 0x67a4f28711d03e4eULL;
};

template<class ContainerAllocator>
struct DataType< ::tauv_msgs::ControllerCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tauv_msgs/ControllerCommand";
  }

  static const char* value(const ::tauv_msgs::ControllerCommand_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tauv_msgs::ControllerCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Accelerations\n"
"float32 a_x\n"
"float32 a_y\n"
"float32 a_z\n"
"float32 a_roll\n"
"float32 a_pitch\n"
"float32 a_yaw\n"
"\n"
"# Forces\n"
"float32 f_x\n"
"float32 f_y\n"
"float32 f_z\n"
"float32 f_roll\n"
"float32 f_pitch\n"
"float32 f_yaw\n"
"\n"
"# If set, override accelerations and use forces\n"
"bool use_f_x\n"
"bool use_f_y\n"
"bool use_f_z\n"
"bool use_f_roll\n"
"bool use_f_pitch\n"
"bool use_f_yaw\n"
"\n"
"# Setpoints\n"
"float32 setpoint_z\n"
"float32 setpoint_roll\n"
"float32 setpoint_pitch\n"
"\n"
"# If set, override accelerations and forces and use setpoints\n"
"bool use_setpoint_z\n"
"bool use_setpoint_roll\n"
"bool use_setpoint_pitch\n"
;
  }

  static const char* value(const ::tauv_msgs::ControllerCommand_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tauv_msgs::ControllerCommand_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.a_x);
      stream.next(m.a_y);
      stream.next(m.a_z);
      stream.next(m.a_roll);
      stream.next(m.a_pitch);
      stream.next(m.a_yaw);
      stream.next(m.f_x);
      stream.next(m.f_y);
      stream.next(m.f_z);
      stream.next(m.f_roll);
      stream.next(m.f_pitch);
      stream.next(m.f_yaw);
      stream.next(m.use_f_x);
      stream.next(m.use_f_y);
      stream.next(m.use_f_z);
      stream.next(m.use_f_roll);
      stream.next(m.use_f_pitch);
      stream.next(m.use_f_yaw);
      stream.next(m.setpoint_z);
      stream.next(m.setpoint_roll);
      stream.next(m.setpoint_pitch);
      stream.next(m.use_setpoint_z);
      stream.next(m.use_setpoint_roll);
      stream.next(m.use_setpoint_pitch);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ControllerCommand_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tauv_msgs::ControllerCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tauv_msgs::ControllerCommand_<ContainerAllocator>& v)
  {
    s << indent << "a_x: ";
    Printer<float>::stream(s, indent + "  ", v.a_x);
    s << indent << "a_y: ";
    Printer<float>::stream(s, indent + "  ", v.a_y);
    s << indent << "a_z: ";
    Printer<float>::stream(s, indent + "  ", v.a_z);
    s << indent << "a_roll: ";
    Printer<float>::stream(s, indent + "  ", v.a_roll);
    s << indent << "a_pitch: ";
    Printer<float>::stream(s, indent + "  ", v.a_pitch);
    s << indent << "a_yaw: ";
    Printer<float>::stream(s, indent + "  ", v.a_yaw);
    s << indent << "f_x: ";
    Printer<float>::stream(s, indent + "  ", v.f_x);
    s << indent << "f_y: ";
    Printer<float>::stream(s, indent + "  ", v.f_y);
    s << indent << "f_z: ";
    Printer<float>::stream(s, indent + "  ", v.f_z);
    s << indent << "f_roll: ";
    Printer<float>::stream(s, indent + "  ", v.f_roll);
    s << indent << "f_pitch: ";
    Printer<float>::stream(s, indent + "  ", v.f_pitch);
    s << indent << "f_yaw: ";
    Printer<float>::stream(s, indent + "  ", v.f_yaw);
    s << indent << "use_f_x: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.use_f_x);
    s << indent << "use_f_y: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.use_f_y);
    s << indent << "use_f_z: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.use_f_z);
    s << indent << "use_f_roll: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.use_f_roll);
    s << indent << "use_f_pitch: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.use_f_pitch);
    s << indent << "use_f_yaw: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.use_f_yaw);
    s << indent << "setpoint_z: ";
    Printer<float>::stream(s, indent + "  ", v.setpoint_z);
    s << indent << "setpoint_roll: ";
    Printer<float>::stream(s, indent + "  ", v.setpoint_roll);
    s << indent << "setpoint_pitch: ";
    Printer<float>::stream(s, indent + "  ", v.setpoint_pitch);
    s << indent << "use_setpoint_z: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.use_setpoint_z);
    s << indent << "use_setpoint_roll: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.use_setpoint_roll);
    s << indent << "use_setpoint_pitch: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.use_setpoint_pitch);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TAUV_MSGS_MESSAGE_CONTROLLERCOMMAND_H
