// Generated by gencpp from file tauv_msgs/Ctrl_cmd.msg
// DO NOT EDIT!


#ifndef TAUV_MSGS_MESSAGE_CTRL_CMD_H
#define TAUV_MSGS_MESSAGE_CTRL_CMD_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tauv_msgs
{
template <class ContainerAllocator>
struct Ctrl_cmd_
{
  typedef Ctrl_cmd_<ContainerAllocator> Type;

  Ctrl_cmd_()
    : Ctrl_vel_X()
    , Ctrl_vel_Y()
    , Ctrl_vel_Z()
    , Ctrl_fixed_Z()
    , Ctrl_vel_Rol()
    , Ctrl_vel_Pit()
    , Ctrl_vel_Yaw()
    , Ctrl_fixed_Yaw()
    , Ctrl_pivot_1()
    , Ctrl_pivot_2()
    , Ctrl_pivot_3()
    , Ctrl_pivot_4()
    , Ctrl_emagnet_1()
    , Ctrl_emagnet_2()
    , Ctrl_emagnet_3()
    , Ctrl_emagnet_4()
    , Ctrl_arm_joint_1()
    , Ctrl_arm_joint_2()
    , Joy_Button_Y()
    , Joy_Button_X()
    , Joy_Button_A()
    , Joy_Button_B()
    , Joy_Button_LB()
    , Joy_Button_RB()
    , Joy_Button_STICK_LEFT()
    , Joy_Button_STICK_RIGHT()
    , Reset_pwm()  {
      Ctrl_vel_X.assign(0);

      Ctrl_vel_Y.assign(0);

      Ctrl_vel_Z.assign(0);

      Ctrl_fixed_Z.assign(0);

      Ctrl_vel_Rol.assign(0);

      Ctrl_vel_Pit.assign(0);

      Ctrl_vel_Yaw.assign(0);

      Ctrl_fixed_Yaw.assign(0);

      Ctrl_pivot_1.assign(0);

      Ctrl_pivot_2.assign(0);

      Ctrl_pivot_3.assign(0);

      Ctrl_pivot_4.assign(0);

      Ctrl_emagnet_1.assign(0);

      Ctrl_emagnet_2.assign(0);

      Ctrl_emagnet_3.assign(0);

      Ctrl_emagnet_4.assign(0);

      Ctrl_arm_joint_1.assign(0);

      Ctrl_arm_joint_2.assign(0);

      Joy_Button_Y.assign(0);

      Joy_Button_X.assign(0);

      Joy_Button_A.assign(0);

      Joy_Button_B.assign(0);

      Joy_Button_LB.assign(0);

      Joy_Button_RB.assign(0);

      Joy_Button_STICK_LEFT.assign(0);

      Joy_Button_STICK_RIGHT.assign(0);

      Reset_pwm.assign(0);
  }
  Ctrl_cmd_(const ContainerAllocator& _alloc)
    : Ctrl_vel_X()
    , Ctrl_vel_Y()
    , Ctrl_vel_Z()
    , Ctrl_fixed_Z()
    , Ctrl_vel_Rol()
    , Ctrl_vel_Pit()
    , Ctrl_vel_Yaw()
    , Ctrl_fixed_Yaw()
    , Ctrl_pivot_1()
    , Ctrl_pivot_2()
    , Ctrl_pivot_3()
    , Ctrl_pivot_4()
    , Ctrl_emagnet_1()
    , Ctrl_emagnet_2()
    , Ctrl_emagnet_3()
    , Ctrl_emagnet_4()
    , Ctrl_arm_joint_1()
    , Ctrl_arm_joint_2()
    , Joy_Button_Y()
    , Joy_Button_X()
    , Joy_Button_A()
    , Joy_Button_B()
    , Joy_Button_LB()
    , Joy_Button_RB()
    , Joy_Button_STICK_LEFT()
    , Joy_Button_STICK_RIGHT()
    , Reset_pwm()  {
  (void)_alloc;
      Ctrl_vel_X.assign(0);

      Ctrl_vel_Y.assign(0);

      Ctrl_vel_Z.assign(0);

      Ctrl_fixed_Z.assign(0);

      Ctrl_vel_Rol.assign(0);

      Ctrl_vel_Pit.assign(0);

      Ctrl_vel_Yaw.assign(0);

      Ctrl_fixed_Yaw.assign(0);

      Ctrl_pivot_1.assign(0);

      Ctrl_pivot_2.assign(0);

      Ctrl_pivot_3.assign(0);

      Ctrl_pivot_4.assign(0);

      Ctrl_emagnet_1.assign(0);

      Ctrl_emagnet_2.assign(0);

      Ctrl_emagnet_3.assign(0);

      Ctrl_emagnet_4.assign(0);

      Ctrl_arm_joint_1.assign(0);

      Ctrl_arm_joint_2.assign(0);

      Joy_Button_Y.assign(0);

      Joy_Button_X.assign(0);

      Joy_Button_A.assign(0);

      Joy_Button_B.assign(0);

      Joy_Button_LB.assign(0);

      Joy_Button_RB.assign(0);

      Joy_Button_STICK_LEFT.assign(0);

      Joy_Button_STICK_RIGHT.assign(0);

      Reset_pwm.assign(0);
  }



   typedef boost::array<uint8_t, 4>  _Ctrl_vel_X_type;
  _Ctrl_vel_X_type Ctrl_vel_X;

   typedef boost::array<uint8_t, 4>  _Ctrl_vel_Y_type;
  _Ctrl_vel_Y_type Ctrl_vel_Y;

   typedef boost::array<uint8_t, 4>  _Ctrl_vel_Z_type;
  _Ctrl_vel_Z_type Ctrl_vel_Z;

   typedef boost::array<uint8_t, 4>  _Ctrl_fixed_Z_type;
  _Ctrl_fixed_Z_type Ctrl_fixed_Z;

   typedef boost::array<uint8_t, 4>  _Ctrl_vel_Rol_type;
  _Ctrl_vel_Rol_type Ctrl_vel_Rol;

   typedef boost::array<uint8_t, 4>  _Ctrl_vel_Pit_type;
  _Ctrl_vel_Pit_type Ctrl_vel_Pit;

   typedef boost::array<uint8_t, 4>  _Ctrl_vel_Yaw_type;
  _Ctrl_vel_Yaw_type Ctrl_vel_Yaw;

   typedef boost::array<uint8_t, 4>  _Ctrl_fixed_Yaw_type;
  _Ctrl_fixed_Yaw_type Ctrl_fixed_Yaw;

   typedef boost::array<uint8_t, 4>  _Ctrl_pivot_1_type;
  _Ctrl_pivot_1_type Ctrl_pivot_1;

   typedef boost::array<uint8_t, 4>  _Ctrl_pivot_2_type;
  _Ctrl_pivot_2_type Ctrl_pivot_2;

   typedef boost::array<uint8_t, 4>  _Ctrl_pivot_3_type;
  _Ctrl_pivot_3_type Ctrl_pivot_3;

   typedef boost::array<uint8_t, 4>  _Ctrl_pivot_4_type;
  _Ctrl_pivot_4_type Ctrl_pivot_4;

   typedef boost::array<uint8_t, 4>  _Ctrl_emagnet_1_type;
  _Ctrl_emagnet_1_type Ctrl_emagnet_1;

   typedef boost::array<uint8_t, 4>  _Ctrl_emagnet_2_type;
  _Ctrl_emagnet_2_type Ctrl_emagnet_2;

   typedef boost::array<uint8_t, 4>  _Ctrl_emagnet_3_type;
  _Ctrl_emagnet_3_type Ctrl_emagnet_3;

   typedef boost::array<uint8_t, 4>  _Ctrl_emagnet_4_type;
  _Ctrl_emagnet_4_type Ctrl_emagnet_4;

   typedef boost::array<uint8_t, 4>  _Ctrl_arm_joint_1_type;
  _Ctrl_arm_joint_1_type Ctrl_arm_joint_1;

   typedef boost::array<uint8_t, 4>  _Ctrl_arm_joint_2_type;
  _Ctrl_arm_joint_2_type Ctrl_arm_joint_2;

   typedef boost::array<int16_t, 4>  _Joy_Button_Y_type;
  _Joy_Button_Y_type Joy_Button_Y;

   typedef boost::array<int16_t, 4>  _Joy_Button_X_type;
  _Joy_Button_X_type Joy_Button_X;

   typedef boost::array<int16_t, 4>  _Joy_Button_A_type;
  _Joy_Button_A_type Joy_Button_A;

   typedef boost::array<int16_t, 4>  _Joy_Button_B_type;
  _Joy_Button_B_type Joy_Button_B;

   typedef boost::array<int16_t, 4>  _Joy_Button_LB_type;
  _Joy_Button_LB_type Joy_Button_LB;

   typedef boost::array<int16_t, 4>  _Joy_Button_RB_type;
  _Joy_Button_RB_type Joy_Button_RB;

   typedef boost::array<int16_t, 4>  _Joy_Button_STICK_LEFT_type;
  _Joy_Button_STICK_LEFT_type Joy_Button_STICK_LEFT;

   typedef boost::array<int16_t, 4>  _Joy_Button_STICK_RIGHT_type;
  _Joy_Button_STICK_RIGHT_type Joy_Button_STICK_RIGHT;

   typedef boost::array<int16_t, 4>  _Reset_pwm_type;
  _Reset_pwm_type Reset_pwm;





  typedef boost::shared_ptr< ::tauv_msgs::Ctrl_cmd_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tauv_msgs::Ctrl_cmd_<ContainerAllocator> const> ConstPtr;

}; // struct Ctrl_cmd_

typedef ::tauv_msgs::Ctrl_cmd_<std::allocator<void> > Ctrl_cmd;

typedef boost::shared_ptr< ::tauv_msgs::Ctrl_cmd > Ctrl_cmdPtr;
typedef boost::shared_ptr< ::tauv_msgs::Ctrl_cmd const> Ctrl_cmdConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tauv_msgs::Ctrl_cmd_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tauv_msgs::Ctrl_cmd_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tauv_msgs::Ctrl_cmd_<ContainerAllocator1> & lhs, const ::tauv_msgs::Ctrl_cmd_<ContainerAllocator2> & rhs)
{
  return lhs.Ctrl_vel_X == rhs.Ctrl_vel_X &&
    lhs.Ctrl_vel_Y == rhs.Ctrl_vel_Y &&
    lhs.Ctrl_vel_Z == rhs.Ctrl_vel_Z &&
    lhs.Ctrl_fixed_Z == rhs.Ctrl_fixed_Z &&
    lhs.Ctrl_vel_Rol == rhs.Ctrl_vel_Rol &&
    lhs.Ctrl_vel_Pit == rhs.Ctrl_vel_Pit &&
    lhs.Ctrl_vel_Yaw == rhs.Ctrl_vel_Yaw &&
    lhs.Ctrl_fixed_Yaw == rhs.Ctrl_fixed_Yaw &&
    lhs.Ctrl_pivot_1 == rhs.Ctrl_pivot_1 &&
    lhs.Ctrl_pivot_2 == rhs.Ctrl_pivot_2 &&
    lhs.Ctrl_pivot_3 == rhs.Ctrl_pivot_3 &&
    lhs.Ctrl_pivot_4 == rhs.Ctrl_pivot_4 &&
    lhs.Ctrl_emagnet_1 == rhs.Ctrl_emagnet_1 &&
    lhs.Ctrl_emagnet_2 == rhs.Ctrl_emagnet_2 &&
    lhs.Ctrl_emagnet_3 == rhs.Ctrl_emagnet_3 &&
    lhs.Ctrl_emagnet_4 == rhs.Ctrl_emagnet_4 &&
    lhs.Ctrl_arm_joint_1 == rhs.Ctrl_arm_joint_1 &&
    lhs.Ctrl_arm_joint_2 == rhs.Ctrl_arm_joint_2 &&
    lhs.Joy_Button_Y == rhs.Joy_Button_Y &&
    lhs.Joy_Button_X == rhs.Joy_Button_X &&
    lhs.Joy_Button_A == rhs.Joy_Button_A &&
    lhs.Joy_Button_B == rhs.Joy_Button_B &&
    lhs.Joy_Button_LB == rhs.Joy_Button_LB &&
    lhs.Joy_Button_RB == rhs.Joy_Button_RB &&
    lhs.Joy_Button_STICK_LEFT == rhs.Joy_Button_STICK_LEFT &&
    lhs.Joy_Button_STICK_RIGHT == rhs.Joy_Button_STICK_RIGHT &&
    lhs.Reset_pwm == rhs.Reset_pwm;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tauv_msgs::Ctrl_cmd_<ContainerAllocator1> & lhs, const ::tauv_msgs::Ctrl_cmd_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tauv_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::tauv_msgs::Ctrl_cmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tauv_msgs::Ctrl_cmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tauv_msgs::Ctrl_cmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tauv_msgs::Ctrl_cmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tauv_msgs::Ctrl_cmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tauv_msgs::Ctrl_cmd_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tauv_msgs::Ctrl_cmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7a746ffc64e1d5a26fb5d6cba04e63c2";
  }

  static const char* value(const ::tauv_msgs::Ctrl_cmd_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7a746ffc64e1d5a2ULL;
  static const uint64_t static_value2 = 0x6fb5d6cba04e63c2ULL;
};

template<class ContainerAllocator>
struct DataType< ::tauv_msgs::Ctrl_cmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tauv_msgs/Ctrl_cmd";
  }

  static const char* value(const ::tauv_msgs::Ctrl_cmd_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tauv_msgs::Ctrl_cmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"uint8[4] Ctrl_vel_X\n"
"uint8[4] Ctrl_vel_Y\n"
"uint8[4] Ctrl_vel_Z\n"
"uint8[4] Ctrl_fixed_Z\n"
"uint8[4] Ctrl_vel_Rol\n"
"uint8[4] Ctrl_vel_Pit\n"
"uint8[4] Ctrl_vel_Yaw\n"
"uint8[4] Ctrl_fixed_Yaw\n"
"\n"
"uint8[4] Ctrl_pivot_1\n"
"uint8[4] Ctrl_pivot_2\n"
"uint8[4] Ctrl_pivot_3\n"
"uint8[4] Ctrl_pivot_4\n"
"\n"
"uint8[4] Ctrl_emagnet_1\n"
"uint8[4] Ctrl_emagnet_2\n"
"uint8[4] Ctrl_emagnet_3\n"
"uint8[4] Ctrl_emagnet_4\n"
"\n"
"uint8[4] Ctrl_arm_joint_1\n"
"uint8[4] Ctrl_arm_joint_2\n"
"\n"
"int16[4] Joy_Button_Y\n"
"int16[4] Joy_Button_X\n"
"int16[4] Joy_Button_A\n"
"int16[4] Joy_Button_B\n"
"int16[4] Joy_Button_LB\n"
"int16[4] Joy_Button_RB\n"
"int16[4] Joy_Button_STICK_LEFT\n"
"int16[4] Joy_Button_STICK_RIGHT\n"
"int16[4] Reset_pwm\n"
;
  }

  static const char* value(const ::tauv_msgs::Ctrl_cmd_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tauv_msgs::Ctrl_cmd_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Ctrl_vel_X);
      stream.next(m.Ctrl_vel_Y);
      stream.next(m.Ctrl_vel_Z);
      stream.next(m.Ctrl_fixed_Z);
      stream.next(m.Ctrl_vel_Rol);
      stream.next(m.Ctrl_vel_Pit);
      stream.next(m.Ctrl_vel_Yaw);
      stream.next(m.Ctrl_fixed_Yaw);
      stream.next(m.Ctrl_pivot_1);
      stream.next(m.Ctrl_pivot_2);
      stream.next(m.Ctrl_pivot_3);
      stream.next(m.Ctrl_pivot_4);
      stream.next(m.Ctrl_emagnet_1);
      stream.next(m.Ctrl_emagnet_2);
      stream.next(m.Ctrl_emagnet_3);
      stream.next(m.Ctrl_emagnet_4);
      stream.next(m.Ctrl_arm_joint_1);
      stream.next(m.Ctrl_arm_joint_2);
      stream.next(m.Joy_Button_Y);
      stream.next(m.Joy_Button_X);
      stream.next(m.Joy_Button_A);
      stream.next(m.Joy_Button_B);
      stream.next(m.Joy_Button_LB);
      stream.next(m.Joy_Button_RB);
      stream.next(m.Joy_Button_STICK_LEFT);
      stream.next(m.Joy_Button_STICK_RIGHT);
      stream.next(m.Reset_pwm);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Ctrl_cmd_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tauv_msgs::Ctrl_cmd_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tauv_msgs::Ctrl_cmd_<ContainerAllocator>& v)
  {
    s << indent << "Ctrl_vel_X[]" << std::endl;
    for (size_t i = 0; i < v.Ctrl_vel_X.size(); ++i)
    {
      s << indent << "  Ctrl_vel_X[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.Ctrl_vel_X[i]);
    }
    s << indent << "Ctrl_vel_Y[]" << std::endl;
    for (size_t i = 0; i < v.Ctrl_vel_Y.size(); ++i)
    {
      s << indent << "  Ctrl_vel_Y[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.Ctrl_vel_Y[i]);
    }
    s << indent << "Ctrl_vel_Z[]" << std::endl;
    for (size_t i = 0; i < v.Ctrl_vel_Z.size(); ++i)
    {
      s << indent << "  Ctrl_vel_Z[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.Ctrl_vel_Z[i]);
    }
    s << indent << "Ctrl_fixed_Z[]" << std::endl;
    for (size_t i = 0; i < v.Ctrl_fixed_Z.size(); ++i)
    {
      s << indent << "  Ctrl_fixed_Z[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.Ctrl_fixed_Z[i]);
    }
    s << indent << "Ctrl_vel_Rol[]" << std::endl;
    for (size_t i = 0; i < v.Ctrl_vel_Rol.size(); ++i)
    {
      s << indent << "  Ctrl_vel_Rol[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.Ctrl_vel_Rol[i]);
    }
    s << indent << "Ctrl_vel_Pit[]" << std::endl;
    for (size_t i = 0; i < v.Ctrl_vel_Pit.size(); ++i)
    {
      s << indent << "  Ctrl_vel_Pit[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.Ctrl_vel_Pit[i]);
    }
    s << indent << "Ctrl_vel_Yaw[]" << std::endl;
    for (size_t i = 0; i < v.Ctrl_vel_Yaw.size(); ++i)
    {
      s << indent << "  Ctrl_vel_Yaw[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.Ctrl_vel_Yaw[i]);
    }
    s << indent << "Ctrl_fixed_Yaw[]" << std::endl;
    for (size_t i = 0; i < v.Ctrl_fixed_Yaw.size(); ++i)
    {
      s << indent << "  Ctrl_fixed_Yaw[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.Ctrl_fixed_Yaw[i]);
    }
    s << indent << "Ctrl_pivot_1[]" << std::endl;
    for (size_t i = 0; i < v.Ctrl_pivot_1.size(); ++i)
    {
      s << indent << "  Ctrl_pivot_1[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.Ctrl_pivot_1[i]);
    }
    s << indent << "Ctrl_pivot_2[]" << std::endl;
    for (size_t i = 0; i < v.Ctrl_pivot_2.size(); ++i)
    {
      s << indent << "  Ctrl_pivot_2[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.Ctrl_pivot_2[i]);
    }
    s << indent << "Ctrl_pivot_3[]" << std::endl;
    for (size_t i = 0; i < v.Ctrl_pivot_3.size(); ++i)
    {
      s << indent << "  Ctrl_pivot_3[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.Ctrl_pivot_3[i]);
    }
    s << indent << "Ctrl_pivot_4[]" << std::endl;
    for (size_t i = 0; i < v.Ctrl_pivot_4.size(); ++i)
    {
      s << indent << "  Ctrl_pivot_4[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.Ctrl_pivot_4[i]);
    }
    s << indent << "Ctrl_emagnet_1[]" << std::endl;
    for (size_t i = 0; i < v.Ctrl_emagnet_1.size(); ++i)
    {
      s << indent << "  Ctrl_emagnet_1[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.Ctrl_emagnet_1[i]);
    }
    s << indent << "Ctrl_emagnet_2[]" << std::endl;
    for (size_t i = 0; i < v.Ctrl_emagnet_2.size(); ++i)
    {
      s << indent << "  Ctrl_emagnet_2[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.Ctrl_emagnet_2[i]);
    }
    s << indent << "Ctrl_emagnet_3[]" << std::endl;
    for (size_t i = 0; i < v.Ctrl_emagnet_3.size(); ++i)
    {
      s << indent << "  Ctrl_emagnet_3[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.Ctrl_emagnet_3[i]);
    }
    s << indent << "Ctrl_emagnet_4[]" << std::endl;
    for (size_t i = 0; i < v.Ctrl_emagnet_4.size(); ++i)
    {
      s << indent << "  Ctrl_emagnet_4[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.Ctrl_emagnet_4[i]);
    }
    s << indent << "Ctrl_arm_joint_1[]" << std::endl;
    for (size_t i = 0; i < v.Ctrl_arm_joint_1.size(); ++i)
    {
      s << indent << "  Ctrl_arm_joint_1[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.Ctrl_arm_joint_1[i]);
    }
    s << indent << "Ctrl_arm_joint_2[]" << std::endl;
    for (size_t i = 0; i < v.Ctrl_arm_joint_2.size(); ++i)
    {
      s << indent << "  Ctrl_arm_joint_2[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.Ctrl_arm_joint_2[i]);
    }
    s << indent << "Joy_Button_Y[]" << std::endl;
    for (size_t i = 0; i < v.Joy_Button_Y.size(); ++i)
    {
      s << indent << "  Joy_Button_Y[" << i << "]: ";
      Printer<int16_t>::stream(s, indent + "  ", v.Joy_Button_Y[i]);
    }
    s << indent << "Joy_Button_X[]" << std::endl;
    for (size_t i = 0; i < v.Joy_Button_X.size(); ++i)
    {
      s << indent << "  Joy_Button_X[" << i << "]: ";
      Printer<int16_t>::stream(s, indent + "  ", v.Joy_Button_X[i]);
    }
    s << indent << "Joy_Button_A[]" << std::endl;
    for (size_t i = 0; i < v.Joy_Button_A.size(); ++i)
    {
      s << indent << "  Joy_Button_A[" << i << "]: ";
      Printer<int16_t>::stream(s, indent + "  ", v.Joy_Button_A[i]);
    }
    s << indent << "Joy_Button_B[]" << std::endl;
    for (size_t i = 0; i < v.Joy_Button_B.size(); ++i)
    {
      s << indent << "  Joy_Button_B[" << i << "]: ";
      Printer<int16_t>::stream(s, indent + "  ", v.Joy_Button_B[i]);
    }
    s << indent << "Joy_Button_LB[]" << std::endl;
    for (size_t i = 0; i < v.Joy_Button_LB.size(); ++i)
    {
      s << indent << "  Joy_Button_LB[" << i << "]: ";
      Printer<int16_t>::stream(s, indent + "  ", v.Joy_Button_LB[i]);
    }
    s << indent << "Joy_Button_RB[]" << std::endl;
    for (size_t i = 0; i < v.Joy_Button_RB.size(); ++i)
    {
      s << indent << "  Joy_Button_RB[" << i << "]: ";
      Printer<int16_t>::stream(s, indent + "  ", v.Joy_Button_RB[i]);
    }
    s << indent << "Joy_Button_STICK_LEFT[]" << std::endl;
    for (size_t i = 0; i < v.Joy_Button_STICK_LEFT.size(); ++i)
    {
      s << indent << "  Joy_Button_STICK_LEFT[" << i << "]: ";
      Printer<int16_t>::stream(s, indent + "  ", v.Joy_Button_STICK_LEFT[i]);
    }
    s << indent << "Joy_Button_STICK_RIGHT[]" << std::endl;
    for (size_t i = 0; i < v.Joy_Button_STICK_RIGHT.size(); ++i)
    {
      s << indent << "  Joy_Button_STICK_RIGHT[" << i << "]: ";
      Printer<int16_t>::stream(s, indent + "  ", v.Joy_Button_STICK_RIGHT[i]);
    }
    s << indent << "Reset_pwm[]" << std::endl;
    for (size_t i = 0; i < v.Reset_pwm.size(); ++i)
    {
      s << indent << "  Reset_pwm[" << i << "]: ";
      Printer<int16_t>::stream(s, indent + "  ", v.Reset_pwm[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // TAUV_MSGS_MESSAGE_CTRL_CMD_H
