// Generated by gencpp from file tauv_msgs/DynamicsParameterConfigUpdate.msg
// DO NOT EDIT!


#ifndef TAUV_MSGS_MESSAGE_DYNAMICSPARAMETERCONFIGUPDATE_H
#define TAUV_MSGS_MESSAGE_DYNAMICSPARAMETERCONFIGUPDATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tauv_msgs
{
template <class ContainerAllocator>
struct DynamicsParameterConfigUpdate_
{
  typedef DynamicsParameterConfigUpdate_<ContainerAllocator> Type;

  DynamicsParameterConfigUpdate_()
    : name()
    , update_initial_value(false)
    , initial_value(0.0)
    , update_fixed(false)
    , fixed(false)
    , update_initial_covariance(false)
    , initial_covariance(0.0)
    , update_process_covariance(false)
    , process_covariance(0.0)
    , update_limits(false)
    , limits()
    , reset(false)  {
      limits.assign(0.0);
  }
  DynamicsParameterConfigUpdate_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , update_initial_value(false)
    , initial_value(0.0)
    , update_fixed(false)
    , fixed(false)
    , update_initial_covariance(false)
    , initial_covariance(0.0)
    , update_process_covariance(false)
    , process_covariance(0.0)
    , update_limits(false)
    , limits()
    , reset(false)  {
  (void)_alloc;
      limits.assign(0.0);
  }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _name_type;
  _name_type name;

   typedef uint8_t _update_initial_value_type;
  _update_initial_value_type update_initial_value;

   typedef double _initial_value_type;
  _initial_value_type initial_value;

   typedef uint8_t _update_fixed_type;
  _update_fixed_type update_fixed;

   typedef uint8_t _fixed_type;
  _fixed_type fixed;

   typedef uint8_t _update_initial_covariance_type;
  _update_initial_covariance_type update_initial_covariance;

   typedef double _initial_covariance_type;
  _initial_covariance_type initial_covariance;

   typedef uint8_t _update_process_covariance_type;
  _update_process_covariance_type update_process_covariance;

   typedef double _process_covariance_type;
  _process_covariance_type process_covariance;

   typedef uint8_t _update_limits_type;
  _update_limits_type update_limits;

   typedef boost::array<double, 2>  _limits_type;
  _limits_type limits;

   typedef uint8_t _reset_type;
  _reset_type reset;





  typedef boost::shared_ptr< ::tauv_msgs::DynamicsParameterConfigUpdate_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tauv_msgs::DynamicsParameterConfigUpdate_<ContainerAllocator> const> ConstPtr;

}; // struct DynamicsParameterConfigUpdate_

typedef ::tauv_msgs::DynamicsParameterConfigUpdate_<std::allocator<void> > DynamicsParameterConfigUpdate;

typedef boost::shared_ptr< ::tauv_msgs::DynamicsParameterConfigUpdate > DynamicsParameterConfigUpdatePtr;
typedef boost::shared_ptr< ::tauv_msgs::DynamicsParameterConfigUpdate const> DynamicsParameterConfigUpdateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tauv_msgs::DynamicsParameterConfigUpdate_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tauv_msgs::DynamicsParameterConfigUpdate_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tauv_msgs::DynamicsParameterConfigUpdate_<ContainerAllocator1> & lhs, const ::tauv_msgs::DynamicsParameterConfigUpdate_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name &&
    lhs.update_initial_value == rhs.update_initial_value &&
    lhs.initial_value == rhs.initial_value &&
    lhs.update_fixed == rhs.update_fixed &&
    lhs.fixed == rhs.fixed &&
    lhs.update_initial_covariance == rhs.update_initial_covariance &&
    lhs.initial_covariance == rhs.initial_covariance &&
    lhs.update_process_covariance == rhs.update_process_covariance &&
    lhs.process_covariance == rhs.process_covariance &&
    lhs.update_limits == rhs.update_limits &&
    lhs.limits == rhs.limits &&
    lhs.reset == rhs.reset;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tauv_msgs::DynamicsParameterConfigUpdate_<ContainerAllocator1> & lhs, const ::tauv_msgs::DynamicsParameterConfigUpdate_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tauv_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::tauv_msgs::DynamicsParameterConfigUpdate_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tauv_msgs::DynamicsParameterConfigUpdate_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tauv_msgs::DynamicsParameterConfigUpdate_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tauv_msgs::DynamicsParameterConfigUpdate_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tauv_msgs::DynamicsParameterConfigUpdate_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tauv_msgs::DynamicsParameterConfigUpdate_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tauv_msgs::DynamicsParameterConfigUpdate_<ContainerAllocator> >
{
  static const char* value()
  {
    return "31294fd8c67bf91ba516e5502711b385";
  }

  static const char* value(const ::tauv_msgs::DynamicsParameterConfigUpdate_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x31294fd8c67bf91bULL;
  static const uint64_t static_value2 = 0xa516e5502711b385ULL;
};

template<class ContainerAllocator>
struct DataType< ::tauv_msgs::DynamicsParameterConfigUpdate_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tauv_msgs/DynamicsParameterConfigUpdate";
  }

  static const char* value(const ::tauv_msgs::DynamicsParameterConfigUpdate_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tauv_msgs::DynamicsParameterConfigUpdate_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n"
"\n"
"bool update_initial_value\n"
"float64 initial_value\n"
"\n"
"bool update_fixed\n"
"bool fixed\n"
"\n"
"bool update_initial_covariance\n"
"float64 initial_covariance\n"
"\n"
"bool update_process_covariance\n"
"float64 process_covariance\n"
"\n"
"bool update_limits\n"
"float64[2] limits\n"
"\n"
"bool reset\n"
"\n"
"\n"
;
  }

  static const char* value(const ::tauv_msgs::DynamicsParameterConfigUpdate_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tauv_msgs::DynamicsParameterConfigUpdate_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.update_initial_value);
      stream.next(m.initial_value);
      stream.next(m.update_fixed);
      stream.next(m.fixed);
      stream.next(m.update_initial_covariance);
      stream.next(m.initial_covariance);
      stream.next(m.update_process_covariance);
      stream.next(m.process_covariance);
      stream.next(m.update_limits);
      stream.next(m.limits);
      stream.next(m.reset);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DynamicsParameterConfigUpdate_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tauv_msgs::DynamicsParameterConfigUpdate_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tauv_msgs::DynamicsParameterConfigUpdate_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.name);
    s << indent << "update_initial_value: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.update_initial_value);
    s << indent << "initial_value: ";
    Printer<double>::stream(s, indent + "  ", v.initial_value);
    s << indent << "update_fixed: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.update_fixed);
    s << indent << "fixed: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.fixed);
    s << indent << "update_initial_covariance: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.update_initial_covariance);
    s << indent << "initial_covariance: ";
    Printer<double>::stream(s, indent + "  ", v.initial_covariance);
    s << indent << "update_process_covariance: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.update_process_covariance);
    s << indent << "process_covariance: ";
    Printer<double>::stream(s, indent + "  ", v.process_covariance);
    s << indent << "update_limits: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.update_limits);
    s << indent << "limits[]" << std::endl;
    for (size_t i = 0; i < v.limits.size(); ++i)
    {
      s << indent << "  limits[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.limits[i]);
    }
    s << indent << "reset: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.reset);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TAUV_MSGS_MESSAGE_DYNAMICSPARAMETERCONFIGUPDATE_H
