// Generated by gencpp from file tauv_msgs/FeatureDetection.msg
// DO NOT EDIT!


#ifndef TAUV_MSGS_MESSAGE_FEATUREDETECTION_H
#define TAUV_MSGS_MESSAGE_FEATUREDETECTION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Point.h>
#include <geometry_msgs/Point.h>

namespace tauv_msgs
{
template <class ContainerAllocator>
struct FeatureDetection_
{
  typedef FeatureDetection_<ContainerAllocator> Type;

  FeatureDetection_()
    : header()
    , position()
    , orientation()
    , tag()
    , confidence(0.0)
    , SE2(false)  {
    }
  FeatureDetection_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , position(_alloc)
    , orientation(_alloc)
    , tag(_alloc)
    , confidence(0.0)
    , SE2(false)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _position_type;
  _position_type position;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _orientation_type;
  _orientation_type orientation;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _tag_type;
  _tag_type tag;

   typedef double _confidence_type;
  _confidence_type confidence;

   typedef uint8_t _SE2_type;
  _SE2_type SE2;





  typedef boost::shared_ptr< ::tauv_msgs::FeatureDetection_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tauv_msgs::FeatureDetection_<ContainerAllocator> const> ConstPtr;

}; // struct FeatureDetection_

typedef ::tauv_msgs::FeatureDetection_<std::allocator<void> > FeatureDetection;

typedef boost::shared_ptr< ::tauv_msgs::FeatureDetection > FeatureDetectionPtr;
typedef boost::shared_ptr< ::tauv_msgs::FeatureDetection const> FeatureDetectionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tauv_msgs::FeatureDetection_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tauv_msgs::FeatureDetection_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tauv_msgs::FeatureDetection_<ContainerAllocator1> & lhs, const ::tauv_msgs::FeatureDetection_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.position == rhs.position &&
    lhs.orientation == rhs.orientation &&
    lhs.tag == rhs.tag &&
    lhs.confidence == rhs.confidence &&
    lhs.SE2 == rhs.SE2;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tauv_msgs::FeatureDetection_<ContainerAllocator1> & lhs, const ::tauv_msgs::FeatureDetection_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tauv_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::tauv_msgs::FeatureDetection_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tauv_msgs::FeatureDetection_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tauv_msgs::FeatureDetection_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tauv_msgs::FeatureDetection_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tauv_msgs::FeatureDetection_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tauv_msgs::FeatureDetection_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tauv_msgs::FeatureDetection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a256c9fb7a965addac0015cd369172cd";
  }

  static const char* value(const ::tauv_msgs::FeatureDetection_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa256c9fb7a965addULL;
  static const uint64_t static_value2 = 0xac0015cd369172cdULL;
};

template<class ContainerAllocator>
struct DataType< ::tauv_msgs::FeatureDetection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tauv_msgs/FeatureDetection";
  }

  static const char* value(const ::tauv_msgs::FeatureDetection_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tauv_msgs::FeatureDetection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"geometry_msgs/Point position #SE2 msgs will only use x y\n"
"geometry_msgs/Point orientation #SE2 msgs will only use x (theta)\n"
"string tag\n"
"float64 confidence\n"
"bool SE2\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::tauv_msgs::FeatureDetection_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tauv_msgs::FeatureDetection_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.position);
      stream.next(m.orientation);
      stream.next(m.tag);
      stream.next(m.confidence);
      stream.next(m.SE2);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FeatureDetection_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tauv_msgs::FeatureDetection_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tauv_msgs::FeatureDetection_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "position: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.position);
    s << indent << "orientation: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.orientation);
    s << indent << "tag: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.tag);
    s << indent << "confidence: ";
    Printer<double>::stream(s, indent + "  ", v.confidence);
    s << indent << "SE2: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.SE2);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TAUV_MSGS_MESSAGE_FEATUREDETECTION_H
