// Generated by gencpp from file tauv_msgs/FeatureDetectionsSync.msg
// DO NOT EDIT!


#ifndef TAUV_MSGS_MESSAGE_FEATUREDETECTIONSSYNC_H
#define TAUV_MSGS_MESSAGE_FEATUREDETECTIONSSYNC_H

#include <ros/service_traits.h>


#include <tauv_msgs/FeatureDetectionsSyncRequest.h>
#include <tauv_msgs/FeatureDetectionsSyncResponse.h>


namespace tauv_msgs
{

struct FeatureDetectionsSync
{

typedef FeatureDetectionsSyncRequest Request;
typedef FeatureDetectionsSyncResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct FeatureDetectionsSync
} // namespace tauv_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tauv_msgs::FeatureDetectionsSync > {
  static const char* value()
  {
    return "2da451629f8ca3f1c8b6e832ba66c6c5";
  }

  static const char* value(const ::tauv_msgs::FeatureDetectionsSync&) { return value(); }
};

template<>
struct DataType< ::tauv_msgs::FeatureDetectionsSync > {
  static const char* value()
  {
    return "tauv_msgs/FeatureDetectionsSync";
  }

  static const char* value(const ::tauv_msgs::FeatureDetectionsSync&) { return value(); }
};


// service_traits::MD5Sum< ::tauv_msgs::FeatureDetectionsSyncRequest> should match
// service_traits::MD5Sum< ::tauv_msgs::FeatureDetectionsSync >
template<>
struct MD5Sum< ::tauv_msgs::FeatureDetectionsSyncRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tauv_msgs::FeatureDetectionsSync >::value();
  }
  static const char* value(const ::tauv_msgs::FeatureDetectionsSyncRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tauv_msgs::FeatureDetectionsSyncRequest> should match
// service_traits::DataType< ::tauv_msgs::FeatureDetectionsSync >
template<>
struct DataType< ::tauv_msgs::FeatureDetectionsSyncRequest>
{
  static const char* value()
  {
    return DataType< ::tauv_msgs::FeatureDetectionsSync >::value();
  }
  static const char* value(const ::tauv_msgs::FeatureDetectionsSyncRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tauv_msgs::FeatureDetectionsSyncResponse> should match
// service_traits::MD5Sum< ::tauv_msgs::FeatureDetectionsSync >
template<>
struct MD5Sum< ::tauv_msgs::FeatureDetectionsSyncResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tauv_msgs::FeatureDetectionsSync >::value();
  }
  static const char* value(const ::tauv_msgs::FeatureDetectionsSyncResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tauv_msgs::FeatureDetectionsSyncResponse> should match
// service_traits::DataType< ::tauv_msgs::FeatureDetectionsSync >
template<>
struct DataType< ::tauv_msgs::FeatureDetectionsSyncResponse>
{
  static const char* value()
  {
    return DataType< ::tauv_msgs::FeatureDetectionsSync >::value();
  }
  static const char* value(const ::tauv_msgs::FeatureDetectionsSyncResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TAUV_MSGS_MESSAGE_FEATUREDETECTIONSSYNC_H
