// Generated by gencpp from file tauv_msgs/GateDetection.msg
// DO NOT EDIT!


#ifndef TAUV_MSGS_MESSAGE_GATEDETECTION_H
#define TAUV_MSGS_MESSAGE_GATEDETECTION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>
#include <geometry_msgs/Point.h>
#include <geometry_msgs/Point.h>

namespace tauv_msgs
{
template <class ContainerAllocator>
struct GateDetection_
{
  typedef GateDetection_<ContainerAllocator> Type;

  GateDetection_()
    : leftCorner()
    , rightCorner()
    , centerPoint()  {
    }
  GateDetection_(const ContainerAllocator& _alloc)
    : leftCorner(_alloc)
    , rightCorner(_alloc)
    , centerPoint(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _leftCorner_type;
  _leftCorner_type leftCorner;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _rightCorner_type;
  _rightCorner_type rightCorner;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _centerPoint_type;
  _centerPoint_type centerPoint;





  typedef boost::shared_ptr< ::tauv_msgs::GateDetection_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tauv_msgs::GateDetection_<ContainerAllocator> const> ConstPtr;

}; // struct GateDetection_

typedef ::tauv_msgs::GateDetection_<std::allocator<void> > GateDetection;

typedef boost::shared_ptr< ::tauv_msgs::GateDetection > GateDetectionPtr;
typedef boost::shared_ptr< ::tauv_msgs::GateDetection const> GateDetectionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tauv_msgs::GateDetection_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tauv_msgs::GateDetection_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tauv_msgs::GateDetection_<ContainerAllocator1> & lhs, const ::tauv_msgs::GateDetection_<ContainerAllocator2> & rhs)
{
  return lhs.leftCorner == rhs.leftCorner &&
    lhs.rightCorner == rhs.rightCorner &&
    lhs.centerPoint == rhs.centerPoint;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tauv_msgs::GateDetection_<ContainerAllocator1> & lhs, const ::tauv_msgs::GateDetection_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tauv_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::tauv_msgs::GateDetection_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tauv_msgs::GateDetection_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tauv_msgs::GateDetection_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tauv_msgs::GateDetection_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tauv_msgs::GateDetection_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tauv_msgs::GateDetection_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tauv_msgs::GateDetection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8a67a29e701c68c820bd45950230c212";
  }

  static const char* value(const ::tauv_msgs::GateDetection_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8a67a29e701c68c8ULL;
  static const uint64_t static_value2 = 0x20bd45950230c212ULL;
};

template<class ContainerAllocator>
struct DataType< ::tauv_msgs::GateDetection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tauv_msgs/GateDetection";
  }

  static const char* value(const ::tauv_msgs::GateDetection_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tauv_msgs::GateDetection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Point leftCorner\n"
"geometry_msgs/Point rightCorner\n"
"geometry_msgs/Point centerPoint\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::tauv_msgs::GateDetection_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tauv_msgs::GateDetection_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.leftCorner);
      stream.next(m.rightCorner);
      stream.next(m.centerPoint);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GateDetection_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tauv_msgs::GateDetection_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tauv_msgs::GateDetection_<ContainerAllocator>& v)
  {
    s << indent << "leftCorner: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.leftCorner);
    s << indent << "rightCorner: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.rightCorner);
    s << indent << "centerPoint: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.centerPoint);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TAUV_MSGS_MESSAGE_GATEDETECTION_H
