// Generated by gencpp from file tauv_msgs/GetCameraInfoRequest.msg
// DO NOT EDIT!


#ifndef TAUV_MSGS_MESSAGE_GETCAMERAINFOREQUEST_H
#define TAUV_MSGS_MESSAGE_GETCAMERAINFOREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tauv_msgs
{
template <class ContainerAllocator>
struct GetCameraInfoRequest_
{
  typedef GetCameraInfoRequest_<ContainerAllocator> Type;

  GetCameraInfoRequest_()
    : camera_name()  {
    }
  GetCameraInfoRequest_(const ContainerAllocator& _alloc)
    : camera_name(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _camera_name_type;
  _camera_name_type camera_name;





  typedef boost::shared_ptr< ::tauv_msgs::GetCameraInfoRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tauv_msgs::GetCameraInfoRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetCameraInfoRequest_

typedef ::tauv_msgs::GetCameraInfoRequest_<std::allocator<void> > GetCameraInfoRequest;

typedef boost::shared_ptr< ::tauv_msgs::GetCameraInfoRequest > GetCameraInfoRequestPtr;
typedef boost::shared_ptr< ::tauv_msgs::GetCameraInfoRequest const> GetCameraInfoRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tauv_msgs::GetCameraInfoRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tauv_msgs::GetCameraInfoRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tauv_msgs::GetCameraInfoRequest_<ContainerAllocator1> & lhs, const ::tauv_msgs::GetCameraInfoRequest_<ContainerAllocator2> & rhs)
{
  return lhs.camera_name == rhs.camera_name;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tauv_msgs::GetCameraInfoRequest_<ContainerAllocator1> & lhs, const ::tauv_msgs::GetCameraInfoRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tauv_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::tauv_msgs::GetCameraInfoRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tauv_msgs::GetCameraInfoRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tauv_msgs::GetCameraInfoRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tauv_msgs::GetCameraInfoRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tauv_msgs::GetCameraInfoRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tauv_msgs::GetCameraInfoRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tauv_msgs::GetCameraInfoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0013e8d6e7250e2f5a5c671a35c835e3";
  }

  static const char* value(const ::tauv_msgs::GetCameraInfoRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0013e8d6e7250e2fULL;
  static const uint64_t static_value2 = 0x5a5c671a35c835e3ULL;
};

template<class ContainerAllocator>
struct DataType< ::tauv_msgs::GetCameraInfoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tauv_msgs/GetCameraInfoRequest";
  }

  static const char* value(const ::tauv_msgs::GetCameraInfoRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tauv_msgs::GetCameraInfoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string camera_name\n"
;
  }

  static const char* value(const ::tauv_msgs::GetCameraInfoRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tauv_msgs::GetCameraInfoRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.camera_name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetCameraInfoRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tauv_msgs::GetCameraInfoRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tauv_msgs::GetCameraInfoRequest_<ContainerAllocator>& v)
  {
    s << indent << "camera_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.camera_name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TAUV_MSGS_MESSAGE_GETCAMERAINFOREQUEST_H
