// Generated by gencpp from file tauv_msgs/GetTrajectory.msg
// DO NOT EDIT!


#ifndef TAUV_MSGS_MESSAGE_GETTRAJECTORY_H
#define TAUV_MSGS_MESSAGE_GETTRAJECTORY_H

#include <ros/service_traits.h>


#include <tauv_msgs/GetTrajectoryRequest.h>
#include <tauv_msgs/GetTrajectoryResponse.h>


namespace tauv_msgs
{

struct GetTrajectory
{

typedef GetTrajectoryRequest Request;
typedef GetTrajectoryResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetTrajectory
} // namespace tauv_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tauv_msgs::GetTrajectory > {
  static const char* value()
  {
    return "a821c3e69b37025c156850881154fe33";
  }

  static const char* value(const ::tauv_msgs::GetTrajectory&) { return value(); }
};

template<>
struct DataType< ::tauv_msgs::GetTrajectory > {
  static const char* value()
  {
    return "tauv_msgs/GetTrajectory";
  }

  static const char* value(const ::tauv_msgs::GetTrajectory&) { return value(); }
};


// service_traits::MD5Sum< ::tauv_msgs::GetTrajectoryRequest> should match
// service_traits::MD5Sum< ::tauv_msgs::GetTrajectory >
template<>
struct MD5Sum< ::tauv_msgs::GetTrajectoryRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tauv_msgs::GetTrajectory >::value();
  }
  static const char* value(const ::tauv_msgs::GetTrajectoryRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tauv_msgs::GetTrajectoryRequest> should match
// service_traits::DataType< ::tauv_msgs::GetTrajectory >
template<>
struct DataType< ::tauv_msgs::GetTrajectoryRequest>
{
  static const char* value()
  {
    return DataType< ::tauv_msgs::GetTrajectory >::value();
  }
  static const char* value(const ::tauv_msgs::GetTrajectoryRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tauv_msgs::GetTrajectoryResponse> should match
// service_traits::MD5Sum< ::tauv_msgs::GetTrajectory >
template<>
struct MD5Sum< ::tauv_msgs::GetTrajectoryResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tauv_msgs::GetTrajectory >::value();
  }
  static const char* value(const ::tauv_msgs::GetTrajectoryResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tauv_msgs::GetTrajectoryResponse> should match
// service_traits::DataType< ::tauv_msgs::GetTrajectory >
template<>
struct DataType< ::tauv_msgs::GetTrajectoryResponse>
{
  static const char* value()
  {
    return DataType< ::tauv_msgs::GetTrajectory >::value();
  }
  static const char* value(const ::tauv_msgs::GetTrajectoryResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TAUV_MSGS_MESSAGE_GETTRAJECTORY_H
