// Generated by gencpp from file tauv_msgs/MapFindClosestResponse.msg
// DO NOT EDIT!


#ifndef TAUV_MSGS_MESSAGE_MAPFINDCLOSESTRESPONSE_H
#define TAUV_MSGS_MESSAGE_MAPFINDCLOSESTRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <tauv_msgs/FeatureDetection.h>

namespace tauv_msgs
{
template <class ContainerAllocator>
struct MapFindClosestResponse_
{
  typedef MapFindClosestResponse_<ContainerAllocator> Type;

  MapFindClosestResponse_()
    : detection()
    , success(false)  {
    }
  MapFindClosestResponse_(const ContainerAllocator& _alloc)
    : detection(_alloc)
    , success(false)  {
  (void)_alloc;
    }



   typedef  ::tauv_msgs::FeatureDetection_<ContainerAllocator>  _detection_type;
  _detection_type detection;

   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::tauv_msgs::MapFindClosestResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tauv_msgs::MapFindClosestResponse_<ContainerAllocator> const> ConstPtr;

}; // struct MapFindClosestResponse_

typedef ::tauv_msgs::MapFindClosestResponse_<std::allocator<void> > MapFindClosestResponse;

typedef boost::shared_ptr< ::tauv_msgs::MapFindClosestResponse > MapFindClosestResponsePtr;
typedef boost::shared_ptr< ::tauv_msgs::MapFindClosestResponse const> MapFindClosestResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tauv_msgs::MapFindClosestResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tauv_msgs::MapFindClosestResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tauv_msgs::MapFindClosestResponse_<ContainerAllocator1> & lhs, const ::tauv_msgs::MapFindClosestResponse_<ContainerAllocator2> & rhs)
{
  return lhs.detection == rhs.detection &&
    lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tauv_msgs::MapFindClosestResponse_<ContainerAllocator1> & lhs, const ::tauv_msgs::MapFindClosestResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tauv_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::tauv_msgs::MapFindClosestResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tauv_msgs::MapFindClosestResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tauv_msgs::MapFindClosestResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tauv_msgs::MapFindClosestResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tauv_msgs::MapFindClosestResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tauv_msgs::MapFindClosestResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tauv_msgs::MapFindClosestResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a3723c79370a7a20ad0722931618c5db";
  }

  static const char* value(const ::tauv_msgs::MapFindClosestResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa3723c79370a7a20ULL;
  static const uint64_t static_value2 = 0xad0722931618c5dbULL;
};

template<class ContainerAllocator>
struct DataType< ::tauv_msgs::MapFindClosestResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tauv_msgs/MapFindClosestResponse";
  }

  static const char* value(const ::tauv_msgs::MapFindClosestResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tauv_msgs::MapFindClosestResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tauv_msgs/FeatureDetection detection\n"
"bool success\n"
"\n"
"================================================================================\n"
"MSG: tauv_msgs/FeatureDetection\n"
"Header header\n"
"geometry_msgs/Point position #SE2 msgs will only use x y\n"
"geometry_msgs/Point orientation #SE2 msgs will only use x (theta)\n"
"string tag\n"
"float64 confidence\n"
"bool SE2\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::tauv_msgs::MapFindClosestResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tauv_msgs::MapFindClosestResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.detection);
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MapFindClosestResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tauv_msgs::MapFindClosestResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tauv_msgs::MapFindClosestResponse_<ContainerAllocator>& v)
  {
    s << indent << "detection: ";
    s << std::endl;
    Printer< ::tauv_msgs::FeatureDetection_<ContainerAllocator> >::stream(s, indent + "  ", v.detection);
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TAUV_MSGS_MESSAGE_MAPFINDCLOSESTRESPONSE_H
