// Generated by gencpp from file tauv_msgs/MapFindOneRequest.msg
// DO NOT EDIT!


#ifndef TAUV_MSGS_MESSAGE_MAPFINDONEREQUEST_H
#define TAUV_MSGS_MESSAGE_MAPFINDONEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tauv_msgs
{
template <class ContainerAllocator>
struct MapFindOneRequest_
{
  typedef MapFindOneRequest_<ContainerAllocator> Type;

  MapFindOneRequest_()
    : tag()  {
    }
  MapFindOneRequest_(const ContainerAllocator& _alloc)
    : tag(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _tag_type;
  _tag_type tag;





  typedef boost::shared_ptr< ::tauv_msgs::MapFindOneRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tauv_msgs::MapFindOneRequest_<ContainerAllocator> const> ConstPtr;

}; // struct MapFindOneRequest_

typedef ::tauv_msgs::MapFindOneRequest_<std::allocator<void> > MapFindOneRequest;

typedef boost::shared_ptr< ::tauv_msgs::MapFindOneRequest > MapFindOneRequestPtr;
typedef boost::shared_ptr< ::tauv_msgs::MapFindOneRequest const> MapFindOneRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tauv_msgs::MapFindOneRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tauv_msgs::MapFindOneRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tauv_msgs::MapFindOneRequest_<ContainerAllocator1> & lhs, const ::tauv_msgs::MapFindOneRequest_<ContainerAllocator2> & rhs)
{
  return lhs.tag == rhs.tag;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tauv_msgs::MapFindOneRequest_<ContainerAllocator1> & lhs, const ::tauv_msgs::MapFindOneRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tauv_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::tauv_msgs::MapFindOneRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tauv_msgs::MapFindOneRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tauv_msgs::MapFindOneRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tauv_msgs::MapFindOneRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tauv_msgs::MapFindOneRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tauv_msgs::MapFindOneRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tauv_msgs::MapFindOneRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5f71b33bec3d95b07048be7f138c8710";
  }

  static const char* value(const ::tauv_msgs::MapFindOneRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5f71b33bec3d95b0ULL;
  static const uint64_t static_value2 = 0x7048be7f138c8710ULL;
};

template<class ContainerAllocator>
struct DataType< ::tauv_msgs::MapFindOneRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tauv_msgs/MapFindOneRequest";
  }

  static const char* value(const ::tauv_msgs::MapFindOneRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tauv_msgs::MapFindOneRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string tag\n"
;
  }

  static const char* value(const ::tauv_msgs::MapFindOneRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tauv_msgs::MapFindOneRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.tag);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MapFindOneRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tauv_msgs::MapFindOneRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tauv_msgs::MapFindOneRequest_<ContainerAllocator>& v)
  {
    s << indent << "tag: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.tag);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TAUV_MSGS_MESSAGE_MAPFINDONEREQUEST_H
