// Generated by gencpp from file tauv_msgs/MapFindClosestRequest.msg
// DO NOT EDIT!


#ifndef TAUV_MSGS_MESSAGE_MAPFINDCLOSESTREQUEST_H
#define TAUV_MSGS_MESSAGE_MAPFINDCLOSESTREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace tauv_msgs
{
template <class ContainerAllocator>
struct MapFindClosestRequest_
{
  typedef MapFindClosestRequest_<ContainerAllocator> Type;

  MapFindClosestRequest_()
    : tag()
    , point()  {
    }
  MapFindClosestRequest_(const ContainerAllocator& _alloc)
    : tag(_alloc)
    , point(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _tag_type;
  _tag_type tag;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _point_type;
  _point_type point;





  typedef boost::shared_ptr< ::tauv_msgs::MapFindClosestRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tauv_msgs::MapFindClosestRequest_<ContainerAllocator> const> ConstPtr;

}; // struct MapFindClosestRequest_

typedef ::tauv_msgs::MapFindClosestRequest_<std::allocator<void> > MapFindClosestRequest;

typedef boost::shared_ptr< ::tauv_msgs::MapFindClosestRequest > MapFindClosestRequestPtr;
typedef boost::shared_ptr< ::tauv_msgs::MapFindClosestRequest const> MapFindClosestRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tauv_msgs::MapFindClosestRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tauv_msgs::MapFindClosestRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tauv_msgs::MapFindClosestRequest_<ContainerAllocator1> & lhs, const ::tauv_msgs::MapFindClosestRequest_<ContainerAllocator2> & rhs)
{
  return lhs.tag == rhs.tag &&
    lhs.point == rhs.point;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tauv_msgs::MapFindClosestRequest_<ContainerAllocator1> & lhs, const ::tauv_msgs::MapFindClosestRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tauv_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::tauv_msgs::MapFindClosestRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tauv_msgs::MapFindClosestRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tauv_msgs::MapFindClosestRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tauv_msgs::MapFindClosestRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tauv_msgs::MapFindClosestRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tauv_msgs::MapFindClosestRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tauv_msgs::MapFindClosestRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a224d7e785aebecdaee544b0851d3ba1";
  }

  static const char* value(const ::tauv_msgs::MapFindClosestRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa224d7e785aebecdULL;
  static const uint64_t static_value2 = 0xaee544b0851d3ba1ULL;
};

template<class ContainerAllocator>
struct DataType< ::tauv_msgs::MapFindClosestRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tauv_msgs/MapFindClosestRequest";
  }

  static const char* value(const ::tauv_msgs::MapFindClosestRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tauv_msgs::MapFindClosestRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string tag\n"
"geometry_msgs/Point point\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::tauv_msgs::MapFindClosestRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tauv_msgs::MapFindClosestRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.tag);
      stream.next(m.point);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MapFindClosestRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tauv_msgs::MapFindClosestRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tauv_msgs::MapFindClosestRequest_<ContainerAllocator>& v)
  {
    s << indent << "tag: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.tag);
    s << indent << "point: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.point);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TAUV_MSGS_MESSAGE_MAPFINDCLOSESTREQUEST_H
