// Generated by gencpp from file tauv_msgs/MapFindClosest.msg
// DO NOT EDIT!


#ifndef TAUV_MSGS_MESSAGE_MAPFINDCLOSEST_H
#define TAUV_MSGS_MESSAGE_MAPFINDCLOSEST_H

#include <ros/service_traits.h>


#include <tauv_msgs/MapFindClosestRequest.h>
#include <tauv_msgs/MapFindClosestResponse.h>


namespace tauv_msgs
{

struct MapFindClosest
{

typedef MapFindClosestRequest Request;
typedef MapFindClosestResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MapFindClosest
} // namespace tauv_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tauv_msgs::MapFindClosest > {
  static const char* value()
  {
    return "8fcd7cf3f0341186fb07c7acdf8e1704";
  }

  static const char* value(const ::tauv_msgs::MapFindClosest&) { return value(); }
};

template<>
struct DataType< ::tauv_msgs::MapFindClosest > {
  static const char* value()
  {
    return "tauv_msgs/MapFindClosest";
  }

  static const char* value(const ::tauv_msgs::MapFindClosest&) { return value(); }
};


// service_traits::MD5Sum< ::tauv_msgs::MapFindClosestRequest> should match
// service_traits::MD5Sum< ::tauv_msgs::MapFindClosest >
template<>
struct MD5Sum< ::tauv_msgs::MapFindClosestRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tauv_msgs::MapFindClosest >::value();
  }
  static const char* value(const ::tauv_msgs::MapFindClosestRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tauv_msgs::MapFindClosestRequest> should match
// service_traits::DataType< ::tauv_msgs::MapFindClosest >
template<>
struct DataType< ::tauv_msgs::MapFindClosestRequest>
{
  static const char* value()
  {
    return DataType< ::tauv_msgs::MapFindClosest >::value();
  }
  static const char* value(const ::tauv_msgs::MapFindClosestRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tauv_msgs::MapFindClosestResponse> should match
// service_traits::MD5Sum< ::tauv_msgs::MapFindClosest >
template<>
struct MD5Sum< ::tauv_msgs::MapFindClosestResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tauv_msgs::MapFindClosest >::value();
  }
  static const char* value(const ::tauv_msgs::MapFindClosestResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tauv_msgs::MapFindClosestResponse> should match
// service_traits::DataType< ::tauv_msgs::MapFindClosest >
template<>
struct DataType< ::tauv_msgs::MapFindClosestResponse>
{
  static const char* value()
  {
    return DataType< ::tauv_msgs::MapFindClosest >::value();
  }
  static const char* value(const ::tauv_msgs::MapFindClosestResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TAUV_MSGS_MESSAGE_MAPFINDCLOSEST_H
