// Generated by gencpp from file tauv_msgs/MapFindOne.msg
// DO NOT EDIT!


#ifndef TAUV_MSGS_MESSAGE_MAPFINDONE_H
#define TAUV_MSGS_MESSAGE_MAPFINDONE_H

#include <ros/service_traits.h>


#include <tauv_msgs/MapFindOneRequest.h>
#include <tauv_msgs/MapFindOneResponse.h>


namespace tauv_msgs
{

struct MapFindOne
{

typedef MapFindOneRequest Request;
typedef MapFindOneResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MapFindOne
} // namespace tauv_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tauv_msgs::MapFindOne > {
  static const char* value()
  {
    return "0b9e59f5c45dc6444e155df33a798059";
  }

  static const char* value(const ::tauv_msgs::MapFindOne&) { return value(); }
};

template<>
struct DataType< ::tauv_msgs::MapFindOne > {
  static const char* value()
  {
    return "tauv_msgs/MapFindOne";
  }

  static const char* value(const ::tauv_msgs::MapFindOne&) { return value(); }
};


// service_traits::MD5Sum< ::tauv_msgs::MapFindOneRequest> should match
// service_traits::MD5Sum< ::tauv_msgs::MapFindOne >
template<>
struct MD5Sum< ::tauv_msgs::MapFindOneRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tauv_msgs::MapFindOne >::value();
  }
  static const char* value(const ::tauv_msgs::MapFindOneRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tauv_msgs::MapFindOneRequest> should match
// service_traits::DataType< ::tauv_msgs::MapFindOne >
template<>
struct DataType< ::tauv_msgs::MapFindOneRequest>
{
  static const char* value()
  {
    return DataType< ::tauv_msgs::MapFindOne >::value();
  }
  static const char* value(const ::tauv_msgs::MapFindOneRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tauv_msgs::MapFindOneResponse> should match
// service_traits::MD5Sum< ::tauv_msgs::MapFindOne >
template<>
struct MD5Sum< ::tauv_msgs::MapFindOneResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tauv_msgs::MapFindOne >::value();
  }
  static const char* value(const ::tauv_msgs::MapFindOneResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tauv_msgs::MapFindOneResponse> should match
// service_traits::DataType< ::tauv_msgs::MapFindOne >
template<>
struct DataType< ::tauv_msgs::MapFindOneResponse>
{
  static const char* value()
  {
    return DataType< ::tauv_msgs::MapFindOne >::value();
  }
  static const char* value(const ::tauv_msgs::MapFindOneResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TAUV_MSGS_MESSAGE_MAPFINDONE_H
