// Generated by gencpp from file tauv_msgs/MapFindResponse.msg
// DO NOT EDIT!


#ifndef TAUV_MSGS_MESSAGE_MAPFINDRESPONSE_H
#define TAUV_MSGS_MESSAGE_MAPFINDRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <tauv_msgs/FeatureDetection.h>

namespace tauv_msgs
{
template <class ContainerAllocator>
struct MapFindResponse_
{
  typedef MapFindResponse_<ContainerAllocator> Type;

  MapFindResponse_()
    : detections()
    , success(false)  {
    }
  MapFindResponse_(const ContainerAllocator& _alloc)
    : detections(_alloc)
    , success(false)  {
  (void)_alloc;
    }



   typedef std::vector< ::tauv_msgs::FeatureDetection_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::tauv_msgs::FeatureDetection_<ContainerAllocator> >> _detections_type;
  _detections_type detections;

   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::tauv_msgs::MapFindResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tauv_msgs::MapFindResponse_<ContainerAllocator> const> ConstPtr;

}; // struct MapFindResponse_

typedef ::tauv_msgs::MapFindResponse_<std::allocator<void> > MapFindResponse;

typedef boost::shared_ptr< ::tauv_msgs::MapFindResponse > MapFindResponsePtr;
typedef boost::shared_ptr< ::tauv_msgs::MapFindResponse const> MapFindResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tauv_msgs::MapFindResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tauv_msgs::MapFindResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tauv_msgs::MapFindResponse_<ContainerAllocator1> & lhs, const ::tauv_msgs::MapFindResponse_<ContainerAllocator2> & rhs)
{
  return lhs.detections == rhs.detections &&
    lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tauv_msgs::MapFindResponse_<ContainerAllocator1> & lhs, const ::tauv_msgs::MapFindResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tauv_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::tauv_msgs::MapFindResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tauv_msgs::MapFindResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tauv_msgs::MapFindResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tauv_msgs::MapFindResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tauv_msgs::MapFindResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tauv_msgs::MapFindResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tauv_msgs::MapFindResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3550f71bd1354de3af109636d90de6c0";
  }

  static const char* value(const ::tauv_msgs::MapFindResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3550f71bd1354de3ULL;
  static const uint64_t static_value2 = 0xaf109636d90de6c0ULL;
};

template<class ContainerAllocator>
struct DataType< ::tauv_msgs::MapFindResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tauv_msgs/MapFindResponse";
  }

  static const char* value(const ::tauv_msgs::MapFindResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tauv_msgs::MapFindResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tauv_msgs/FeatureDetection[] detections\n"
"bool success\n"
"\n"
"================================================================================\n"
"MSG: tauv_msgs/FeatureDetection\n"
"Header header\n"
"geometry_msgs/Point position #SE2 msgs will only use x y\n"
"geometry_msgs/Point orientation #SE2 msgs will only use x (theta)\n"
"string tag\n"
"float64 confidence\n"
"bool SE2\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::tauv_msgs::MapFindResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tauv_msgs::MapFindResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.detections);
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MapFindResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tauv_msgs::MapFindResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tauv_msgs::MapFindResponse_<ContainerAllocator>& v)
  {
    s << indent << "detections[]" << std::endl;
    for (size_t i = 0; i < v.detections.size(); ++i)
    {
      s << indent << "  detections[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::tauv_msgs::FeatureDetection_<ContainerAllocator> >::stream(s, indent + "    ", v.detections[i]);
    }
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TAUV_MSGS_MESSAGE_MAPFINDRESPONSE_H
