// Generated by gencpp from file tauv_msgs/Message.msg
// DO NOT EDIT!


#ifndef TAUV_MSGS_MESSAGE_MESSAGE_H
#define TAUV_MSGS_MESSAGE_MESSAGE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tauv_msgs
{
template <class ContainerAllocator>
struct Message_
{
  typedef Message_<ContainerAllocator> Type;

  Message_()
    : stamp()
    , color_code_256(0)
    , severity(0)
    , message()  {
    }
  Message_(const ContainerAllocator& _alloc)
    : stamp()
    , color_code_256(0)
    , severity(0)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef ros::Time _stamp_type;
  _stamp_type stamp;

   typedef uint8_t _color_code_256_type;
  _color_code_256_type color_code_256;

   typedef int8_t _severity_type;
  _severity_type severity;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(ERROR)
  #undef ERROR
#endif
#if defined(_WIN32) && defined(WARNING)
  #undef WARNING
#endif
#if defined(_WIN32) && defined(INFO)
  #undef INFO
#endif
#if defined(_WIN32) && defined(DEBUG)
  #undef DEBUG
#endif

  enum {
    ERROR = 0,
    WARNING = 1,
    INFO = 2,
    DEBUG = 3,
  };


  typedef boost::shared_ptr< ::tauv_msgs::Message_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tauv_msgs::Message_<ContainerAllocator> const> ConstPtr;

}; // struct Message_

typedef ::tauv_msgs::Message_<std::allocator<void> > Message;

typedef boost::shared_ptr< ::tauv_msgs::Message > MessagePtr;
typedef boost::shared_ptr< ::tauv_msgs::Message const> MessageConstPtr;

// constants requiring out of line definition

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tauv_msgs::Message_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tauv_msgs::Message_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tauv_msgs::Message_<ContainerAllocator1> & lhs, const ::tauv_msgs::Message_<ContainerAllocator2> & rhs)
{
  return lhs.stamp == rhs.stamp &&
    lhs.color_code_256 == rhs.color_code_256 &&
    lhs.severity == rhs.severity &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tauv_msgs::Message_<ContainerAllocator1> & lhs, const ::tauv_msgs::Message_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tauv_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::tauv_msgs::Message_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tauv_msgs::Message_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tauv_msgs::Message_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tauv_msgs::Message_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tauv_msgs::Message_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tauv_msgs::Message_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tauv_msgs::Message_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9553ea1e0a9cfe897226edaceb34218e";
  }

  static const char* value(const ::tauv_msgs::Message_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9553ea1e0a9cfe89ULL;
  static const uint64_t static_value2 = 0x7226edaceb34218eULL;
};

template<class ContainerAllocator>
struct DataType< ::tauv_msgs::Message_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tauv_msgs/Message";
  }

  static const char* value(const ::tauv_msgs::Message_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tauv_msgs::Message_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 ERROR=0\n"
"int8 WARNING=1\n"
"int8 INFO=2\n"
"int8 DEBUG=3\n"
"\n"
"time stamp         # time stamp of the message\n"
"uint8 color_code_256   # color code of the message\n"
"int8 severity       # severity level\n"
"string message      # message\n"
;
  }

  static const char* value(const ::tauv_msgs::Message_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tauv_msgs::Message_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.stamp);
      stream.next(m.color_code_256);
      stream.next(m.severity);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Message_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tauv_msgs::Message_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tauv_msgs::Message_<ContainerAllocator>& v)
  {
    s << indent << "stamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.stamp);
    s << indent << "color_code_256: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.color_code_256);
    s << indent << "severity: ";
    Printer<int8_t>::stream(s, indent + "  ", v.severity);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TAUV_MSGS_MESSAGE_MESSAGE_H
