// Generated by gencpp from file tauv_msgs/NavigationState.msg
// DO NOT EDIT!


#ifndef TAUV_MSGS_MESSAGE_NAVIGATIONSTATE_H
#define TAUV_MSGS_MESSAGE_NAVIGATIONSTATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>

namespace tauv_msgs
{
template <class ContainerAllocator>
struct NavigationState_
{
  typedef NavigationState_<ContainerAllocator> Type;

  NavigationState_()
    : header()
    , position()
    , linear_velocity()
    , linear_acceleration()
    , orientation()
    , euler_velocity()
    , euler_acceleration()  {
    }
  NavigationState_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , position(_alloc)
    , linear_velocity(_alloc)
    , linear_acceleration(_alloc)
    , orientation(_alloc)
    , euler_velocity(_alloc)
    , euler_acceleration(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _position_type;
  _position_type position;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _linear_velocity_type;
  _linear_velocity_type linear_velocity;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _linear_acceleration_type;
  _linear_acceleration_type linear_acceleration;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _orientation_type;
  _orientation_type orientation;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _euler_velocity_type;
  _euler_velocity_type euler_velocity;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _euler_acceleration_type;
  _euler_acceleration_type euler_acceleration;





  typedef boost::shared_ptr< ::tauv_msgs::NavigationState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tauv_msgs::NavigationState_<ContainerAllocator> const> ConstPtr;

}; // struct NavigationState_

typedef ::tauv_msgs::NavigationState_<std::allocator<void> > NavigationState;

typedef boost::shared_ptr< ::tauv_msgs::NavigationState > NavigationStatePtr;
typedef boost::shared_ptr< ::tauv_msgs::NavigationState const> NavigationStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tauv_msgs::NavigationState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tauv_msgs::NavigationState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tauv_msgs::NavigationState_<ContainerAllocator1> & lhs, const ::tauv_msgs::NavigationState_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.position == rhs.position &&
    lhs.linear_velocity == rhs.linear_velocity &&
    lhs.linear_acceleration == rhs.linear_acceleration &&
    lhs.orientation == rhs.orientation &&
    lhs.euler_velocity == rhs.euler_velocity &&
    lhs.euler_acceleration == rhs.euler_acceleration;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tauv_msgs::NavigationState_<ContainerAllocator1> & lhs, const ::tauv_msgs::NavigationState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tauv_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::tauv_msgs::NavigationState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tauv_msgs::NavigationState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tauv_msgs::NavigationState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tauv_msgs::NavigationState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tauv_msgs::NavigationState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tauv_msgs::NavigationState_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tauv_msgs::NavigationState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3507e091ce71f01fa9dea0061304746a";
  }

  static const char* value(const ::tauv_msgs::NavigationState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3507e091ce71f01fULL;
  static const uint64_t static_value2 = 0xa9dea0061304746aULL;
};

template<class ContainerAllocator>
struct DataType< ::tauv_msgs::NavigationState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tauv_msgs/NavigationState";
  }

  static const char* value(const ::tauv_msgs::NavigationState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tauv_msgs::NavigationState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"geometry_msgs/Vector3 position\n"
"geometry_msgs/Vector3 linear_velocity      # body\n"
"geometry_msgs/Vector3 linear_acceleration  # body\n"
"geometry_msgs/Vector3 orientation          # (r, p, y)\n"
"geometry_msgs/Vector3 euler_velocity       # (dr/dt, dp/dt, dy/dt)\n"
"geometry_msgs/Vector3 euler_acceleration   # (d2r/dt2, d2p/dt2, d2y/dt2)\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::tauv_msgs::NavigationState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tauv_msgs::NavigationState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.position);
      stream.next(m.linear_velocity);
      stream.next(m.linear_acceleration);
      stream.next(m.orientation);
      stream.next(m.euler_velocity);
      stream.next(m.euler_acceleration);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NavigationState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tauv_msgs::NavigationState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tauv_msgs::NavigationState_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "position: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.position);
    s << indent << "linear_velocity: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.linear_velocity);
    s << indent << "linear_acceleration: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.linear_acceleration);
    s << indent << "orientation: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.orientation);
    s << indent << "euler_velocity: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.euler_velocity);
    s << indent << "euler_acceleration: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.euler_acceleration);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TAUV_MSGS_MESSAGE_NAVIGATIONSTATE_H
