// Generated by gencpp from file tauv_msgs/PIDDebug.msg
// DO NOT EDIT!


#ifndef TAUV_MSGS_MESSAGE_PIDDEBUG_H
#define TAUV_MSGS_MESSAGE_PIDDEBUG_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <tauv_msgs/PIDTuning.h>

namespace tauv_msgs
{
template <class ContainerAllocator>
struct PIDDebug_
{
  typedef PIDDebug_<ContainerAllocator> Type;

  PIDDebug_()
    : tuning()
    , value(0.0)
    , setpoint(0.0)
    , error(0.0)
    , proportional(0.0)
    , integral(0.0)
    , derivative(0.0)
    , effort(0.0)  {
    }
  PIDDebug_(const ContainerAllocator& _alloc)
    : tuning(_alloc)
    , value(0.0)
    , setpoint(0.0)
    , error(0.0)
    , proportional(0.0)
    , integral(0.0)
    , derivative(0.0)
    , effort(0.0)  {
  (void)_alloc;
    }



   typedef  ::tauv_msgs::PIDTuning_<ContainerAllocator>  _tuning_type;
  _tuning_type tuning;

   typedef double _value_type;
  _value_type value;

   typedef double _setpoint_type;
  _setpoint_type setpoint;

   typedef double _error_type;
  _error_type error;

   typedef double _proportional_type;
  _proportional_type proportional;

   typedef double _integral_type;
  _integral_type integral;

   typedef double _derivative_type;
  _derivative_type derivative;

   typedef double _effort_type;
  _effort_type effort;





  typedef boost::shared_ptr< ::tauv_msgs::PIDDebug_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tauv_msgs::PIDDebug_<ContainerAllocator> const> ConstPtr;

}; // struct PIDDebug_

typedef ::tauv_msgs::PIDDebug_<std::allocator<void> > PIDDebug;

typedef boost::shared_ptr< ::tauv_msgs::PIDDebug > PIDDebugPtr;
typedef boost::shared_ptr< ::tauv_msgs::PIDDebug const> PIDDebugConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tauv_msgs::PIDDebug_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tauv_msgs::PIDDebug_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tauv_msgs::PIDDebug_<ContainerAllocator1> & lhs, const ::tauv_msgs::PIDDebug_<ContainerAllocator2> & rhs)
{
  return lhs.tuning == rhs.tuning &&
    lhs.value == rhs.value &&
    lhs.setpoint == rhs.setpoint &&
    lhs.error == rhs.error &&
    lhs.proportional == rhs.proportional &&
    lhs.integral == rhs.integral &&
    lhs.derivative == rhs.derivative &&
    lhs.effort == rhs.effort;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tauv_msgs::PIDDebug_<ContainerAllocator1> & lhs, const ::tauv_msgs::PIDDebug_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tauv_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::tauv_msgs::PIDDebug_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tauv_msgs::PIDDebug_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tauv_msgs::PIDDebug_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tauv_msgs::PIDDebug_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tauv_msgs::PIDDebug_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tauv_msgs::PIDDebug_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tauv_msgs::PIDDebug_<ContainerAllocator> >
{
  static const char* value()
  {
    return "16ed0a79b3cb076d76fdb91c1c560d6a";
  }

  static const char* value(const ::tauv_msgs::PIDDebug_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x16ed0a79b3cb076dULL;
  static const uint64_t static_value2 = 0x76fdb91c1c560d6aULL;
};

template<class ContainerAllocator>
struct DataType< ::tauv_msgs::PIDDebug_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tauv_msgs/PIDDebug";
  }

  static const char* value(const ::tauv_msgs::PIDDebug_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tauv_msgs::PIDDebug_<ContainerAllocator> >
{
  static const char* value()
  {
    return "PIDTuning tuning\n"
"\n"
"float64 value\n"
"float64 setpoint\n"
"float64 error\n"
"float64 proportional\n"
"float64 integral\n"
"float64 derivative\n"
"float64 effort\n"
"================================================================================\n"
"MSG: tauv_msgs/PIDTuning\n"
"string axis\n"
"float64 kp\n"
"float64 ki\n"
"float64 kd\n"
"float64 tau\n"
"float64[2] limits\n"
;
  }

  static const char* value(const ::tauv_msgs::PIDDebug_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tauv_msgs::PIDDebug_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.tuning);
      stream.next(m.value);
      stream.next(m.setpoint);
      stream.next(m.error);
      stream.next(m.proportional);
      stream.next(m.integral);
      stream.next(m.derivative);
      stream.next(m.effort);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PIDDebug_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tauv_msgs::PIDDebug_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tauv_msgs::PIDDebug_<ContainerAllocator>& v)
  {
    s << indent << "tuning: ";
    s << std::endl;
    Printer< ::tauv_msgs::PIDTuning_<ContainerAllocator> >::stream(s, indent + "  ", v.tuning);
    s << indent << "value: ";
    Printer<double>::stream(s, indent + "  ", v.value);
    s << indent << "setpoint: ";
    Printer<double>::stream(s, indent + "  ", v.setpoint);
    s << indent << "error: ";
    Printer<double>::stream(s, indent + "  ", v.error);
    s << indent << "proportional: ";
    Printer<double>::stream(s, indent + "  ", v.proportional);
    s << indent << "integral: ";
    Printer<double>::stream(s, indent + "  ", v.integral);
    s << indent << "derivative: ";
    Printer<double>::stream(s, indent + "  ", v.derivative);
    s << indent << "effort: ";
    Printer<double>::stream(s, indent + "  ", v.effort);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TAUV_MSGS_MESSAGE_PIDDEBUG_H
