// Generated by gencpp from file tauv_msgs/PIDPlannerDebug.msg
// DO NOT EDIT!


#ifndef TAUV_MSGS_MESSAGE_PIDPLANNERDEBUG_H
#define TAUV_MSGS_MESSAGE_PIDPLANNERDEBUG_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <tauv_msgs/PIDDebug.h>
#include <tauv_msgs/PIDDebug.h>
#include <tauv_msgs/PIDDebug.h>
#include <tauv_msgs/PIDDebug.h>
#include <tauv_msgs/PIDDebug.h>
#include <tauv_msgs/PIDDebug.h>

namespace tauv_msgs
{
template <class ContainerAllocator>
struct PIDPlannerDebug_
{
  typedef PIDPlannerDebug_<ContainerAllocator> Type;

  PIDPlannerDebug_()
    : stamp()
    , x()
    , y()
    , z()
    , roll()
    , pitch()
    , yaw()  {
    }
  PIDPlannerDebug_(const ContainerAllocator& _alloc)
    : stamp()
    , x(_alloc)
    , y(_alloc)
    , z(_alloc)
    , roll(_alloc)
    , pitch(_alloc)
    , yaw(_alloc)  {
  (void)_alloc;
    }



   typedef ros::Time _stamp_type;
  _stamp_type stamp;

   typedef  ::tauv_msgs::PIDDebug_<ContainerAllocator>  _x_type;
  _x_type x;

   typedef  ::tauv_msgs::PIDDebug_<ContainerAllocator>  _y_type;
  _y_type y;

   typedef  ::tauv_msgs::PIDDebug_<ContainerAllocator>  _z_type;
  _z_type z;

   typedef  ::tauv_msgs::PIDDebug_<ContainerAllocator>  _roll_type;
  _roll_type roll;

   typedef  ::tauv_msgs::PIDDebug_<ContainerAllocator>  _pitch_type;
  _pitch_type pitch;

   typedef  ::tauv_msgs::PIDDebug_<ContainerAllocator>  _yaw_type;
  _yaw_type yaw;





  typedef boost::shared_ptr< ::tauv_msgs::PIDPlannerDebug_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tauv_msgs::PIDPlannerDebug_<ContainerAllocator> const> ConstPtr;

}; // struct PIDPlannerDebug_

typedef ::tauv_msgs::PIDPlannerDebug_<std::allocator<void> > PIDPlannerDebug;

typedef boost::shared_ptr< ::tauv_msgs::PIDPlannerDebug > PIDPlannerDebugPtr;
typedef boost::shared_ptr< ::tauv_msgs::PIDPlannerDebug const> PIDPlannerDebugConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tauv_msgs::PIDPlannerDebug_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tauv_msgs::PIDPlannerDebug_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tauv_msgs::PIDPlannerDebug_<ContainerAllocator1> & lhs, const ::tauv_msgs::PIDPlannerDebug_<ContainerAllocator2> & rhs)
{
  return lhs.stamp == rhs.stamp &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z &&
    lhs.roll == rhs.roll &&
    lhs.pitch == rhs.pitch &&
    lhs.yaw == rhs.yaw;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tauv_msgs::PIDPlannerDebug_<ContainerAllocator1> & lhs, const ::tauv_msgs::PIDPlannerDebug_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tauv_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::tauv_msgs::PIDPlannerDebug_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tauv_msgs::PIDPlannerDebug_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tauv_msgs::PIDPlannerDebug_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tauv_msgs::PIDPlannerDebug_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tauv_msgs::PIDPlannerDebug_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tauv_msgs::PIDPlannerDebug_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tauv_msgs::PIDPlannerDebug_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0f555c58b06b2c2d39d97456d9e34ef3";
  }

  static const char* value(const ::tauv_msgs::PIDPlannerDebug_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0f555c58b06b2c2dULL;
  static const uint64_t static_value2 = 0x39d97456d9e34ef3ULL;
};

template<class ContainerAllocator>
struct DataType< ::tauv_msgs::PIDPlannerDebug_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tauv_msgs/PIDPlannerDebug";
  }

  static const char* value(const ::tauv_msgs::PIDPlannerDebug_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tauv_msgs::PIDPlannerDebug_<ContainerAllocator> >
{
  static const char* value()
  {
    return "time stamp\n"
"\n"
"PIDDebug x\n"
"PIDDebug y\n"
"PIDDebug z\n"
"PIDDebug roll\n"
"PIDDebug pitch\n"
"PIDDebug yaw\n"
"================================================================================\n"
"MSG: tauv_msgs/PIDDebug\n"
"PIDTuning tuning\n"
"\n"
"float64 value\n"
"float64 setpoint\n"
"float64 error\n"
"float64 proportional\n"
"float64 integral\n"
"float64 derivative\n"
"float64 effort\n"
"================================================================================\n"
"MSG: tauv_msgs/PIDTuning\n"
"string axis\n"
"float64 kp\n"
"float64 ki\n"
"float64 kd\n"
"float64 tau\n"
"float64[2] limits\n"
;
  }

  static const char* value(const ::tauv_msgs::PIDPlannerDebug_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tauv_msgs::PIDPlannerDebug_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.stamp);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.roll);
      stream.next(m.pitch);
      stream.next(m.yaw);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PIDPlannerDebug_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tauv_msgs::PIDPlannerDebug_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tauv_msgs::PIDPlannerDebug_<ContainerAllocator>& v)
  {
    s << indent << "stamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.stamp);
    s << indent << "x: ";
    s << std::endl;
    Printer< ::tauv_msgs::PIDDebug_<ContainerAllocator> >::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    s << std::endl;
    Printer< ::tauv_msgs::PIDDebug_<ContainerAllocator> >::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    s << std::endl;
    Printer< ::tauv_msgs::PIDDebug_<ContainerAllocator> >::stream(s, indent + "  ", v.z);
    s << indent << "roll: ";
    s << std::endl;
    Printer< ::tauv_msgs::PIDDebug_<ContainerAllocator> >::stream(s, indent + "  ", v.roll);
    s << indent << "pitch: ";
    s << std::endl;
    Printer< ::tauv_msgs::PIDDebug_<ContainerAllocator> >::stream(s, indent + "  ", v.pitch);
    s << indent << "yaw: ";
    s << std::endl;
    Printer< ::tauv_msgs::PIDDebug_<ContainerAllocator> >::stream(s, indent + "  ", v.yaw);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TAUV_MSGS_MESSAGE_PIDPLANNERDEBUG_H
