// Generated by gencpp from file tauv_msgs/PIDTuning.msg
// DO NOT EDIT!


#ifndef TAUV_MSGS_MESSAGE_PIDTUNING_H
#define TAUV_MSGS_MESSAGE_PIDTUNING_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tauv_msgs
{
template <class ContainerAllocator>
struct PIDTuning_
{
  typedef PIDTuning_<ContainerAllocator> Type;

  PIDTuning_()
    : axis()
    , kp(0.0)
    , ki(0.0)
    , kd(0.0)
    , tau(0.0)
    , limits()  {
      limits.assign(0.0);
  }
  PIDTuning_(const ContainerAllocator& _alloc)
    : axis(_alloc)
    , kp(0.0)
    , ki(0.0)
    , kd(0.0)
    , tau(0.0)
    , limits()  {
  (void)_alloc;
      limits.assign(0.0);
  }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _axis_type;
  _axis_type axis;

   typedef double _kp_type;
  _kp_type kp;

   typedef double _ki_type;
  _ki_type ki;

   typedef double _kd_type;
  _kd_type kd;

   typedef double _tau_type;
  _tau_type tau;

   typedef boost::array<double, 2>  _limits_type;
  _limits_type limits;





  typedef boost::shared_ptr< ::tauv_msgs::PIDTuning_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tauv_msgs::PIDTuning_<ContainerAllocator> const> ConstPtr;

}; // struct PIDTuning_

typedef ::tauv_msgs::PIDTuning_<std::allocator<void> > PIDTuning;

typedef boost::shared_ptr< ::tauv_msgs::PIDTuning > PIDTuningPtr;
typedef boost::shared_ptr< ::tauv_msgs::PIDTuning const> PIDTuningConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tauv_msgs::PIDTuning_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tauv_msgs::PIDTuning_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tauv_msgs::PIDTuning_<ContainerAllocator1> & lhs, const ::tauv_msgs::PIDTuning_<ContainerAllocator2> & rhs)
{
  return lhs.axis == rhs.axis &&
    lhs.kp == rhs.kp &&
    lhs.ki == rhs.ki &&
    lhs.kd == rhs.kd &&
    lhs.tau == rhs.tau &&
    lhs.limits == rhs.limits;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tauv_msgs::PIDTuning_<ContainerAllocator1> & lhs, const ::tauv_msgs::PIDTuning_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tauv_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::tauv_msgs::PIDTuning_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tauv_msgs::PIDTuning_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tauv_msgs::PIDTuning_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tauv_msgs::PIDTuning_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tauv_msgs::PIDTuning_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tauv_msgs::PIDTuning_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tauv_msgs::PIDTuning_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0c319ae505ebfe0fb1604e4f13fce3d5";
  }

  static const char* value(const ::tauv_msgs::PIDTuning_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0c319ae505ebfe0fULL;
  static const uint64_t static_value2 = 0xb1604e4f13fce3d5ULL;
};

template<class ContainerAllocator>
struct DataType< ::tauv_msgs::PIDTuning_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tauv_msgs/PIDTuning";
  }

  static const char* value(const ::tauv_msgs::PIDTuning_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tauv_msgs::PIDTuning_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string axis\n"
"float64 kp\n"
"float64 ki\n"
"float64 kd\n"
"float64 tau\n"
"float64[2] limits\n"
;
  }

  static const char* value(const ::tauv_msgs::PIDTuning_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tauv_msgs::PIDTuning_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.axis);
      stream.next(m.kp);
      stream.next(m.ki);
      stream.next(m.kd);
      stream.next(m.tau);
      stream.next(m.limits);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PIDTuning_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tauv_msgs::PIDTuning_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tauv_msgs::PIDTuning_<ContainerAllocator>& v)
  {
    s << indent << "axis: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.axis);
    s << indent << "kp: ";
    Printer<double>::stream(s, indent + "  ", v.kp);
    s << indent << "ki: ";
    Printer<double>::stream(s, indent + "  ", v.ki);
    s << indent << "kd: ";
    Printer<double>::stream(s, indent + "  ", v.kd);
    s << indent << "tau: ";
    Printer<double>::stream(s, indent + "  ", v.tau);
    s << indent << "limits[]" << std::endl;
    for (size_t i = 0; i < v.limits.size(); ++i)
    {
      s << indent << "  limits[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.limits[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // TAUV_MSGS_MESSAGE_PIDTUNING_H
