// Generated by gencpp from file tauv_msgs/PingDetection.msg
// DO NOT EDIT!


#ifndef TAUV_MSGS_MESSAGE_PINGDETECTION_H
#define TAUV_MSGS_MESSAGE_PINGDETECTION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Vector3.h>

namespace tauv_msgs
{
template <class ContainerAllocator>
struct PingDetection_
{
  typedef PingDetection_<ContainerAllocator> Type;

  PingDetection_()
    : header()
    , frequency(0.0)
    , direction()  {
    }
  PingDetection_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , frequency(0.0)
    , direction(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _frequency_type;
  _frequency_type frequency;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _direction_type;
  _direction_type direction;





  typedef boost::shared_ptr< ::tauv_msgs::PingDetection_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tauv_msgs::PingDetection_<ContainerAllocator> const> ConstPtr;

}; // struct PingDetection_

typedef ::tauv_msgs::PingDetection_<std::allocator<void> > PingDetection;

typedef boost::shared_ptr< ::tauv_msgs::PingDetection > PingDetectionPtr;
typedef boost::shared_ptr< ::tauv_msgs::PingDetection const> PingDetectionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tauv_msgs::PingDetection_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tauv_msgs::PingDetection_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tauv_msgs::PingDetection_<ContainerAllocator1> & lhs, const ::tauv_msgs::PingDetection_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.frequency == rhs.frequency &&
    lhs.direction == rhs.direction;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tauv_msgs::PingDetection_<ContainerAllocator1> & lhs, const ::tauv_msgs::PingDetection_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tauv_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::tauv_msgs::PingDetection_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tauv_msgs::PingDetection_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tauv_msgs::PingDetection_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tauv_msgs::PingDetection_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tauv_msgs::PingDetection_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tauv_msgs::PingDetection_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tauv_msgs::PingDetection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a9abd7bac39db1726e1408962ec95f05";
  }

  static const char* value(const ::tauv_msgs::PingDetection_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa9abd7bac39db172ULL;
  static const uint64_t static_value2 = 0x6e1408962ec95f05ULL;
};

template<class ContainerAllocator>
struct DataType< ::tauv_msgs::PingDetection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tauv_msgs/PingDetection";
  }

  static const char* value(const ::tauv_msgs::PingDetection_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tauv_msgs::PingDetection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"float64 frequency\n"
"geometry_msgs/Vector3 direction\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::tauv_msgs::PingDetection_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tauv_msgs::PingDetection_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.frequency);
      stream.next(m.direction);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PingDetection_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tauv_msgs::PingDetection_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tauv_msgs::PingDetection_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "frequency: ";
    Printer<double>::stream(s, indent + "  ", v.frequency);
    s << indent << "direction: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.direction);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TAUV_MSGS_MESSAGE_PINGDETECTION_H
