// Generated by gencpp from file tauv_msgs/RunMission.msg
// DO NOT EDIT!


#ifndef TAUV_MSGS_MESSAGE_RUNMISSION_H
#define TAUV_MSGS_MESSAGE_RUNMISSION_H

#include <ros/service_traits.h>


#include <tauv_msgs/RunMissionRequest.h>
#include <tauv_msgs/RunMissionResponse.h>


namespace tauv_msgs
{

struct RunMission
{

typedef RunMissionRequest Request;
typedef RunMissionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RunMission
} // namespace tauv_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tauv_msgs::RunMission > {
  static const char* value()
  {
    return "9f981363eccc116598d821fe063b0990";
  }

  static const char* value(const ::tauv_msgs::RunMission&) { return value(); }
};

template<>
struct DataType< ::tauv_msgs::RunMission > {
  static const char* value()
  {
    return "tauv_msgs/RunMission";
  }

  static const char* value(const ::tauv_msgs::RunMission&) { return value(); }
};


// service_traits::MD5Sum< ::tauv_msgs::RunMissionRequest> should match
// service_traits::MD5Sum< ::tauv_msgs::RunMission >
template<>
struct MD5Sum< ::tauv_msgs::RunMissionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tauv_msgs::RunMission >::value();
  }
  static const char* value(const ::tauv_msgs::RunMissionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tauv_msgs::RunMissionRequest> should match
// service_traits::DataType< ::tauv_msgs::RunMission >
template<>
struct DataType< ::tauv_msgs::RunMissionRequest>
{
  static const char* value()
  {
    return DataType< ::tauv_msgs::RunMission >::value();
  }
  static const char* value(const ::tauv_msgs::RunMissionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tauv_msgs::RunMissionResponse> should match
// service_traits::MD5Sum< ::tauv_msgs::RunMission >
template<>
struct MD5Sum< ::tauv_msgs::RunMissionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tauv_msgs::RunMission >::value();
  }
  static const char* value(const ::tauv_msgs::RunMissionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tauv_msgs::RunMissionResponse> should match
// service_traits::DataType< ::tauv_msgs::RunMission >
template<>
struct DataType< ::tauv_msgs::RunMissionResponse>
{
  static const char* value()
  {
    return DataType< ::tauv_msgs::RunMission >::value();
  }
  static const char* value(const ::tauv_msgs::RunMissionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TAUV_MSGS_MESSAGE_RUNMISSION_H
