// Generated by gencpp from file tauv_msgs/SetPose.msg
// DO NOT EDIT!


#ifndef TAUV_MSGS_MESSAGE_SETPOSE_H
#define TAUV_MSGS_MESSAGE_SETPOSE_H

#include <ros/service_traits.h>


#include <tauv_msgs/SetPoseRequest.h>
#include <tauv_msgs/SetPoseResponse.h>


namespace tauv_msgs
{

struct SetPose
{

typedef SetPoseRequest Request;
typedef SetPoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetPose
} // namespace tauv_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tauv_msgs::SetPose > {
  static const char* value()
  {
    return "c0694c76e8e4d6ff81999164dc53cd23";
  }

  static const char* value(const ::tauv_msgs::SetPose&) { return value(); }
};

template<>
struct DataType< ::tauv_msgs::SetPose > {
  static const char* value()
  {
    return "tauv_msgs/SetPose";
  }

  static const char* value(const ::tauv_msgs::SetPose&) { return value(); }
};


// service_traits::MD5Sum< ::tauv_msgs::SetPoseRequest> should match
// service_traits::MD5Sum< ::tauv_msgs::SetPose >
template<>
struct MD5Sum< ::tauv_msgs::SetPoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tauv_msgs::SetPose >::value();
  }
  static const char* value(const ::tauv_msgs::SetPoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tauv_msgs::SetPoseRequest> should match
// service_traits::DataType< ::tauv_msgs::SetPose >
template<>
struct DataType< ::tauv_msgs::SetPoseRequest>
{
  static const char* value()
  {
    return DataType< ::tauv_msgs::SetPose >::value();
  }
  static const char* value(const ::tauv_msgs::SetPoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tauv_msgs::SetPoseResponse> should match
// service_traits::MD5Sum< ::tauv_msgs::SetPose >
template<>
struct MD5Sum< ::tauv_msgs::SetPoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tauv_msgs::SetPose >::value();
  }
  static const char* value(const ::tauv_msgs::SetPoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tauv_msgs::SetPoseResponse> should match
// service_traits::DataType< ::tauv_msgs::SetPose >
template<>
struct DataType< ::tauv_msgs::SetPoseResponse>
{
  static const char* value()
  {
    return DataType< ::tauv_msgs::SetPose >::value();
  }
  static const char* value(const ::tauv_msgs::SetPoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TAUV_MSGS_MESSAGE_SETPOSE_H
