// Generated by gencpp from file tauv_msgs/SetTargetPose.msg
// DO NOT EDIT!


#ifndef TAUV_MSGS_MESSAGE_SETTARGETPOSE_H
#define TAUV_MSGS_MESSAGE_SETTARGETPOSE_H

#include <ros/service_traits.h>


#include <tauv_msgs/SetTargetPoseRequest.h>
#include <tauv_msgs/SetTargetPoseResponse.h>


namespace tauv_msgs
{

struct SetTargetPose
{

typedef SetTargetPoseRequest Request;
typedef SetTargetPoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetTargetPose
} // namespace tauv_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tauv_msgs::SetTargetPose > {
  static const char* value()
  {
    return "b66f4c8c2fa81b98544cf0f3e10950ee";
  }

  static const char* value(const ::tauv_msgs::SetTargetPose&) { return value(); }
};

template<>
struct DataType< ::tauv_msgs::SetTargetPose > {
  static const char* value()
  {
    return "tauv_msgs/SetTargetPose";
  }

  static const char* value(const ::tauv_msgs::SetTargetPose&) { return value(); }
};


// service_traits::MD5Sum< ::tauv_msgs::SetTargetPoseRequest> should match
// service_traits::MD5Sum< ::tauv_msgs::SetTargetPose >
template<>
struct MD5Sum< ::tauv_msgs::SetTargetPoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tauv_msgs::SetTargetPose >::value();
  }
  static const char* value(const ::tauv_msgs::SetTargetPoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tauv_msgs::SetTargetPoseRequest> should match
// service_traits::DataType< ::tauv_msgs::SetTargetPose >
template<>
struct DataType< ::tauv_msgs::SetTargetPoseRequest>
{
  static const char* value()
  {
    return DataType< ::tauv_msgs::SetTargetPose >::value();
  }
  static const char* value(const ::tauv_msgs::SetTargetPoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tauv_msgs::SetTargetPoseResponse> should match
// service_traits::MD5Sum< ::tauv_msgs::SetTargetPose >
template<>
struct MD5Sum< ::tauv_msgs::SetTargetPoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tauv_msgs::SetTargetPose >::value();
  }
  static const char* value(const ::tauv_msgs::SetTargetPoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tauv_msgs::SetTargetPoseResponse> should match
// service_traits::DataType< ::tauv_msgs::SetTargetPose >
template<>
struct DataType< ::tauv_msgs::SetTargetPoseResponse>
{
  static const char* value()
  {
    return DataType< ::tauv_msgs::SetTargetPose >::value();
  }
  static const char* value(const ::tauv_msgs::SetTargetPoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TAUV_MSGS_MESSAGE_SETTARGETPOSE_H
