// Generated by gencpp from file tauv_msgs/SyncAlarmsResponse.msg
// DO NOT EDIT!


#ifndef TAUV_MSGS_MESSAGE_SYNCALARMSRESPONSE_H
#define TAUV_MSGS_MESSAGE_SYNCALARMSRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tauv_msgs
{
template <class ContainerAllocator>
struct SyncAlarmsResponse_
{
  typedef SyncAlarmsResponse_<ContainerAllocator> Type;

  SyncAlarmsResponse_()
    : stamp()
    , active_alarms()
    , success(false)  {
    }
  SyncAlarmsResponse_(const ContainerAllocator& _alloc)
    : stamp()
    , active_alarms(_alloc)
    , success(false)  {
  (void)_alloc;
    }



   typedef ros::Time _stamp_type;
  _stamp_type stamp;

   typedef std::vector<int32_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int32_t>> _active_alarms_type;
  _active_alarms_type active_alarms;

   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::tauv_msgs::SyncAlarmsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tauv_msgs::SyncAlarmsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SyncAlarmsResponse_

typedef ::tauv_msgs::SyncAlarmsResponse_<std::allocator<void> > SyncAlarmsResponse;

typedef boost::shared_ptr< ::tauv_msgs::SyncAlarmsResponse > SyncAlarmsResponsePtr;
typedef boost::shared_ptr< ::tauv_msgs::SyncAlarmsResponse const> SyncAlarmsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tauv_msgs::SyncAlarmsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tauv_msgs::SyncAlarmsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tauv_msgs::SyncAlarmsResponse_<ContainerAllocator1> & lhs, const ::tauv_msgs::SyncAlarmsResponse_<ContainerAllocator2> & rhs)
{
  return lhs.stamp == rhs.stamp &&
    lhs.active_alarms == rhs.active_alarms &&
    lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tauv_msgs::SyncAlarmsResponse_<ContainerAllocator1> & lhs, const ::tauv_msgs::SyncAlarmsResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tauv_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::tauv_msgs::SyncAlarmsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tauv_msgs::SyncAlarmsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tauv_msgs::SyncAlarmsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tauv_msgs::SyncAlarmsResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tauv_msgs::SyncAlarmsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tauv_msgs::SyncAlarmsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tauv_msgs::SyncAlarmsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a432d60ab588421c6ba91ab7242b55f2";
  }

  static const char* value(const ::tauv_msgs::SyncAlarmsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa432d60ab588421cULL;
  static const uint64_t static_value2 = 0x6ba91ab7242b55f2ULL;
};

template<class ContainerAllocator>
struct DataType< ::tauv_msgs::SyncAlarmsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tauv_msgs/SyncAlarmsResponse";
  }

  static const char* value(const ::tauv_msgs::SyncAlarmsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tauv_msgs::SyncAlarmsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"time stamp\n"
"int32[] active_alarms\n"
"bool success  # false indicates some sort of failure\n"
;
  }

  static const char* value(const ::tauv_msgs::SyncAlarmsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tauv_msgs::SyncAlarmsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.stamp);
      stream.next(m.active_alarms);
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SyncAlarmsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tauv_msgs::SyncAlarmsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tauv_msgs::SyncAlarmsResponse_<ContainerAllocator>& v)
  {
    s << indent << "stamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.stamp);
    s << indent << "active_alarms[]" << std::endl;
    for (size_t i = 0; i < v.active_alarms.size(); ++i)
    {
      s << indent << "  active_alarms[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.active_alarms[i]);
    }
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TAUV_MSGS_MESSAGE_SYNCALARMSRESPONSE_H
