// Generated by gencpp from file tauv_msgs/SyncAlarmsRequest.msg
// DO NOT EDIT!


#ifndef TAUV_MSGS_MESSAGE_SYNCALARMSREQUEST_H
#define TAUV_MSGS_MESSAGE_SYNCALARMSREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <tauv_msgs/AlarmWithMessage.h>

namespace tauv_msgs
{
template <class ContainerAllocator>
struct SyncAlarmsRequest_
{
  typedef SyncAlarmsRequest_<ContainerAllocator> Type;

  SyncAlarmsRequest_()
    : diff()  {
    }
  SyncAlarmsRequest_(const ContainerAllocator& _alloc)
    : diff(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::tauv_msgs::AlarmWithMessage_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::tauv_msgs::AlarmWithMessage_<ContainerAllocator> >> _diff_type;
  _diff_type diff;





  typedef boost::shared_ptr< ::tauv_msgs::SyncAlarmsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tauv_msgs::SyncAlarmsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SyncAlarmsRequest_

typedef ::tauv_msgs::SyncAlarmsRequest_<std::allocator<void> > SyncAlarmsRequest;

typedef boost::shared_ptr< ::tauv_msgs::SyncAlarmsRequest > SyncAlarmsRequestPtr;
typedef boost::shared_ptr< ::tauv_msgs::SyncAlarmsRequest const> SyncAlarmsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tauv_msgs::SyncAlarmsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tauv_msgs::SyncAlarmsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tauv_msgs::SyncAlarmsRequest_<ContainerAllocator1> & lhs, const ::tauv_msgs::SyncAlarmsRequest_<ContainerAllocator2> & rhs)
{
  return lhs.diff == rhs.diff;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tauv_msgs::SyncAlarmsRequest_<ContainerAllocator1> & lhs, const ::tauv_msgs::SyncAlarmsRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tauv_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::tauv_msgs::SyncAlarmsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tauv_msgs::SyncAlarmsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tauv_msgs::SyncAlarmsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tauv_msgs::SyncAlarmsRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tauv_msgs::SyncAlarmsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tauv_msgs::SyncAlarmsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tauv_msgs::SyncAlarmsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "968621d8f52d5d5fb6c3529a8a70d975";
  }

  static const char* value(const ::tauv_msgs::SyncAlarmsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x968621d8f52d5d5fULL;
  static const uint64_t static_value2 = 0xb6c3529a8a70d975ULL;
};

template<class ContainerAllocator>
struct DataType< ::tauv_msgs::SyncAlarmsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tauv_msgs/SyncAlarmsRequest";
  }

  static const char* value(const ::tauv_msgs::SyncAlarmsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tauv_msgs::SyncAlarmsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Note: Angular velocities outside of yaw (z axis) are currently unused.\n"
"\n"
"tauv_msgs/AlarmWithMessage[] diff\n"
"\n"
"\n"
"================================================================================\n"
"MSG: tauv_msgs/AlarmWithMessage\n"
"int32 id            # ID of the alarm\n"
"bool set            # True = set, False = Cleared\n"
"string message      # Readable message\n"
;
  }

  static const char* value(const ::tauv_msgs::SyncAlarmsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tauv_msgs::SyncAlarmsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.diff);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SyncAlarmsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tauv_msgs::SyncAlarmsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tauv_msgs::SyncAlarmsRequest_<ContainerAllocator>& v)
  {
    s << indent << "diff[]" << std::endl;
    for (size_t i = 0; i < v.diff.size(); ++i)
    {
      s << indent << "  diff[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::tauv_msgs::AlarmWithMessage_<ContainerAllocator> >::stream(s, indent + "    ", v.diff[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // TAUV_MSGS_MESSAGE_SYNCALARMSREQUEST_H
