// Generated by gencpp from file tauv_msgs/SyncAlarms.msg
// DO NOT EDIT!


#ifndef TAUV_MSGS_MESSAGE_SYNCALARMS_H
#define TAUV_MSGS_MESSAGE_SYNCALARMS_H

#include <ros/service_traits.h>


#include <tauv_msgs/SyncAlarmsRequest.h>
#include <tauv_msgs/SyncAlarmsResponse.h>


namespace tauv_msgs
{

struct SyncAlarms
{

typedef SyncAlarmsRequest Request;
typedef SyncAlarmsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SyncAlarms
} // namespace tauv_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tauv_msgs::SyncAlarms > {
  static const char* value()
  {
    return "54b1739021e723bf57d59b6622adc3ef";
  }

  static const char* value(const ::tauv_msgs::SyncAlarms&) { return value(); }
};

template<>
struct DataType< ::tauv_msgs::SyncAlarms > {
  static const char* value()
  {
    return "tauv_msgs/SyncAlarms";
  }

  static const char* value(const ::tauv_msgs::SyncAlarms&) { return value(); }
};


// service_traits::MD5Sum< ::tauv_msgs::SyncAlarmsRequest> should match
// service_traits::MD5Sum< ::tauv_msgs::SyncAlarms >
template<>
struct MD5Sum< ::tauv_msgs::SyncAlarmsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tauv_msgs::SyncAlarms >::value();
  }
  static const char* value(const ::tauv_msgs::SyncAlarmsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tauv_msgs::SyncAlarmsRequest> should match
// service_traits::DataType< ::tauv_msgs::SyncAlarms >
template<>
struct DataType< ::tauv_msgs::SyncAlarmsRequest>
{
  static const char* value()
  {
    return DataType< ::tauv_msgs::SyncAlarms >::value();
  }
  static const char* value(const ::tauv_msgs::SyncAlarmsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tauv_msgs::SyncAlarmsResponse> should match
// service_traits::MD5Sum< ::tauv_msgs::SyncAlarms >
template<>
struct MD5Sum< ::tauv_msgs::SyncAlarmsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tauv_msgs::SyncAlarms >::value();
  }
  static const char* value(const ::tauv_msgs::SyncAlarmsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tauv_msgs::SyncAlarmsResponse> should match
// service_traits::DataType< ::tauv_msgs::SyncAlarms >
template<>
struct DataType< ::tauv_msgs::SyncAlarmsResponse>
{
  static const char* value()
  {
    return DataType< ::tauv_msgs::SyncAlarms >::value();
  }
  static const char* value(const ::tauv_msgs::SyncAlarmsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TAUV_MSGS_MESSAGE_SYNCALARMS_H
