// Generated by gencpp from file tauv_msgs/Thrust.msg
// DO NOT EDIT!


#ifndef TAUV_MSGS_MESSAGE_THRUST_H
#define TAUV_MSGS_MESSAGE_THRUST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace tauv_msgs
{
template <class ContainerAllocator>
struct Thrust_
{
  typedef Thrust_<ContainerAllocator> Type;

  Thrust_()
    : header()
    , thrusts()  {
    }
  Thrust_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , thrusts(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _thrusts_type;
  _thrusts_type thrusts;





  typedef boost::shared_ptr< ::tauv_msgs::Thrust_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tauv_msgs::Thrust_<ContainerAllocator> const> ConstPtr;

}; // struct Thrust_

typedef ::tauv_msgs::Thrust_<std::allocator<void> > Thrust;

typedef boost::shared_ptr< ::tauv_msgs::Thrust > ThrustPtr;
typedef boost::shared_ptr< ::tauv_msgs::Thrust const> ThrustConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tauv_msgs::Thrust_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tauv_msgs::Thrust_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tauv_msgs::Thrust_<ContainerAllocator1> & lhs, const ::tauv_msgs::Thrust_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.thrusts == rhs.thrusts;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tauv_msgs::Thrust_<ContainerAllocator1> & lhs, const ::tauv_msgs::Thrust_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tauv_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::tauv_msgs::Thrust_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tauv_msgs::Thrust_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tauv_msgs::Thrust_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tauv_msgs::Thrust_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tauv_msgs::Thrust_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tauv_msgs::Thrust_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tauv_msgs::Thrust_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dad92a8d25b7ce836a9750ca65604332";
  }

  static const char* value(const ::tauv_msgs::Thrust_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdad92a8d25b7ce83ULL;
  static const uint64_t static_value2 = 0x6a9750ca65604332ULL;
};

template<class ContainerAllocator>
struct DataType< ::tauv_msgs::Thrust_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tauv_msgs/Thrust";
  }

  static const char* value(const ::tauv_msgs::Thrust_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tauv_msgs::Thrust_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"float64[] thrusts\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::tauv_msgs::Thrust_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tauv_msgs::Thrust_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.thrusts);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Thrust_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tauv_msgs::Thrust_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tauv_msgs::Thrust_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "thrusts[]" << std::endl;
    for (size_t i = 0; i < v.thrusts.size(); ++i)
    {
      s << indent << "  thrusts[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.thrusts[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // TAUV_MSGS_MESSAGE_THRUST_H
