// Generated by gencpp from file tauv_msgs/TunePIDPlannerRequest.msg
// DO NOT EDIT!


#ifndef TAUV_MSGS_MESSAGE_TUNEPIDPLANNERREQUEST_H
#define TAUV_MSGS_MESSAGE_TUNEPIDPLANNERREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <tauv_msgs/PIDTuning.h>

namespace tauv_msgs
{
template <class ContainerAllocator>
struct TunePIDPlannerRequest_
{
  typedef TunePIDPlannerRequest_<ContainerAllocator> Type;

  TunePIDPlannerRequest_()
    : tunings()  {
    }
  TunePIDPlannerRequest_(const ContainerAllocator& _alloc)
    : tunings(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::tauv_msgs::PIDTuning_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::tauv_msgs::PIDTuning_<ContainerAllocator> >> _tunings_type;
  _tunings_type tunings;





  typedef boost::shared_ptr< ::tauv_msgs::TunePIDPlannerRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tauv_msgs::TunePIDPlannerRequest_<ContainerAllocator> const> ConstPtr;

}; // struct TunePIDPlannerRequest_

typedef ::tauv_msgs::TunePIDPlannerRequest_<std::allocator<void> > TunePIDPlannerRequest;

typedef boost::shared_ptr< ::tauv_msgs::TunePIDPlannerRequest > TunePIDPlannerRequestPtr;
typedef boost::shared_ptr< ::tauv_msgs::TunePIDPlannerRequest const> TunePIDPlannerRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tauv_msgs::TunePIDPlannerRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tauv_msgs::TunePIDPlannerRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tauv_msgs::TunePIDPlannerRequest_<ContainerAllocator1> & lhs, const ::tauv_msgs::TunePIDPlannerRequest_<ContainerAllocator2> & rhs)
{
  return lhs.tunings == rhs.tunings;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tauv_msgs::TunePIDPlannerRequest_<ContainerAllocator1> & lhs, const ::tauv_msgs::TunePIDPlannerRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tauv_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::tauv_msgs::TunePIDPlannerRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tauv_msgs::TunePIDPlannerRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tauv_msgs::TunePIDPlannerRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tauv_msgs::TunePIDPlannerRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tauv_msgs::TunePIDPlannerRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tauv_msgs::TunePIDPlannerRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tauv_msgs::TunePIDPlannerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6eb5d206e69b070e4d9bf07120aa9b75";
  }

  static const char* value(const ::tauv_msgs::TunePIDPlannerRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6eb5d206e69b070eULL;
  static const uint64_t static_value2 = 0x4d9bf07120aa9b75ULL;
};

template<class ContainerAllocator>
struct DataType< ::tauv_msgs::TunePIDPlannerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tauv_msgs/TunePIDPlannerRequest";
  }

  static const char* value(const ::tauv_msgs::TunePIDPlannerRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tauv_msgs::TunePIDPlannerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tauv_msgs/PIDTuning[] tunings\n"
"\n"
"================================================================================\n"
"MSG: tauv_msgs/PIDTuning\n"
"string axis\n"
"float64 kp\n"
"float64 ki\n"
"float64 kd\n"
"float64 tau\n"
"float64[2] limits\n"
;
  }

  static const char* value(const ::tauv_msgs::TunePIDPlannerRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tauv_msgs::TunePIDPlannerRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.tunings);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TunePIDPlannerRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tauv_msgs::TunePIDPlannerRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tauv_msgs::TunePIDPlannerRequest_<ContainerAllocator>& v)
  {
    s << indent << "tunings[]" << std::endl;
    for (size_t i = 0; i < v.tunings.size(); ++i)
    {
      s << indent << "  tunings[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::tauv_msgs::PIDTuning_<ContainerAllocator> >::stream(s, indent + "    ", v.tunings[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // TAUV_MSGS_MESSAGE_TUNEPIDPLANNERREQUEST_H
