// Generated by gencpp from file tauv_msgs/TuneDynamics.msg
// DO NOT EDIT!


#ifndef TAUV_MSGS_MESSAGE_TUNEDYNAMICS_H
#define TAUV_MSGS_MESSAGE_TUNEDYNAMICS_H

#include <ros/service_traits.h>


#include <tauv_msgs/TuneDynamicsRequest.h>
#include <tauv_msgs/TuneDynamicsResponse.h>


namespace tauv_msgs
{

struct TuneDynamics
{

typedef TuneDynamicsRequest Request;
typedef TuneDynamicsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TuneDynamics
} // namespace tauv_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tauv_msgs::TuneDynamics > {
  static const char* value()
  {
    return "7d0bd5eafc7372a83c5502516a094dbc";
  }

  static const char* value(const ::tauv_msgs::TuneDynamics&) { return value(); }
};

template<>
struct DataType< ::tauv_msgs::TuneDynamics > {
  static const char* value()
  {
    return "tauv_msgs/TuneDynamics";
  }

  static const char* value(const ::tauv_msgs::TuneDynamics&) { return value(); }
};


// service_traits::MD5Sum< ::tauv_msgs::TuneDynamicsRequest> should match
// service_traits::MD5Sum< ::tauv_msgs::TuneDynamics >
template<>
struct MD5Sum< ::tauv_msgs::TuneDynamicsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tauv_msgs::TuneDynamics >::value();
  }
  static const char* value(const ::tauv_msgs::TuneDynamicsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tauv_msgs::TuneDynamicsRequest> should match
// service_traits::DataType< ::tauv_msgs::TuneDynamics >
template<>
struct DataType< ::tauv_msgs::TuneDynamicsRequest>
{
  static const char* value()
  {
    return DataType< ::tauv_msgs::TuneDynamics >::value();
  }
  static const char* value(const ::tauv_msgs::TuneDynamicsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tauv_msgs::TuneDynamicsResponse> should match
// service_traits::MD5Sum< ::tauv_msgs::TuneDynamics >
template<>
struct MD5Sum< ::tauv_msgs::TuneDynamicsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tauv_msgs::TuneDynamics >::value();
  }
  static const char* value(const ::tauv_msgs::TuneDynamicsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tauv_msgs::TuneDynamicsResponse> should match
// service_traits::DataType< ::tauv_msgs::TuneDynamics >
template<>
struct DataType< ::tauv_msgs::TuneDynamicsResponse>
{
  static const char* value()
  {
    return DataType< ::tauv_msgs::TuneDynamics >::value();
  }
  static const char* value(const ::tauv_msgs::TuneDynamicsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TAUV_MSGS_MESSAGE_TUNEDYNAMICS_H
