// Generated by gencpp from file tauv_msgs/TunePIDPlanner.msg
// DO NOT EDIT!


#ifndef TAUV_MSGS_MESSAGE_TUNEPIDPLANNER_H
#define TAUV_MSGS_MESSAGE_TUNEPIDPLANNER_H

#include <ros/service_traits.h>


#include <tauv_msgs/TunePIDPlannerRequest.h>
#include <tauv_msgs/TunePIDPlannerResponse.h>


namespace tauv_msgs
{

struct TunePIDPlanner
{

typedef TunePIDPlannerRequest Request;
typedef TunePIDPlannerResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TunePIDPlanner
} // namespace tauv_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tauv_msgs::TunePIDPlanner > {
  static const char* value()
  {
    return "c6a95158ee66091a3c801f9968586b2d";
  }

  static const char* value(const ::tauv_msgs::TunePIDPlanner&) { return value(); }
};

template<>
struct DataType< ::tauv_msgs::TunePIDPlanner > {
  static const char* value()
  {
    return "tauv_msgs/TunePIDPlanner";
  }

  static const char* value(const ::tauv_msgs::TunePIDPlanner&) { return value(); }
};


// service_traits::MD5Sum< ::tauv_msgs::TunePIDPlannerRequest> should match
// service_traits::MD5Sum< ::tauv_msgs::TunePIDPlanner >
template<>
struct MD5Sum< ::tauv_msgs::TunePIDPlannerRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tauv_msgs::TunePIDPlanner >::value();
  }
  static const char* value(const ::tauv_msgs::TunePIDPlannerRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tauv_msgs::TunePIDPlannerRequest> should match
// service_traits::DataType< ::tauv_msgs::TunePIDPlanner >
template<>
struct DataType< ::tauv_msgs::TunePIDPlannerRequest>
{
  static const char* value()
  {
    return DataType< ::tauv_msgs::TunePIDPlanner >::value();
  }
  static const char* value(const ::tauv_msgs::TunePIDPlannerRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tauv_msgs::TunePIDPlannerResponse> should match
// service_traits::MD5Sum< ::tauv_msgs::TunePIDPlanner >
template<>
struct MD5Sum< ::tauv_msgs::TunePIDPlannerResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tauv_msgs::TunePIDPlanner >::value();
  }
  static const char* value(const ::tauv_msgs::TunePIDPlannerResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tauv_msgs::TunePIDPlannerResponse> should match
// service_traits::DataType< ::tauv_msgs::TunePIDPlanner >
template<>
struct DataType< ::tauv_msgs::TunePIDPlannerResponse>
{
  static const char* value()
  {
    return DataType< ::tauv_msgs::TunePIDPlanner >::value();
  }
  static const char* value(const ::tauv_msgs::TunePIDPlannerResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TAUV_MSGS_MESSAGE_TUNEPIDPLANNER_H
