// Generated by gencpp from file tauv_msgs/TuneDynamicsRequest.msg
// DO NOT EDIT!


#ifndef TAUV_MSGS_MESSAGE_TUNEDYNAMICSREQUEST_H
#define TAUV_MSGS_MESSAGE_TUNEDYNAMICSREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <tauv_msgs/DynamicsTuning.h>

namespace tauv_msgs
{
template <class ContainerAllocator>
struct TuneDynamicsRequest_
{
  typedef TuneDynamicsRequest_<ContainerAllocator> Type;

  TuneDynamicsRequest_()
    : tuning()  {
    }
  TuneDynamicsRequest_(const ContainerAllocator& _alloc)
    : tuning(_alloc)  {
  (void)_alloc;
    }



   typedef  ::tauv_msgs::DynamicsTuning_<ContainerAllocator>  _tuning_type;
  _tuning_type tuning;





  typedef boost::shared_ptr< ::tauv_msgs::TuneDynamicsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tauv_msgs::TuneDynamicsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct TuneDynamicsRequest_

typedef ::tauv_msgs::TuneDynamicsRequest_<std::allocator<void> > TuneDynamicsRequest;

typedef boost::shared_ptr< ::tauv_msgs::TuneDynamicsRequest > TuneDynamicsRequestPtr;
typedef boost::shared_ptr< ::tauv_msgs::TuneDynamicsRequest const> TuneDynamicsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tauv_msgs::TuneDynamicsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tauv_msgs::TuneDynamicsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tauv_msgs::TuneDynamicsRequest_<ContainerAllocator1> & lhs, const ::tauv_msgs::TuneDynamicsRequest_<ContainerAllocator2> & rhs)
{
  return lhs.tuning == rhs.tuning;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tauv_msgs::TuneDynamicsRequest_<ContainerAllocator1> & lhs, const ::tauv_msgs::TuneDynamicsRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tauv_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::tauv_msgs::TuneDynamicsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tauv_msgs::TuneDynamicsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tauv_msgs::TuneDynamicsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tauv_msgs::TuneDynamicsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tauv_msgs::TuneDynamicsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tauv_msgs::TuneDynamicsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tauv_msgs::TuneDynamicsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "75519b80dff65935bfae9b6c04b2e1d8";
  }

  static const char* value(const ::tauv_msgs::TuneDynamicsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x75519b80dff65935ULL;
  static const uint64_t static_value2 = 0xbfae9b6c04b2e1d8ULL;
};

template<class ContainerAllocator>
struct DataType< ::tauv_msgs::TuneDynamicsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tauv_msgs/TuneDynamicsRequest";
  }

  static const char* value(const ::tauv_msgs::TuneDynamicsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tauv_msgs::TuneDynamicsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tauv_msgs/DynamicsTuning tuning\n"
"\n"
"================================================================================\n"
"MSG: tauv_msgs/DynamicsTuning\n"
"bool update_mass\n"
"float64 mass\n"
"bool update_volume\n"
"float64 volume\n"
"bool update_water_density\n"
"float64 water_density\n"
"bool update_center_of_gravity\n"
"float64[3] center_of_gravity\n"
"bool update_center_of_buoyancy\n"
"float64[3] center_of_buoyancy\n"
"bool update_moments\n"
"float64[6] moments\n"
"bool update_linear_damping\n"
"float64[6] linear_damping\n"
"bool update_quadratic_damping\n"
"float64[6] quadratic_damping\n"
"bool update_added_mass\n"
"float64[6] added_mass\n"
;
  }

  static const char* value(const ::tauv_msgs::TuneDynamicsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tauv_msgs::TuneDynamicsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.tuning);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TuneDynamicsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tauv_msgs::TuneDynamicsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tauv_msgs::TuneDynamicsRequest_<ContainerAllocator>& v)
  {
    s << indent << "tuning: ";
    s << std::endl;
    Printer< ::tauv_msgs::DynamicsTuning_<ContainerAllocator> >::stream(s, indent + "  ", v.tuning);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TAUV_MSGS_MESSAGE_TUNEDYNAMICSREQUEST_H
