// Generated by gencpp from file tauv_msgs/UpdateDynamicsParameterConfigsRequest.msg
// DO NOT EDIT!


#ifndef TAUV_MSGS_MESSAGE_UPDATEDYNAMICSPARAMETERCONFIGSREQUEST_H
#define TAUV_MSGS_MESSAGE_UPDATEDYNAMICSPARAMETERCONFIGSREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <tauv_msgs/DynamicsParameterConfigUpdate.h>

namespace tauv_msgs
{
template <class ContainerAllocator>
struct UpdateDynamicsParameterConfigsRequest_
{
  typedef UpdateDynamicsParameterConfigsRequest_<ContainerAllocator> Type;

  UpdateDynamicsParameterConfigsRequest_()
    : updates()  {
    }
  UpdateDynamicsParameterConfigsRequest_(const ContainerAllocator& _alloc)
    : updates(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::tauv_msgs::DynamicsParameterConfigUpdate_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::tauv_msgs::DynamicsParameterConfigUpdate_<ContainerAllocator> >> _updates_type;
  _updates_type updates;





  typedef boost::shared_ptr< ::tauv_msgs::UpdateDynamicsParameterConfigsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tauv_msgs::UpdateDynamicsParameterConfigsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct UpdateDynamicsParameterConfigsRequest_

typedef ::tauv_msgs::UpdateDynamicsParameterConfigsRequest_<std::allocator<void> > UpdateDynamicsParameterConfigsRequest;

typedef boost::shared_ptr< ::tauv_msgs::UpdateDynamicsParameterConfigsRequest > UpdateDynamicsParameterConfigsRequestPtr;
typedef boost::shared_ptr< ::tauv_msgs::UpdateDynamicsParameterConfigsRequest const> UpdateDynamicsParameterConfigsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tauv_msgs::UpdateDynamicsParameterConfigsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tauv_msgs::UpdateDynamicsParameterConfigsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tauv_msgs::UpdateDynamicsParameterConfigsRequest_<ContainerAllocator1> & lhs, const ::tauv_msgs::UpdateDynamicsParameterConfigsRequest_<ContainerAllocator2> & rhs)
{
  return lhs.updates == rhs.updates;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tauv_msgs::UpdateDynamicsParameterConfigsRequest_<ContainerAllocator1> & lhs, const ::tauv_msgs::UpdateDynamicsParameterConfigsRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tauv_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::tauv_msgs::UpdateDynamicsParameterConfigsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tauv_msgs::UpdateDynamicsParameterConfigsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tauv_msgs::UpdateDynamicsParameterConfigsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tauv_msgs::UpdateDynamicsParameterConfigsRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tauv_msgs::UpdateDynamicsParameterConfigsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tauv_msgs::UpdateDynamicsParameterConfigsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tauv_msgs::UpdateDynamicsParameterConfigsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6b0568555c382068683b9ab2dfb31b6b";
  }

  static const char* value(const ::tauv_msgs::UpdateDynamicsParameterConfigsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6b0568555c382068ULL;
  static const uint64_t static_value2 = 0x683b9ab2dfb31b6bULL;
};

template<class ContainerAllocator>
struct DataType< ::tauv_msgs::UpdateDynamicsParameterConfigsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tauv_msgs/UpdateDynamicsParameterConfigsRequest";
  }

  static const char* value(const ::tauv_msgs::UpdateDynamicsParameterConfigsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tauv_msgs::UpdateDynamicsParameterConfigsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tauv_msgs/DynamicsParameterConfigUpdate[] updates\n"
"\n"
"================================================================================\n"
"MSG: tauv_msgs/DynamicsParameterConfigUpdate\n"
"string name\n"
"\n"
"bool update_initial_value\n"
"float64 initial_value\n"
"\n"
"bool update_fixed\n"
"bool fixed\n"
"\n"
"bool update_initial_covariance\n"
"float64 initial_covariance\n"
"\n"
"bool update_process_covariance\n"
"float64 process_covariance\n"
"\n"
"bool update_limits\n"
"float64[2] limits\n"
"\n"
"bool reset\n"
"\n"
"\n"
;
  }

  static const char* value(const ::tauv_msgs::UpdateDynamicsParameterConfigsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tauv_msgs::UpdateDynamicsParameterConfigsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.updates);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct UpdateDynamicsParameterConfigsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tauv_msgs::UpdateDynamicsParameterConfigsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tauv_msgs::UpdateDynamicsParameterConfigsRequest_<ContainerAllocator>& v)
  {
    s << indent << "updates[]" << std::endl;
    for (size_t i = 0; i < v.updates.size(); ++i)
    {
      s << indent << "  updates[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::tauv_msgs::DynamicsParameterConfigUpdate_<ContainerAllocator> >::stream(s, indent + "    ", v.updates[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // TAUV_MSGS_MESSAGE_UPDATEDYNAMICSPARAMETERCONFIGSREQUEST_H
