// Generated by gencpp from file tauv_msgs/UpdateDynamicsParameterConfigs.msg
// DO NOT EDIT!


#ifndef TAUV_MSGS_MESSAGE_UPDATEDYNAMICSPARAMETERCONFIGS_H
#define TAUV_MSGS_MESSAGE_UPDATEDYNAMICSPARAMETERCONFIGS_H

#include <ros/service_traits.h>


#include <tauv_msgs/UpdateDynamicsParameterConfigsRequest.h>
#include <tauv_msgs/UpdateDynamicsParameterConfigsResponse.h>


namespace tauv_msgs
{

struct UpdateDynamicsParameterConfigs
{

typedef UpdateDynamicsParameterConfigsRequest Request;
typedef UpdateDynamicsParameterConfigsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct UpdateDynamicsParameterConfigs
} // namespace tauv_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tauv_msgs::UpdateDynamicsParameterConfigs > {
  static const char* value()
  {
    return "613592a768bbac2700fe9ff9c5b0cffe";
  }

  static const char* value(const ::tauv_msgs::UpdateDynamicsParameterConfigs&) { return value(); }
};

template<>
struct DataType< ::tauv_msgs::UpdateDynamicsParameterConfigs > {
  static const char* value()
  {
    return "tauv_msgs/UpdateDynamicsParameterConfigs";
  }

  static const char* value(const ::tauv_msgs::UpdateDynamicsParameterConfigs&) { return value(); }
};


// service_traits::MD5Sum< ::tauv_msgs::UpdateDynamicsParameterConfigsRequest> should match
// service_traits::MD5Sum< ::tauv_msgs::UpdateDynamicsParameterConfigs >
template<>
struct MD5Sum< ::tauv_msgs::UpdateDynamicsParameterConfigsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tauv_msgs::UpdateDynamicsParameterConfigs >::value();
  }
  static const char* value(const ::tauv_msgs::UpdateDynamicsParameterConfigsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tauv_msgs::UpdateDynamicsParameterConfigsRequest> should match
// service_traits::DataType< ::tauv_msgs::UpdateDynamicsParameterConfigs >
template<>
struct DataType< ::tauv_msgs::UpdateDynamicsParameterConfigsRequest>
{
  static const char* value()
  {
    return DataType< ::tauv_msgs::UpdateDynamicsParameterConfigs >::value();
  }
  static const char* value(const ::tauv_msgs::UpdateDynamicsParameterConfigsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tauv_msgs::UpdateDynamicsParameterConfigsResponse> should match
// service_traits::MD5Sum< ::tauv_msgs::UpdateDynamicsParameterConfigs >
template<>
struct MD5Sum< ::tauv_msgs::UpdateDynamicsParameterConfigsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tauv_msgs::UpdateDynamicsParameterConfigs >::value();
  }
  static const char* value(const ::tauv_msgs::UpdateDynamicsParameterConfigsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tauv_msgs::UpdateDynamicsParameterConfigsResponse> should match
// service_traits::DataType< ::tauv_msgs::UpdateDynamicsParameterConfigs >
template<>
struct DataType< ::tauv_msgs::UpdateDynamicsParameterConfigsResponse>
{
  static const char* value()
  {
    return DataType< ::tauv_msgs::UpdateDynamicsParameterConfigs >::value();
  }
  static const char* value(const ::tauv_msgs::UpdateDynamicsParameterConfigsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TAUV_MSGS_MESSAGE_UPDATEDYNAMICSPARAMETERCONFIGS_H
