// Generated by gencpp from file tauv_msgs/XsensImuData.msg
// DO NOT EDIT!


#ifndef TAUV_MSGS_MESSAGE_XSENSIMUDATA_H
#define TAUV_MSGS_MESSAGE_XSENSIMUDATA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>

namespace tauv_msgs
{
template <class ContainerAllocator>
struct XsensImuData_
{
  typedef XsensImuData_<ContainerAllocator> Type;

  XsensImuData_()
    : header()
    , ros_time()
    , imu_time()
    , triggered_dvl(false)
    , orientation()
    , rate_of_turn()
    , linear_acceleration()
    , free_acceleration()  {
    }
  XsensImuData_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , ros_time()
    , imu_time()
    , triggered_dvl(false)
    , orientation(_alloc)
    , rate_of_turn(_alloc)
    , linear_acceleration(_alloc)
    , free_acceleration(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef ros::Time _ros_time_type;
  _ros_time_type ros_time;

   typedef ros::Time _imu_time_type;
  _imu_time_type imu_time;

   typedef uint8_t _triggered_dvl_type;
  _triggered_dvl_type triggered_dvl;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _orientation_type;
  _orientation_type orientation;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _rate_of_turn_type;
  _rate_of_turn_type rate_of_turn;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _linear_acceleration_type;
  _linear_acceleration_type linear_acceleration;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _free_acceleration_type;
  _free_acceleration_type free_acceleration;





  typedef boost::shared_ptr< ::tauv_msgs::XsensImuData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tauv_msgs::XsensImuData_<ContainerAllocator> const> ConstPtr;

}; // struct XsensImuData_

typedef ::tauv_msgs::XsensImuData_<std::allocator<void> > XsensImuData;

typedef boost::shared_ptr< ::tauv_msgs::XsensImuData > XsensImuDataPtr;
typedef boost::shared_ptr< ::tauv_msgs::XsensImuData const> XsensImuDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tauv_msgs::XsensImuData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tauv_msgs::XsensImuData_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tauv_msgs::XsensImuData_<ContainerAllocator1> & lhs, const ::tauv_msgs::XsensImuData_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.ros_time == rhs.ros_time &&
    lhs.imu_time == rhs.imu_time &&
    lhs.triggered_dvl == rhs.triggered_dvl &&
    lhs.orientation == rhs.orientation &&
    lhs.rate_of_turn == rhs.rate_of_turn &&
    lhs.linear_acceleration == rhs.linear_acceleration &&
    lhs.free_acceleration == rhs.free_acceleration;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tauv_msgs::XsensImuData_<ContainerAllocator1> & lhs, const ::tauv_msgs::XsensImuData_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tauv_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::tauv_msgs::XsensImuData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tauv_msgs::XsensImuData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tauv_msgs::XsensImuData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tauv_msgs::XsensImuData_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tauv_msgs::XsensImuData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tauv_msgs::XsensImuData_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tauv_msgs::XsensImuData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a5e7b14c591863b869ed2281b0f6b1ed";
  }

  static const char* value(const ::tauv_msgs::XsensImuData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa5e7b14c591863b8ULL;
  static const uint64_t static_value2 = 0x69ed2281b0f6b1edULL;
};

template<class ContainerAllocator>
struct DataType< ::tauv_msgs::XsensImuData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tauv_msgs/XsensImuData";
  }

  static const char* value(const ::tauv_msgs::XsensImuData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tauv_msgs::XsensImuData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"time ros_time\n"
"\n"
"time imu_time\n"
"\n"
"bool triggered_dvl\n"
"\n"
"geometry_msgs/Vector3 orientation\n"
"\n"
"geometry_msgs/Vector3 rate_of_turn\n"
"\n"
"geometry_msgs/Vector3 linear_acceleration\n"
"\n"
"geometry_msgs/Vector3 free_acceleration\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::tauv_msgs::XsensImuData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tauv_msgs::XsensImuData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.ros_time);
      stream.next(m.imu_time);
      stream.next(m.triggered_dvl);
      stream.next(m.orientation);
      stream.next(m.rate_of_turn);
      stream.next(m.linear_acceleration);
      stream.next(m.free_acceleration);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct XsensImuData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tauv_msgs::XsensImuData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tauv_msgs::XsensImuData_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "ros_time: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.ros_time);
    s << indent << "imu_time: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.imu_time);
    s << indent << "triggered_dvl: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.triggered_dvl);
    s << indent << "orientation: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.orientation);
    s << indent << "rate_of_turn: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.rate_of_turn);
    s << indent << "linear_acceleration: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.linear_acceleration);
    s << indent << "free_acceleration: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.free_acceleration);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TAUV_MSGS_MESSAGE_XSENSIMUDATA_H
