# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from tauv_msgs/ControllerCommand.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class ControllerCommand(genpy.Message):
  _md5sum = "ad1b57ce703dafd167a4f28711d03e4e"
  _type = "tauv_msgs/ControllerCommand"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# Accelerations
float32 a_x
float32 a_y
float32 a_z
float32 a_roll
float32 a_pitch
float32 a_yaw

# Forces
float32 f_x
float32 f_y
float32 f_z
float32 f_roll
float32 f_pitch
float32 f_yaw

# If set, override accelerations and use forces
bool use_f_x
bool use_f_y
bool use_f_z
bool use_f_roll
bool use_f_pitch
bool use_f_yaw

# Setpoints
float32 setpoint_z
float32 setpoint_roll
float32 setpoint_pitch

# If set, override accelerations and forces and use setpoints
bool use_setpoint_z
bool use_setpoint_roll
bool use_setpoint_pitch"""
  __slots__ = ['a_x','a_y','a_z','a_roll','a_pitch','a_yaw','f_x','f_y','f_z','f_roll','f_pitch','f_yaw','use_f_x','use_f_y','use_f_z','use_f_roll','use_f_pitch','use_f_yaw','setpoint_z','setpoint_roll','setpoint_pitch','use_setpoint_z','use_setpoint_roll','use_setpoint_pitch']
  _slot_types = ['float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','bool','bool','bool','bool','bool','bool','float32','float32','float32','bool','bool','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       a_x,a_y,a_z,a_roll,a_pitch,a_yaw,f_x,f_y,f_z,f_roll,f_pitch,f_yaw,use_f_x,use_f_y,use_f_z,use_f_roll,use_f_pitch,use_f_yaw,setpoint_z,setpoint_roll,setpoint_pitch,use_setpoint_z,use_setpoint_roll,use_setpoint_pitch

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ControllerCommand, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.a_x is None:
        self.a_x = 0.
      if self.a_y is None:
        self.a_y = 0.
      if self.a_z is None:
        self.a_z = 0.
      if self.a_roll is None:
        self.a_roll = 0.
      if self.a_pitch is None:
        self.a_pitch = 0.
      if self.a_yaw is None:
        self.a_yaw = 0.
      if self.f_x is None:
        self.f_x = 0.
      if self.f_y is None:
        self.f_y = 0.
      if self.f_z is None:
        self.f_z = 0.
      if self.f_roll is None:
        self.f_roll = 0.
      if self.f_pitch is None:
        self.f_pitch = 0.
      if self.f_yaw is None:
        self.f_yaw = 0.
      if self.use_f_x is None:
        self.use_f_x = False
      if self.use_f_y is None:
        self.use_f_y = False
      if self.use_f_z is None:
        self.use_f_z = False
      if self.use_f_roll is None:
        self.use_f_roll = False
      if self.use_f_pitch is None:
        self.use_f_pitch = False
      if self.use_f_yaw is None:
        self.use_f_yaw = False
      if self.setpoint_z is None:
        self.setpoint_z = 0.
      if self.setpoint_roll is None:
        self.setpoint_roll = 0.
      if self.setpoint_pitch is None:
        self.setpoint_pitch = 0.
      if self.use_setpoint_z is None:
        self.use_setpoint_z = False
      if self.use_setpoint_roll is None:
        self.use_setpoint_roll = False
      if self.use_setpoint_pitch is None:
        self.use_setpoint_pitch = False
    else:
      self.a_x = 0.
      self.a_y = 0.
      self.a_z = 0.
      self.a_roll = 0.
      self.a_pitch = 0.
      self.a_yaw = 0.
      self.f_x = 0.
      self.f_y = 0.
      self.f_z = 0.
      self.f_roll = 0.
      self.f_pitch = 0.
      self.f_yaw = 0.
      self.use_f_x = False
      self.use_f_y = False
      self.use_f_z = False
      self.use_f_roll = False
      self.use_f_pitch = False
      self.use_f_yaw = False
      self.setpoint_z = 0.
      self.setpoint_roll = 0.
      self.setpoint_pitch = 0.
      self.use_setpoint_z = False
      self.use_setpoint_roll = False
      self.use_setpoint_pitch = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_12f6B3f3B().pack(_x.a_x, _x.a_y, _x.a_z, _x.a_roll, _x.a_pitch, _x.a_yaw, _x.f_x, _x.f_y, _x.f_z, _x.f_roll, _x.f_pitch, _x.f_yaw, _x.use_f_x, _x.use_f_y, _x.use_f_z, _x.use_f_roll, _x.use_f_pitch, _x.use_f_yaw, _x.setpoint_z, _x.setpoint_roll, _x.setpoint_pitch, _x.use_setpoint_z, _x.use_setpoint_roll, _x.use_setpoint_pitch))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 69
      (_x.a_x, _x.a_y, _x.a_z, _x.a_roll, _x.a_pitch, _x.a_yaw, _x.f_x, _x.f_y, _x.f_z, _x.f_roll, _x.f_pitch, _x.f_yaw, _x.use_f_x, _x.use_f_y, _x.use_f_z, _x.use_f_roll, _x.use_f_pitch, _x.use_f_yaw, _x.setpoint_z, _x.setpoint_roll, _x.setpoint_pitch, _x.use_setpoint_z, _x.use_setpoint_roll, _x.use_setpoint_pitch,) = _get_struct_12f6B3f3B().unpack(str[start:end])
      self.use_f_x = bool(self.use_f_x)
      self.use_f_y = bool(self.use_f_y)
      self.use_f_z = bool(self.use_f_z)
      self.use_f_roll = bool(self.use_f_roll)
      self.use_f_pitch = bool(self.use_f_pitch)
      self.use_f_yaw = bool(self.use_f_yaw)
      self.use_setpoint_z = bool(self.use_setpoint_z)
      self.use_setpoint_roll = bool(self.use_setpoint_roll)
      self.use_setpoint_pitch = bool(self.use_setpoint_pitch)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_12f6B3f3B().pack(_x.a_x, _x.a_y, _x.a_z, _x.a_roll, _x.a_pitch, _x.a_yaw, _x.f_x, _x.f_y, _x.f_z, _x.f_roll, _x.f_pitch, _x.f_yaw, _x.use_f_x, _x.use_f_y, _x.use_f_z, _x.use_f_roll, _x.use_f_pitch, _x.use_f_yaw, _x.setpoint_z, _x.setpoint_roll, _x.setpoint_pitch, _x.use_setpoint_z, _x.use_setpoint_roll, _x.use_setpoint_pitch))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 69
      (_x.a_x, _x.a_y, _x.a_z, _x.a_roll, _x.a_pitch, _x.a_yaw, _x.f_x, _x.f_y, _x.f_z, _x.f_roll, _x.f_pitch, _x.f_yaw, _x.use_f_x, _x.use_f_y, _x.use_f_z, _x.use_f_roll, _x.use_f_pitch, _x.use_f_yaw, _x.setpoint_z, _x.setpoint_roll, _x.setpoint_pitch, _x.use_setpoint_z, _x.use_setpoint_roll, _x.use_setpoint_pitch,) = _get_struct_12f6B3f3B().unpack(str[start:end])
      self.use_f_x = bool(self.use_f_x)
      self.use_f_y = bool(self.use_f_y)
      self.use_f_z = bool(self.use_f_z)
      self.use_f_roll = bool(self.use_f_roll)
      self.use_f_pitch = bool(self.use_f_pitch)
      self.use_f_yaw = bool(self.use_f_yaw)
      self.use_setpoint_z = bool(self.use_setpoint_z)
      self.use_setpoint_roll = bool(self.use_setpoint_roll)
      self.use_setpoint_pitch = bool(self.use_setpoint_pitch)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_12f6B3f3B = None
def _get_struct_12f6B3f3B():
    global _struct_12f6B3f3B
    if _struct_12f6B3f3B is None:
        _struct_12f6B3f3B = struct.Struct("<12f6B3f3B")
    return _struct_12f6B3f3B
