# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from tauv_msgs/Ctrl_cmd.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Ctrl_cmd(genpy.Message):
  _md5sum = "7a746ffc64e1d5a26fb5d6cba04e63c2"
  _type = "tauv_msgs/Ctrl_cmd"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """
uint8[4] Ctrl_vel_X
uint8[4] Ctrl_vel_Y
uint8[4] Ctrl_vel_Z
uint8[4] Ctrl_fixed_Z
uint8[4] Ctrl_vel_Rol
uint8[4] Ctrl_vel_Pit
uint8[4] Ctrl_vel_Yaw
uint8[4] Ctrl_fixed_Yaw

uint8[4] Ctrl_pivot_1
uint8[4] Ctrl_pivot_2
uint8[4] Ctrl_pivot_3
uint8[4] Ctrl_pivot_4

uint8[4] Ctrl_emagnet_1
uint8[4] Ctrl_emagnet_2
uint8[4] Ctrl_emagnet_3
uint8[4] Ctrl_emagnet_4

uint8[4] Ctrl_arm_joint_1
uint8[4] Ctrl_arm_joint_2

int16[4] Joy_Button_Y
int16[4] Joy_Button_X
int16[4] Joy_Button_A
int16[4] Joy_Button_B
int16[4] Joy_Button_LB
int16[4] Joy_Button_RB
int16[4] Joy_Button_STICK_LEFT
int16[4] Joy_Button_STICK_RIGHT
int16[4] Reset_pwm
"""
  __slots__ = ['Ctrl_vel_X','Ctrl_vel_Y','Ctrl_vel_Z','Ctrl_fixed_Z','Ctrl_vel_Rol','Ctrl_vel_Pit','Ctrl_vel_Yaw','Ctrl_fixed_Yaw','Ctrl_pivot_1','Ctrl_pivot_2','Ctrl_pivot_3','Ctrl_pivot_4','Ctrl_emagnet_1','Ctrl_emagnet_2','Ctrl_emagnet_3','Ctrl_emagnet_4','Ctrl_arm_joint_1','Ctrl_arm_joint_2','Joy_Button_Y','Joy_Button_X','Joy_Button_A','Joy_Button_B','Joy_Button_LB','Joy_Button_RB','Joy_Button_STICK_LEFT','Joy_Button_STICK_RIGHT','Reset_pwm']
  _slot_types = ['uint8[4]','uint8[4]','uint8[4]','uint8[4]','uint8[4]','uint8[4]','uint8[4]','uint8[4]','uint8[4]','uint8[4]','uint8[4]','uint8[4]','uint8[4]','uint8[4]','uint8[4]','uint8[4]','uint8[4]','uint8[4]','int16[4]','int16[4]','int16[4]','int16[4]','int16[4]','int16[4]','int16[4]','int16[4]','int16[4]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       Ctrl_vel_X,Ctrl_vel_Y,Ctrl_vel_Z,Ctrl_fixed_Z,Ctrl_vel_Rol,Ctrl_vel_Pit,Ctrl_vel_Yaw,Ctrl_fixed_Yaw,Ctrl_pivot_1,Ctrl_pivot_2,Ctrl_pivot_3,Ctrl_pivot_4,Ctrl_emagnet_1,Ctrl_emagnet_2,Ctrl_emagnet_3,Ctrl_emagnet_4,Ctrl_arm_joint_1,Ctrl_arm_joint_2,Joy_Button_Y,Joy_Button_X,Joy_Button_A,Joy_Button_B,Joy_Button_LB,Joy_Button_RB,Joy_Button_STICK_LEFT,Joy_Button_STICK_RIGHT,Reset_pwm

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Ctrl_cmd, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.Ctrl_vel_X is None:
        self.Ctrl_vel_X = b'\0'*4
      if self.Ctrl_vel_Y is None:
        self.Ctrl_vel_Y = b'\0'*4
      if self.Ctrl_vel_Z is None:
        self.Ctrl_vel_Z = b'\0'*4
      if self.Ctrl_fixed_Z is None:
        self.Ctrl_fixed_Z = b'\0'*4
      if self.Ctrl_vel_Rol is None:
        self.Ctrl_vel_Rol = b'\0'*4
      if self.Ctrl_vel_Pit is None:
        self.Ctrl_vel_Pit = b'\0'*4
      if self.Ctrl_vel_Yaw is None:
        self.Ctrl_vel_Yaw = b'\0'*4
      if self.Ctrl_fixed_Yaw is None:
        self.Ctrl_fixed_Yaw = b'\0'*4
      if self.Ctrl_pivot_1 is None:
        self.Ctrl_pivot_1 = b'\0'*4
      if self.Ctrl_pivot_2 is None:
        self.Ctrl_pivot_2 = b'\0'*4
      if self.Ctrl_pivot_3 is None:
        self.Ctrl_pivot_3 = b'\0'*4
      if self.Ctrl_pivot_4 is None:
        self.Ctrl_pivot_4 = b'\0'*4
      if self.Ctrl_emagnet_1 is None:
        self.Ctrl_emagnet_1 = b'\0'*4
      if self.Ctrl_emagnet_2 is None:
        self.Ctrl_emagnet_2 = b'\0'*4
      if self.Ctrl_emagnet_3 is None:
        self.Ctrl_emagnet_3 = b'\0'*4
      if self.Ctrl_emagnet_4 is None:
        self.Ctrl_emagnet_4 = b'\0'*4
      if self.Ctrl_arm_joint_1 is None:
        self.Ctrl_arm_joint_1 = b'\0'*4
      if self.Ctrl_arm_joint_2 is None:
        self.Ctrl_arm_joint_2 = b'\0'*4
      if self.Joy_Button_Y is None:
        self.Joy_Button_Y = [0] * 4
      if self.Joy_Button_X is None:
        self.Joy_Button_X = [0] * 4
      if self.Joy_Button_A is None:
        self.Joy_Button_A = [0] * 4
      if self.Joy_Button_B is None:
        self.Joy_Button_B = [0] * 4
      if self.Joy_Button_LB is None:
        self.Joy_Button_LB = [0] * 4
      if self.Joy_Button_RB is None:
        self.Joy_Button_RB = [0] * 4
      if self.Joy_Button_STICK_LEFT is None:
        self.Joy_Button_STICK_LEFT = [0] * 4
      if self.Joy_Button_STICK_RIGHT is None:
        self.Joy_Button_STICK_RIGHT = [0] * 4
      if self.Reset_pwm is None:
        self.Reset_pwm = [0] * 4
    else:
      self.Ctrl_vel_X = b'\0'*4
      self.Ctrl_vel_Y = b'\0'*4
      self.Ctrl_vel_Z = b'\0'*4
      self.Ctrl_fixed_Z = b'\0'*4
      self.Ctrl_vel_Rol = b'\0'*4
      self.Ctrl_vel_Pit = b'\0'*4
      self.Ctrl_vel_Yaw = b'\0'*4
      self.Ctrl_fixed_Yaw = b'\0'*4
      self.Ctrl_pivot_1 = b'\0'*4
      self.Ctrl_pivot_2 = b'\0'*4
      self.Ctrl_pivot_3 = b'\0'*4
      self.Ctrl_pivot_4 = b'\0'*4
      self.Ctrl_emagnet_1 = b'\0'*4
      self.Ctrl_emagnet_2 = b'\0'*4
      self.Ctrl_emagnet_3 = b'\0'*4
      self.Ctrl_emagnet_4 = b'\0'*4
      self.Ctrl_arm_joint_1 = b'\0'*4
      self.Ctrl_arm_joint_2 = b'\0'*4
      self.Joy_Button_Y = [0] * 4
      self.Joy_Button_X = [0] * 4
      self.Joy_Button_A = [0] * 4
      self.Joy_Button_B = [0] * 4
      self.Joy_Button_LB = [0] * 4
      self.Joy_Button_RB = [0] * 4
      self.Joy_Button_STICK_LEFT = [0] * 4
      self.Joy_Button_STICK_RIGHT = [0] * 4
      self.Reset_pwm = [0] * 4

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.Ctrl_vel_X
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(_get_struct_4B().pack(*_x))
      else:
        buff.write(_get_struct_4s().pack(_x))
      _x = self.Ctrl_vel_Y
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(_get_struct_4B().pack(*_x))
      else:
        buff.write(_get_struct_4s().pack(_x))
      _x = self.Ctrl_vel_Z
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(_get_struct_4B().pack(*_x))
      else:
        buff.write(_get_struct_4s().pack(_x))
      _x = self.Ctrl_fixed_Z
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(_get_struct_4B().pack(*_x))
      else:
        buff.write(_get_struct_4s().pack(_x))
      _x = self.Ctrl_vel_Rol
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(_get_struct_4B().pack(*_x))
      else:
        buff.write(_get_struct_4s().pack(_x))
      _x = self.Ctrl_vel_Pit
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(_get_struct_4B().pack(*_x))
      else:
        buff.write(_get_struct_4s().pack(_x))
      _x = self.Ctrl_vel_Yaw
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(_get_struct_4B().pack(*_x))
      else:
        buff.write(_get_struct_4s().pack(_x))
      _x = self.Ctrl_fixed_Yaw
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(_get_struct_4B().pack(*_x))
      else:
        buff.write(_get_struct_4s().pack(_x))
      _x = self.Ctrl_pivot_1
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(_get_struct_4B().pack(*_x))
      else:
        buff.write(_get_struct_4s().pack(_x))
      _x = self.Ctrl_pivot_2
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(_get_struct_4B().pack(*_x))
      else:
        buff.write(_get_struct_4s().pack(_x))
      _x = self.Ctrl_pivot_3
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(_get_struct_4B().pack(*_x))
      else:
        buff.write(_get_struct_4s().pack(_x))
      _x = self.Ctrl_pivot_4
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(_get_struct_4B().pack(*_x))
      else:
        buff.write(_get_struct_4s().pack(_x))
      _x = self.Ctrl_emagnet_1
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(_get_struct_4B().pack(*_x))
      else:
        buff.write(_get_struct_4s().pack(_x))
      _x = self.Ctrl_emagnet_2
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(_get_struct_4B().pack(*_x))
      else:
        buff.write(_get_struct_4s().pack(_x))
      _x = self.Ctrl_emagnet_3
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(_get_struct_4B().pack(*_x))
      else:
        buff.write(_get_struct_4s().pack(_x))
      _x = self.Ctrl_emagnet_4
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(_get_struct_4B().pack(*_x))
      else:
        buff.write(_get_struct_4s().pack(_x))
      _x = self.Ctrl_arm_joint_1
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(_get_struct_4B().pack(*_x))
      else:
        buff.write(_get_struct_4s().pack(_x))
      _x = self.Ctrl_arm_joint_2
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(_get_struct_4B().pack(*_x))
      else:
        buff.write(_get_struct_4s().pack(_x))
      buff.write(_get_struct_4h().pack(*self.Joy_Button_Y))
      buff.write(_get_struct_4h().pack(*self.Joy_Button_X))
      buff.write(_get_struct_4h().pack(*self.Joy_Button_A))
      buff.write(_get_struct_4h().pack(*self.Joy_Button_B))
      buff.write(_get_struct_4h().pack(*self.Joy_Button_LB))
      buff.write(_get_struct_4h().pack(*self.Joy_Button_RB))
      buff.write(_get_struct_4h().pack(*self.Joy_Button_STICK_LEFT))
      buff.write(_get_struct_4h().pack(*self.Joy_Button_STICK_RIGHT))
      buff.write(_get_struct_4h().pack(*self.Reset_pwm))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 4
      self.Ctrl_vel_X = str[start:end]
      start = end
      end += 4
      self.Ctrl_vel_Y = str[start:end]
      start = end
      end += 4
      self.Ctrl_vel_Z = str[start:end]
      start = end
      end += 4
      self.Ctrl_fixed_Z = str[start:end]
      start = end
      end += 4
      self.Ctrl_vel_Rol = str[start:end]
      start = end
      end += 4
      self.Ctrl_vel_Pit = str[start:end]
      start = end
      end += 4
      self.Ctrl_vel_Yaw = str[start:end]
      start = end
      end += 4
      self.Ctrl_fixed_Yaw = str[start:end]
      start = end
      end += 4
      self.Ctrl_pivot_1 = str[start:end]
      start = end
      end += 4
      self.Ctrl_pivot_2 = str[start:end]
      start = end
      end += 4
      self.Ctrl_pivot_3 = str[start:end]
      start = end
      end += 4
      self.Ctrl_pivot_4 = str[start:end]
      start = end
      end += 4
      self.Ctrl_emagnet_1 = str[start:end]
      start = end
      end += 4
      self.Ctrl_emagnet_2 = str[start:end]
      start = end
      end += 4
      self.Ctrl_emagnet_3 = str[start:end]
      start = end
      end += 4
      self.Ctrl_emagnet_4 = str[start:end]
      start = end
      end += 4
      self.Ctrl_arm_joint_1 = str[start:end]
      start = end
      end += 4
      self.Ctrl_arm_joint_2 = str[start:end]
      start = end
      end += 8
      self.Joy_Button_Y = _get_struct_4h().unpack(str[start:end])
      start = end
      end += 8
      self.Joy_Button_X = _get_struct_4h().unpack(str[start:end])
      start = end
      end += 8
      self.Joy_Button_A = _get_struct_4h().unpack(str[start:end])
      start = end
      end += 8
      self.Joy_Button_B = _get_struct_4h().unpack(str[start:end])
      start = end
      end += 8
      self.Joy_Button_LB = _get_struct_4h().unpack(str[start:end])
      start = end
      end += 8
      self.Joy_Button_RB = _get_struct_4h().unpack(str[start:end])
      start = end
      end += 8
      self.Joy_Button_STICK_LEFT = _get_struct_4h().unpack(str[start:end])
      start = end
      end += 8
      self.Joy_Button_STICK_RIGHT = _get_struct_4h().unpack(str[start:end])
      start = end
      end += 8
      self.Reset_pwm = _get_struct_4h().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.Ctrl_vel_X
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(_get_struct_4B().pack(*_x))
      else:
        buff.write(_get_struct_4s().pack(_x))
      _x = self.Ctrl_vel_Y
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(_get_struct_4B().pack(*_x))
      else:
        buff.write(_get_struct_4s().pack(_x))
      _x = self.Ctrl_vel_Z
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(_get_struct_4B().pack(*_x))
      else:
        buff.write(_get_struct_4s().pack(_x))
      _x = self.Ctrl_fixed_Z
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(_get_struct_4B().pack(*_x))
      else:
        buff.write(_get_struct_4s().pack(_x))
      _x = self.Ctrl_vel_Rol
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(_get_struct_4B().pack(*_x))
      else:
        buff.write(_get_struct_4s().pack(_x))
      _x = self.Ctrl_vel_Pit
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(_get_struct_4B().pack(*_x))
      else:
        buff.write(_get_struct_4s().pack(_x))
      _x = self.Ctrl_vel_Yaw
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(_get_struct_4B().pack(*_x))
      else:
        buff.write(_get_struct_4s().pack(_x))
      _x = self.Ctrl_fixed_Yaw
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(_get_struct_4B().pack(*_x))
      else:
        buff.write(_get_struct_4s().pack(_x))
      _x = self.Ctrl_pivot_1
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(_get_struct_4B().pack(*_x))
      else:
        buff.write(_get_struct_4s().pack(_x))
      _x = self.Ctrl_pivot_2
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(_get_struct_4B().pack(*_x))
      else:
        buff.write(_get_struct_4s().pack(_x))
      _x = self.Ctrl_pivot_3
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(_get_struct_4B().pack(*_x))
      else:
        buff.write(_get_struct_4s().pack(_x))
      _x = self.Ctrl_pivot_4
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(_get_struct_4B().pack(*_x))
      else:
        buff.write(_get_struct_4s().pack(_x))
      _x = self.Ctrl_emagnet_1
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(_get_struct_4B().pack(*_x))
      else:
        buff.write(_get_struct_4s().pack(_x))
      _x = self.Ctrl_emagnet_2
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(_get_struct_4B().pack(*_x))
      else:
        buff.write(_get_struct_4s().pack(_x))
      _x = self.Ctrl_emagnet_3
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(_get_struct_4B().pack(*_x))
      else:
        buff.write(_get_struct_4s().pack(_x))
      _x = self.Ctrl_emagnet_4
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(_get_struct_4B().pack(*_x))
      else:
        buff.write(_get_struct_4s().pack(_x))
      _x = self.Ctrl_arm_joint_1
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(_get_struct_4B().pack(*_x))
      else:
        buff.write(_get_struct_4s().pack(_x))
      _x = self.Ctrl_arm_joint_2
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(_get_struct_4B().pack(*_x))
      else:
        buff.write(_get_struct_4s().pack(_x))
      buff.write(self.Joy_Button_Y.tostring())
      buff.write(self.Joy_Button_X.tostring())
      buff.write(self.Joy_Button_A.tostring())
      buff.write(self.Joy_Button_B.tostring())
      buff.write(self.Joy_Button_LB.tostring())
      buff.write(self.Joy_Button_RB.tostring())
      buff.write(self.Joy_Button_STICK_LEFT.tostring())
      buff.write(self.Joy_Button_STICK_RIGHT.tostring())
      buff.write(self.Reset_pwm.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 4
      self.Ctrl_vel_X = str[start:end]
      start = end
      end += 4
      self.Ctrl_vel_Y = str[start:end]
      start = end
      end += 4
      self.Ctrl_vel_Z = str[start:end]
      start = end
      end += 4
      self.Ctrl_fixed_Z = str[start:end]
      start = end
      end += 4
      self.Ctrl_vel_Rol = str[start:end]
      start = end
      end += 4
      self.Ctrl_vel_Pit = str[start:end]
      start = end
      end += 4
      self.Ctrl_vel_Yaw = str[start:end]
      start = end
      end += 4
      self.Ctrl_fixed_Yaw = str[start:end]
      start = end
      end += 4
      self.Ctrl_pivot_1 = str[start:end]
      start = end
      end += 4
      self.Ctrl_pivot_2 = str[start:end]
      start = end
      end += 4
      self.Ctrl_pivot_3 = str[start:end]
      start = end
      end += 4
      self.Ctrl_pivot_4 = str[start:end]
      start = end
      end += 4
      self.Ctrl_emagnet_1 = str[start:end]
      start = end
      end += 4
      self.Ctrl_emagnet_2 = str[start:end]
      start = end
      end += 4
      self.Ctrl_emagnet_3 = str[start:end]
      start = end
      end += 4
      self.Ctrl_emagnet_4 = str[start:end]
      start = end
      end += 4
      self.Ctrl_arm_joint_1 = str[start:end]
      start = end
      end += 4
      self.Ctrl_arm_joint_2 = str[start:end]
      start = end
      end += 8
      self.Joy_Button_Y = numpy.frombuffer(str[start:end], dtype=numpy.int16, count=4)
      start = end
      end += 8
      self.Joy_Button_X = numpy.frombuffer(str[start:end], dtype=numpy.int16, count=4)
      start = end
      end += 8
      self.Joy_Button_A = numpy.frombuffer(str[start:end], dtype=numpy.int16, count=4)
      start = end
      end += 8
      self.Joy_Button_B = numpy.frombuffer(str[start:end], dtype=numpy.int16, count=4)
      start = end
      end += 8
      self.Joy_Button_LB = numpy.frombuffer(str[start:end], dtype=numpy.int16, count=4)
      start = end
      end += 8
      self.Joy_Button_RB = numpy.frombuffer(str[start:end], dtype=numpy.int16, count=4)
      start = end
      end += 8
      self.Joy_Button_STICK_LEFT = numpy.frombuffer(str[start:end], dtype=numpy.int16, count=4)
      start = end
      end += 8
      self.Joy_Button_STICK_RIGHT = numpy.frombuffer(str[start:end], dtype=numpy.int16, count=4)
      start = end
      end += 8
      self.Reset_pwm = numpy.frombuffer(str[start:end], dtype=numpy.int16, count=4)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_4B = None
def _get_struct_4B():
    global _struct_4B
    if _struct_4B is None:
        _struct_4B = struct.Struct("<4B")
    return _struct_4B
_struct_4h = None
def _get_struct_4h():
    global _struct_4h
    if _struct_4h is None:
        _struct_4h = struct.Struct("<4h")
    return _struct_4h
_struct_4s = None
def _get_struct_4s():
    global _struct_4s
    if _struct_4s is None:
        _struct_4s = struct.Struct("<4s")
    return _struct_4s
