# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from tauv_msgs/DynamicsParametersEstimate.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import genpy

class DynamicsParametersEstimate(genpy.Message):
  _md5sum = "bd252a6b82405355d619dce17f3eaa07"
  _type = "tauv_msgs/DynamicsParametersEstimate"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """time stamp

float64 m
float64 cov_m
float64 v
float64 cov_v
float64[3] g
float64[3] cov_g
float64[3] b
float64[3] cov_b
float64[6] I
float64[6] cov_I
float64[6] dl
float64[6] cov_dl
float64[6] dq
float64[6] cov_dq
float64[6] am
float64[6] cov_am"""
  __slots__ = ['stamp','m','cov_m','v','cov_v','g','cov_g','b','cov_b','I','cov_I','dl','cov_dl','dq','cov_dq','am','cov_am']
  _slot_types = ['time','float64','float64','float64','float64','float64[3]','float64[3]','float64[3]','float64[3]','float64[6]','float64[6]','float64[6]','float64[6]','float64[6]','float64[6]','float64[6]','float64[6]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       stamp,m,cov_m,v,cov_v,g,cov_g,b,cov_b,I,cov_I,dl,cov_dl,dq,cov_dq,am,cov_am

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(DynamicsParametersEstimate, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.stamp is None:
        self.stamp = genpy.Time()
      if self.m is None:
        self.m = 0.
      if self.cov_m is None:
        self.cov_m = 0.
      if self.v is None:
        self.v = 0.
      if self.cov_v is None:
        self.cov_v = 0.
      if self.g is None:
        self.g = [0.] * 3
      if self.cov_g is None:
        self.cov_g = [0.] * 3
      if self.b is None:
        self.b = [0.] * 3
      if self.cov_b is None:
        self.cov_b = [0.] * 3
      if self.I is None:
        self.I = [0.] * 6
      if self.cov_I is None:
        self.cov_I = [0.] * 6
      if self.dl is None:
        self.dl = [0.] * 6
      if self.cov_dl is None:
        self.cov_dl = [0.] * 6
      if self.dq is None:
        self.dq = [0.] * 6
      if self.cov_dq is None:
        self.cov_dq = [0.] * 6
      if self.am is None:
        self.am = [0.] * 6
      if self.cov_am is None:
        self.cov_am = [0.] * 6
    else:
      self.stamp = genpy.Time()
      self.m = 0.
      self.cov_m = 0.
      self.v = 0.
      self.cov_v = 0.
      self.g = [0.] * 3
      self.cov_g = [0.] * 3
      self.b = [0.] * 3
      self.cov_b = [0.] * 3
      self.I = [0.] * 6
      self.cov_I = [0.] * 6
      self.dl = [0.] * 6
      self.cov_dl = [0.] * 6
      self.dq = [0.] * 6
      self.cov_dq = [0.] * 6
      self.am = [0.] * 6
      self.cov_am = [0.] * 6

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2I4d().pack(_x.stamp.secs, _x.stamp.nsecs, _x.m, _x.cov_m, _x.v, _x.cov_v))
      buff.write(_get_struct_3d().pack(*self.g))
      buff.write(_get_struct_3d().pack(*self.cov_g))
      buff.write(_get_struct_3d().pack(*self.b))
      buff.write(_get_struct_3d().pack(*self.cov_b))
      buff.write(_get_struct_6d().pack(*self.I))
      buff.write(_get_struct_6d().pack(*self.cov_I))
      buff.write(_get_struct_6d().pack(*self.dl))
      buff.write(_get_struct_6d().pack(*self.cov_dl))
      buff.write(_get_struct_6d().pack(*self.dq))
      buff.write(_get_struct_6d().pack(*self.cov_dq))
      buff.write(_get_struct_6d().pack(*self.am))
      buff.write(_get_struct_6d().pack(*self.cov_am))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.stamp is None:
        self.stamp = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 40
      (_x.stamp.secs, _x.stamp.nsecs, _x.m, _x.cov_m, _x.v, _x.cov_v,) = _get_struct_2I4d().unpack(str[start:end])
      start = end
      end += 24
      self.g = _get_struct_3d().unpack(str[start:end])
      start = end
      end += 24
      self.cov_g = _get_struct_3d().unpack(str[start:end])
      start = end
      end += 24
      self.b = _get_struct_3d().unpack(str[start:end])
      start = end
      end += 24
      self.cov_b = _get_struct_3d().unpack(str[start:end])
      start = end
      end += 48
      self.I = _get_struct_6d().unpack(str[start:end])
      start = end
      end += 48
      self.cov_I = _get_struct_6d().unpack(str[start:end])
      start = end
      end += 48
      self.dl = _get_struct_6d().unpack(str[start:end])
      start = end
      end += 48
      self.cov_dl = _get_struct_6d().unpack(str[start:end])
      start = end
      end += 48
      self.dq = _get_struct_6d().unpack(str[start:end])
      start = end
      end += 48
      self.cov_dq = _get_struct_6d().unpack(str[start:end])
      start = end
      end += 48
      self.am = _get_struct_6d().unpack(str[start:end])
      start = end
      end += 48
      self.cov_am = _get_struct_6d().unpack(str[start:end])
      self.stamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2I4d().pack(_x.stamp.secs, _x.stamp.nsecs, _x.m, _x.cov_m, _x.v, _x.cov_v))
      buff.write(self.g.tostring())
      buff.write(self.cov_g.tostring())
      buff.write(self.b.tostring())
      buff.write(self.cov_b.tostring())
      buff.write(self.I.tostring())
      buff.write(self.cov_I.tostring())
      buff.write(self.dl.tostring())
      buff.write(self.cov_dl.tostring())
      buff.write(self.dq.tostring())
      buff.write(self.cov_dq.tostring())
      buff.write(self.am.tostring())
      buff.write(self.cov_am.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.stamp is None:
        self.stamp = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 40
      (_x.stamp.secs, _x.stamp.nsecs, _x.m, _x.cov_m, _x.v, _x.cov_v,) = _get_struct_2I4d().unpack(str[start:end])
      start = end
      end += 24
      self.g = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=3)
      start = end
      end += 24
      self.cov_g = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=3)
      start = end
      end += 24
      self.b = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=3)
      start = end
      end += 24
      self.cov_b = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=3)
      start = end
      end += 48
      self.I = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=6)
      start = end
      end += 48
      self.cov_I = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=6)
      start = end
      end += 48
      self.dl = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=6)
      start = end
      end += 48
      self.cov_dl = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=6)
      start = end
      end += 48
      self.dq = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=6)
      start = end
      end += 48
      self.cov_dq = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=6)
      start = end
      end += 48
      self.am = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=6)
      start = end
      end += 48
      self.cov_am = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=6)
      self.stamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2I4d = None
def _get_struct_2I4d():
    global _struct_2I4d
    if _struct_2I4d is None:
        _struct_2I4d = struct.Struct("<2I4d")
    return _struct_2I4d
_struct_3d = None
def _get_struct_3d():
    global _struct_3d
    if _struct_3d is None:
        _struct_3d = struct.Struct("<3d")
    return _struct_3d
_struct_6d = None
def _get_struct_6d():
    global _struct_6d
    if _struct_6d is None:
        _struct_6d = struct.Struct("<6d")
    return _struct_6d
