# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from tauv_msgs/DynamicsParameterConfigUpdate.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class DynamicsParameterConfigUpdate(genpy.Message):
  _md5sum = "31294fd8c67bf91ba516e5502711b385"
  _type = "tauv_msgs/DynamicsParameterConfigUpdate"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """string name

bool update_initial_value
float64 initial_value

bool update_fixed
bool fixed

bool update_initial_covariance
float64 initial_covariance

bool update_process_covariance
float64 process_covariance

bool update_limits
float64[2] limits

bool reset


"""
  __slots__ = ['name','update_initial_value','initial_value','update_fixed','fixed','update_initial_covariance','initial_covariance','update_process_covariance','process_covariance','update_limits','limits','reset']
  _slot_types = ['string','bool','float64','bool','bool','bool','float64','bool','float64','bool','float64[2]','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       name,update_initial_value,initial_value,update_fixed,fixed,update_initial_covariance,initial_covariance,update_process_covariance,process_covariance,update_limits,limits,reset

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(DynamicsParameterConfigUpdate, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.name is None:
        self.name = ''
      if self.update_initial_value is None:
        self.update_initial_value = False
      if self.initial_value is None:
        self.initial_value = 0.
      if self.update_fixed is None:
        self.update_fixed = False
      if self.fixed is None:
        self.fixed = False
      if self.update_initial_covariance is None:
        self.update_initial_covariance = False
      if self.initial_covariance is None:
        self.initial_covariance = 0.
      if self.update_process_covariance is None:
        self.update_process_covariance = False
      if self.process_covariance is None:
        self.process_covariance = 0.
      if self.update_limits is None:
        self.update_limits = False
      if self.limits is None:
        self.limits = [0.] * 2
      if self.reset is None:
        self.reset = False
    else:
      self.name = ''
      self.update_initial_value = False
      self.initial_value = 0.
      self.update_fixed = False
      self.fixed = False
      self.update_initial_covariance = False
      self.initial_covariance = 0.
      self.update_process_covariance = False
      self.process_covariance = 0.
      self.update_limits = False
      self.limits = [0.] * 2
      self.reset = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_Bd3BdBdB().pack(_x.update_initial_value, _x.initial_value, _x.update_fixed, _x.fixed, _x.update_initial_covariance, _x.initial_covariance, _x.update_process_covariance, _x.process_covariance, _x.update_limits))
      buff.write(_get_struct_2d().pack(*self.limits))
      _x = self.reset
      buff.write(_get_struct_B().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.name = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.name = str[start:end]
      _x = self
      start = end
      end += 30
      (_x.update_initial_value, _x.initial_value, _x.update_fixed, _x.fixed, _x.update_initial_covariance, _x.initial_covariance, _x.update_process_covariance, _x.process_covariance, _x.update_limits,) = _get_struct_Bd3BdBdB().unpack(str[start:end])
      self.update_initial_value = bool(self.update_initial_value)
      self.update_fixed = bool(self.update_fixed)
      self.fixed = bool(self.fixed)
      self.update_initial_covariance = bool(self.update_initial_covariance)
      self.update_process_covariance = bool(self.update_process_covariance)
      self.update_limits = bool(self.update_limits)
      start = end
      end += 16
      self.limits = _get_struct_2d().unpack(str[start:end])
      start = end
      end += 1
      (self.reset,) = _get_struct_B().unpack(str[start:end])
      self.reset = bool(self.reset)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_Bd3BdBdB().pack(_x.update_initial_value, _x.initial_value, _x.update_fixed, _x.fixed, _x.update_initial_covariance, _x.initial_covariance, _x.update_process_covariance, _x.process_covariance, _x.update_limits))
      buff.write(self.limits.tostring())
      _x = self.reset
      buff.write(_get_struct_B().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.name = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.name = str[start:end]
      _x = self
      start = end
      end += 30
      (_x.update_initial_value, _x.initial_value, _x.update_fixed, _x.fixed, _x.update_initial_covariance, _x.initial_covariance, _x.update_process_covariance, _x.process_covariance, _x.update_limits,) = _get_struct_Bd3BdBdB().unpack(str[start:end])
      self.update_initial_value = bool(self.update_initial_value)
      self.update_fixed = bool(self.update_fixed)
      self.fixed = bool(self.fixed)
      self.update_initial_covariance = bool(self.update_initial_covariance)
      self.update_process_covariance = bool(self.update_process_covariance)
      self.update_limits = bool(self.update_limits)
      start = end
      end += 16
      self.limits = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=2)
      start = end
      end += 1
      (self.reset,) = _get_struct_B().unpack(str[start:end])
      self.reset = bool(self.reset)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2d = None
def _get_struct_2d():
    global _struct_2d
    if _struct_2d is None:
        _struct_2d = struct.Struct("<2d")
    return _struct_2d
_struct_B = None
def _get_struct_B():
    global _struct_B
    if _struct_B is None:
        _struct_B = struct.Struct("<B")
    return _struct_B
_struct_Bd3BdBdB = None
def _get_struct_Bd3BdBdB():
    global _struct_Bd3BdBdB
    if _struct_Bd3BdBdB is None:
        _struct_Bd3BdBdB = struct.Struct("<Bd3BdBdB")
    return _struct_Bd3BdBdB
