# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from tauv_msgs/DynamicsTuning.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class DynamicsTuning(genpy.Message):
  _md5sum = "1657e74b53352c5e93a01a5d1743eeaa"
  _type = "tauv_msgs/DynamicsTuning"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """bool update_mass
float64 mass
bool update_volume
float64 volume
bool update_water_density
float64 water_density
bool update_center_of_gravity
float64[3] center_of_gravity
bool update_center_of_buoyancy
float64[3] center_of_buoyancy
bool update_moments
float64[6] moments
bool update_linear_damping
float64[6] linear_damping
bool update_quadratic_damping
float64[6] quadratic_damping
bool update_added_mass
float64[6] added_mass"""
  __slots__ = ['update_mass','mass','update_volume','volume','update_water_density','water_density','update_center_of_gravity','center_of_gravity','update_center_of_buoyancy','center_of_buoyancy','update_moments','moments','update_linear_damping','linear_damping','update_quadratic_damping','quadratic_damping','update_added_mass','added_mass']
  _slot_types = ['bool','float64','bool','float64','bool','float64','bool','float64[3]','bool','float64[3]','bool','float64[6]','bool','float64[6]','bool','float64[6]','bool','float64[6]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       update_mass,mass,update_volume,volume,update_water_density,water_density,update_center_of_gravity,center_of_gravity,update_center_of_buoyancy,center_of_buoyancy,update_moments,moments,update_linear_damping,linear_damping,update_quadratic_damping,quadratic_damping,update_added_mass,added_mass

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(DynamicsTuning, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.update_mass is None:
        self.update_mass = False
      if self.mass is None:
        self.mass = 0.
      if self.update_volume is None:
        self.update_volume = False
      if self.volume is None:
        self.volume = 0.
      if self.update_water_density is None:
        self.update_water_density = False
      if self.water_density is None:
        self.water_density = 0.
      if self.update_center_of_gravity is None:
        self.update_center_of_gravity = False
      if self.center_of_gravity is None:
        self.center_of_gravity = [0.] * 3
      if self.update_center_of_buoyancy is None:
        self.update_center_of_buoyancy = False
      if self.center_of_buoyancy is None:
        self.center_of_buoyancy = [0.] * 3
      if self.update_moments is None:
        self.update_moments = False
      if self.moments is None:
        self.moments = [0.] * 6
      if self.update_linear_damping is None:
        self.update_linear_damping = False
      if self.linear_damping is None:
        self.linear_damping = [0.] * 6
      if self.update_quadratic_damping is None:
        self.update_quadratic_damping = False
      if self.quadratic_damping is None:
        self.quadratic_damping = [0.] * 6
      if self.update_added_mass is None:
        self.update_added_mass = False
      if self.added_mass is None:
        self.added_mass = [0.] * 6
    else:
      self.update_mass = False
      self.mass = 0.
      self.update_volume = False
      self.volume = 0.
      self.update_water_density = False
      self.water_density = 0.
      self.update_center_of_gravity = False
      self.center_of_gravity = [0.] * 3
      self.update_center_of_buoyancy = False
      self.center_of_buoyancy = [0.] * 3
      self.update_moments = False
      self.moments = [0.] * 6
      self.update_linear_damping = False
      self.linear_damping = [0.] * 6
      self.update_quadratic_damping = False
      self.quadratic_damping = [0.] * 6
      self.update_added_mass = False
      self.added_mass = [0.] * 6

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_BdBdBdB().pack(_x.update_mass, _x.mass, _x.update_volume, _x.volume, _x.update_water_density, _x.water_density, _x.update_center_of_gravity))
      buff.write(_get_struct_3d().pack(*self.center_of_gravity))
      _x = self.update_center_of_buoyancy
      buff.write(_get_struct_B().pack(_x))
      buff.write(_get_struct_3d().pack(*self.center_of_buoyancy))
      _x = self.update_moments
      buff.write(_get_struct_B().pack(_x))
      buff.write(_get_struct_6d().pack(*self.moments))
      _x = self.update_linear_damping
      buff.write(_get_struct_B().pack(_x))
      buff.write(_get_struct_6d().pack(*self.linear_damping))
      _x = self.update_quadratic_damping
      buff.write(_get_struct_B().pack(_x))
      buff.write(_get_struct_6d().pack(*self.quadratic_damping))
      _x = self.update_added_mass
      buff.write(_get_struct_B().pack(_x))
      buff.write(_get_struct_6d().pack(*self.added_mass))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 28
      (_x.update_mass, _x.mass, _x.update_volume, _x.volume, _x.update_water_density, _x.water_density, _x.update_center_of_gravity,) = _get_struct_BdBdBdB().unpack(str[start:end])
      self.update_mass = bool(self.update_mass)
      self.update_volume = bool(self.update_volume)
      self.update_water_density = bool(self.update_water_density)
      self.update_center_of_gravity = bool(self.update_center_of_gravity)
      start = end
      end += 24
      self.center_of_gravity = _get_struct_3d().unpack(str[start:end])
      start = end
      end += 1
      (self.update_center_of_buoyancy,) = _get_struct_B().unpack(str[start:end])
      self.update_center_of_buoyancy = bool(self.update_center_of_buoyancy)
      start = end
      end += 24
      self.center_of_buoyancy = _get_struct_3d().unpack(str[start:end])
      start = end
      end += 1
      (self.update_moments,) = _get_struct_B().unpack(str[start:end])
      self.update_moments = bool(self.update_moments)
      start = end
      end += 48
      self.moments = _get_struct_6d().unpack(str[start:end])
      start = end
      end += 1
      (self.update_linear_damping,) = _get_struct_B().unpack(str[start:end])
      self.update_linear_damping = bool(self.update_linear_damping)
      start = end
      end += 48
      self.linear_damping = _get_struct_6d().unpack(str[start:end])
      start = end
      end += 1
      (self.update_quadratic_damping,) = _get_struct_B().unpack(str[start:end])
      self.update_quadratic_damping = bool(self.update_quadratic_damping)
      start = end
      end += 48
      self.quadratic_damping = _get_struct_6d().unpack(str[start:end])
      start = end
      end += 1
      (self.update_added_mass,) = _get_struct_B().unpack(str[start:end])
      self.update_added_mass = bool(self.update_added_mass)
      start = end
      end += 48
      self.added_mass = _get_struct_6d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_BdBdBdB().pack(_x.update_mass, _x.mass, _x.update_volume, _x.volume, _x.update_water_density, _x.water_density, _x.update_center_of_gravity))
      buff.write(self.center_of_gravity.tostring())
      _x = self.update_center_of_buoyancy
      buff.write(_get_struct_B().pack(_x))
      buff.write(self.center_of_buoyancy.tostring())
      _x = self.update_moments
      buff.write(_get_struct_B().pack(_x))
      buff.write(self.moments.tostring())
      _x = self.update_linear_damping
      buff.write(_get_struct_B().pack(_x))
      buff.write(self.linear_damping.tostring())
      _x = self.update_quadratic_damping
      buff.write(_get_struct_B().pack(_x))
      buff.write(self.quadratic_damping.tostring())
      _x = self.update_added_mass
      buff.write(_get_struct_B().pack(_x))
      buff.write(self.added_mass.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 28
      (_x.update_mass, _x.mass, _x.update_volume, _x.volume, _x.update_water_density, _x.water_density, _x.update_center_of_gravity,) = _get_struct_BdBdBdB().unpack(str[start:end])
      self.update_mass = bool(self.update_mass)
      self.update_volume = bool(self.update_volume)
      self.update_water_density = bool(self.update_water_density)
      self.update_center_of_gravity = bool(self.update_center_of_gravity)
      start = end
      end += 24
      self.center_of_gravity = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=3)
      start = end
      end += 1
      (self.update_center_of_buoyancy,) = _get_struct_B().unpack(str[start:end])
      self.update_center_of_buoyancy = bool(self.update_center_of_buoyancy)
      start = end
      end += 24
      self.center_of_buoyancy = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=3)
      start = end
      end += 1
      (self.update_moments,) = _get_struct_B().unpack(str[start:end])
      self.update_moments = bool(self.update_moments)
      start = end
      end += 48
      self.moments = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=6)
      start = end
      end += 1
      (self.update_linear_damping,) = _get_struct_B().unpack(str[start:end])
      self.update_linear_damping = bool(self.update_linear_damping)
      start = end
      end += 48
      self.linear_damping = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=6)
      start = end
      end += 1
      (self.update_quadratic_damping,) = _get_struct_B().unpack(str[start:end])
      self.update_quadratic_damping = bool(self.update_quadratic_damping)
      start = end
      end += 48
      self.quadratic_damping = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=6)
      start = end
      end += 1
      (self.update_added_mass,) = _get_struct_B().unpack(str[start:end])
      self.update_added_mass = bool(self.update_added_mass)
      start = end
      end += 48
      self.added_mass = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=6)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3d = None
def _get_struct_3d():
    global _struct_3d
    if _struct_3d is None:
        _struct_3d = struct.Struct("<3d")
    return _struct_3d
_struct_6d = None
def _get_struct_6d():
    global _struct_6d
    if _struct_6d is None:
        _struct_6d = struct.Struct("<6d")
    return _struct_6d
_struct_B = None
def _get_struct_B():
    global _struct_B
    if _struct_B is None:
        _struct_B = struct.Struct("<B")
    return _struct_B
_struct_BdBdBdB = None
def _get_struct_BdBdBdB():
    global _struct_BdBdBdB
    if _struct_BdBdBdB is None:
        _struct_BdBdBdB = struct.Struct("<BdBdBdB")
    return _struct_BdBdBdB
