# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from tauv_msgs/GateDetection.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg

class GateDetection(genpy.Message):
  _md5sum = "8a67a29e701c68c820bd45950230c212"
  _type = "tauv_msgs/GateDetection"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """geometry_msgs/Point leftCorner
geometry_msgs/Point rightCorner
geometry_msgs/Point centerPoint
================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z
"""
  __slots__ = ['leftCorner','rightCorner','centerPoint']
  _slot_types = ['geometry_msgs/Point','geometry_msgs/Point','geometry_msgs/Point']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       leftCorner,rightCorner,centerPoint

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(GateDetection, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.leftCorner is None:
        self.leftCorner = geometry_msgs.msg.Point()
      if self.rightCorner is None:
        self.rightCorner = geometry_msgs.msg.Point()
      if self.centerPoint is None:
        self.centerPoint = geometry_msgs.msg.Point()
    else:
      self.leftCorner = geometry_msgs.msg.Point()
      self.rightCorner = geometry_msgs.msg.Point()
      self.centerPoint = geometry_msgs.msg.Point()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_9d().pack(_x.leftCorner.x, _x.leftCorner.y, _x.leftCorner.z, _x.rightCorner.x, _x.rightCorner.y, _x.rightCorner.z, _x.centerPoint.x, _x.centerPoint.y, _x.centerPoint.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.leftCorner is None:
        self.leftCorner = geometry_msgs.msg.Point()
      if self.rightCorner is None:
        self.rightCorner = geometry_msgs.msg.Point()
      if self.centerPoint is None:
        self.centerPoint = geometry_msgs.msg.Point()
      end = 0
      _x = self
      start = end
      end += 72
      (_x.leftCorner.x, _x.leftCorner.y, _x.leftCorner.z, _x.rightCorner.x, _x.rightCorner.y, _x.rightCorner.z, _x.centerPoint.x, _x.centerPoint.y, _x.centerPoint.z,) = _get_struct_9d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_9d().pack(_x.leftCorner.x, _x.leftCorner.y, _x.leftCorner.z, _x.rightCorner.x, _x.rightCorner.y, _x.rightCorner.z, _x.centerPoint.x, _x.centerPoint.y, _x.centerPoint.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.leftCorner is None:
        self.leftCorner = geometry_msgs.msg.Point()
      if self.rightCorner is None:
        self.rightCorner = geometry_msgs.msg.Point()
      if self.centerPoint is None:
        self.centerPoint = geometry_msgs.msg.Point()
      end = 0
      _x = self
      start = end
      end += 72
      (_x.leftCorner.x, _x.leftCorner.y, _x.leftCorner.z, _x.rightCorner.x, _x.rightCorner.y, _x.rightCorner.z, _x.centerPoint.x, _x.centerPoint.y, _x.centerPoint.z,) = _get_struct_9d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_9d = None
def _get_struct_9d():
    global _struct_9d
    if _struct_9d is None:
        _struct_9d = struct.Struct("<9d")
    return _struct_9d
