# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from tauv_msgs/RegisterMeasurement.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import std_msgs.msg
import tauv_msgs.msg

class RegisterMeasurement(genpy.Message):
  _md5sum = "b355dd17bfdad2a0499de8384660e7ff"
  _type = "tauv_msgs/RegisterMeasurement"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """PoseGraphMeasurement pg_meas
================================================================================
MSG: tauv_msgs/PoseGraphMeasurement
Header header
uint32 landmark_id
geometry_msgs/Point position


================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z
"""
  __slots__ = ['pg_meas']
  _slot_types = ['tauv_msgs/PoseGraphMeasurement']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       pg_meas

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(RegisterMeasurement, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.pg_meas is None:
        self.pg_meas = tauv_msgs.msg.PoseGraphMeasurement()
    else:
      self.pg_meas = tauv_msgs.msg.PoseGraphMeasurement()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.pg_meas.header.seq, _x.pg_meas.header.stamp.secs, _x.pg_meas.header.stamp.nsecs))
      _x = self.pg_meas.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_I3d().pack(_x.pg_meas.landmark_id, _x.pg_meas.position.x, _x.pg_meas.position.y, _x.pg_meas.position.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.pg_meas is None:
        self.pg_meas = tauv_msgs.msg.PoseGraphMeasurement()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.pg_meas.header.seq, _x.pg_meas.header.stamp.secs, _x.pg_meas.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.pg_meas.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.pg_meas.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 28
      (_x.pg_meas.landmark_id, _x.pg_meas.position.x, _x.pg_meas.position.y, _x.pg_meas.position.z,) = _get_struct_I3d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.pg_meas.header.seq, _x.pg_meas.header.stamp.secs, _x.pg_meas.header.stamp.nsecs))
      _x = self.pg_meas.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_I3d().pack(_x.pg_meas.landmark_id, _x.pg_meas.position.x, _x.pg_meas.position.y, _x.pg_meas.position.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.pg_meas is None:
        self.pg_meas = tauv_msgs.msg.PoseGraphMeasurement()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.pg_meas.header.seq, _x.pg_meas.header.stamp.secs, _x.pg_meas.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.pg_meas.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.pg_meas.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 28
      (_x.pg_meas.landmark_id, _x.pg_meas.position.x, _x.pg_meas.position.y, _x.pg_meas.position.z,) = _get_struct_I3d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_I3d = None
def _get_struct_I3d():
    global _struct_I3d
    if _struct_I3d is None:
        _struct_I3d = struct.Struct("<I3d")
    return _struct_I3d
