# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from tauv_msgs/XsensImuSync.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import genpy
import std_msgs.msg

class XsensImuSync(genpy.Message):
  _md5sum = "8d95951a55cfd457da142f2cc6b05ae6"
  _type = "tauv_msgs/XsensImuSync"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """Header header

time ros_time

time imu_time

bool triggered_dvl

float64 d_corrected # optional

float64 d_ros # optional

float64 d_imu # optional

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id
"""
  __slots__ = ['header','ros_time','imu_time','triggered_dvl','d_corrected','d_ros','d_imu']
  _slot_types = ['std_msgs/Header','time','time','bool','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,ros_time,imu_time,triggered_dvl,d_corrected,d_ros,d_imu

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(XsensImuSync, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.ros_time is None:
        self.ros_time = genpy.Time()
      if self.imu_time is None:
        self.imu_time = genpy.Time()
      if self.triggered_dvl is None:
        self.triggered_dvl = False
      if self.d_corrected is None:
        self.d_corrected = 0.
      if self.d_ros is None:
        self.d_ros = 0.
      if self.d_imu is None:
        self.d_imu = 0.
    else:
      self.header = std_msgs.msg.Header()
      self.ros_time = genpy.Time()
      self.imu_time = genpy.Time()
      self.triggered_dvl = False
      self.d_corrected = 0.
      self.d_ros = 0.
      self.d_imu = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_4IB3d().pack(_x.ros_time.secs, _x.ros_time.nsecs, _x.imu_time.secs, _x.imu_time.nsecs, _x.triggered_dvl, _x.d_corrected, _x.d_ros, _x.d_imu))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.ros_time is None:
        self.ros_time = genpy.Time()
      if self.imu_time is None:
        self.imu_time = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 41
      (_x.ros_time.secs, _x.ros_time.nsecs, _x.imu_time.secs, _x.imu_time.nsecs, _x.triggered_dvl, _x.d_corrected, _x.d_ros, _x.d_imu,) = _get_struct_4IB3d().unpack(str[start:end])
      self.triggered_dvl = bool(self.triggered_dvl)
      self.ros_time.canon()
      self.imu_time.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_4IB3d().pack(_x.ros_time.secs, _x.ros_time.nsecs, _x.imu_time.secs, _x.imu_time.nsecs, _x.triggered_dvl, _x.d_corrected, _x.d_ros, _x.d_imu))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.ros_time is None:
        self.ros_time = genpy.Time()
      if self.imu_time is None:
        self.imu_time = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 41
      (_x.ros_time.secs, _x.ros_time.nsecs, _x.imu_time.secs, _x.imu_time.nsecs, _x.triggered_dvl, _x.d_corrected, _x.d_ros, _x.d_imu,) = _get_struct_4IB3d().unpack(str[start:end])
      self.triggered_dvl = bool(self.triggered_dvl)
      self.ros_time.canon()
      self.imu_time.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_4IB3d = None
def _get_struct_4IB3d():
    global _struct_4IB3d
    if _struct_4IB3d is None:
        _struct_4IB3d = struct.Struct("<4IB3d")
    return _struct_4IB3d
