# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from tauv_msgs/XsensImuData.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import genpy
import geometry_msgs.msg
import std_msgs.msg

class XsensImuData(genpy.Message):
  _md5sum = "a5e7b14c591863b869ed2281b0f6b1ed"
  _type = "tauv_msgs/XsensImuData"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """Header header

time ros_time

time imu_time

bool triggered_dvl

geometry_msgs/Vector3 orientation

geometry_msgs/Vector3 rate_of_turn

geometry_msgs/Vector3 linear_acceleration

geometry_msgs/Vector3 free_acceleration


================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z"""
  __slots__ = ['header','ros_time','imu_time','triggered_dvl','orientation','rate_of_turn','linear_acceleration','free_acceleration']
  _slot_types = ['std_msgs/Header','time','time','bool','geometry_msgs/Vector3','geometry_msgs/Vector3','geometry_msgs/Vector3','geometry_msgs/Vector3']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,ros_time,imu_time,triggered_dvl,orientation,rate_of_turn,linear_acceleration,free_acceleration

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(XsensImuData, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.ros_time is None:
        self.ros_time = genpy.Time()
      if self.imu_time is None:
        self.imu_time = genpy.Time()
      if self.triggered_dvl is None:
        self.triggered_dvl = False
      if self.orientation is None:
        self.orientation = geometry_msgs.msg.Vector3()
      if self.rate_of_turn is None:
        self.rate_of_turn = geometry_msgs.msg.Vector3()
      if self.linear_acceleration is None:
        self.linear_acceleration = geometry_msgs.msg.Vector3()
      if self.free_acceleration is None:
        self.free_acceleration = geometry_msgs.msg.Vector3()
    else:
      self.header = std_msgs.msg.Header()
      self.ros_time = genpy.Time()
      self.imu_time = genpy.Time()
      self.triggered_dvl = False
      self.orientation = geometry_msgs.msg.Vector3()
      self.rate_of_turn = geometry_msgs.msg.Vector3()
      self.linear_acceleration = geometry_msgs.msg.Vector3()
      self.free_acceleration = geometry_msgs.msg.Vector3()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_4IB12d().pack(_x.ros_time.secs, _x.ros_time.nsecs, _x.imu_time.secs, _x.imu_time.nsecs, _x.triggered_dvl, _x.orientation.x, _x.orientation.y, _x.orientation.z, _x.rate_of_turn.x, _x.rate_of_turn.y, _x.rate_of_turn.z, _x.linear_acceleration.x, _x.linear_acceleration.y, _x.linear_acceleration.z, _x.free_acceleration.x, _x.free_acceleration.y, _x.free_acceleration.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.ros_time is None:
        self.ros_time = genpy.Time()
      if self.imu_time is None:
        self.imu_time = genpy.Time()
      if self.orientation is None:
        self.orientation = geometry_msgs.msg.Vector3()
      if self.rate_of_turn is None:
        self.rate_of_turn = geometry_msgs.msg.Vector3()
      if self.linear_acceleration is None:
        self.linear_acceleration = geometry_msgs.msg.Vector3()
      if self.free_acceleration is None:
        self.free_acceleration = geometry_msgs.msg.Vector3()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 113
      (_x.ros_time.secs, _x.ros_time.nsecs, _x.imu_time.secs, _x.imu_time.nsecs, _x.triggered_dvl, _x.orientation.x, _x.orientation.y, _x.orientation.z, _x.rate_of_turn.x, _x.rate_of_turn.y, _x.rate_of_turn.z, _x.linear_acceleration.x, _x.linear_acceleration.y, _x.linear_acceleration.z, _x.free_acceleration.x, _x.free_acceleration.y, _x.free_acceleration.z,) = _get_struct_4IB12d().unpack(str[start:end])
      self.triggered_dvl = bool(self.triggered_dvl)
      self.ros_time.canon()
      self.imu_time.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_4IB12d().pack(_x.ros_time.secs, _x.ros_time.nsecs, _x.imu_time.secs, _x.imu_time.nsecs, _x.triggered_dvl, _x.orientation.x, _x.orientation.y, _x.orientation.z, _x.rate_of_turn.x, _x.rate_of_turn.y, _x.rate_of_turn.z, _x.linear_acceleration.x, _x.linear_acceleration.y, _x.linear_acceleration.z, _x.free_acceleration.x, _x.free_acceleration.y, _x.free_acceleration.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.ros_time is None:
        self.ros_time = genpy.Time()
      if self.imu_time is None:
        self.imu_time = genpy.Time()
      if self.orientation is None:
        self.orientation = geometry_msgs.msg.Vector3()
      if self.rate_of_turn is None:
        self.rate_of_turn = geometry_msgs.msg.Vector3()
      if self.linear_acceleration is None:
        self.linear_acceleration = geometry_msgs.msg.Vector3()
      if self.free_acceleration is None:
        self.free_acceleration = geometry_msgs.msg.Vector3()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 113
      (_x.ros_time.secs, _x.ros_time.nsecs, _x.imu_time.secs, _x.imu_time.nsecs, _x.triggered_dvl, _x.orientation.x, _x.orientation.y, _x.orientation.z, _x.rate_of_turn.x, _x.rate_of_turn.y, _x.rate_of_turn.z, _x.linear_acceleration.x, _x.linear_acceleration.y, _x.linear_acceleration.z, _x.free_acceleration.x, _x.free_acceleration.y, _x.free_acceleration.z,) = _get_struct_4IB12d().unpack(str[start:end])
      self.triggered_dvl = bool(self.triggered_dvl)
      self.ros_time.canon()
      self.imu_time.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_4IB12d = None
def _get_struct_4IB12d():
    global _struct_4IB12d
    if _struct_4IB12d is None:
        _struct_4IB12d = struct.Struct("<4IB12d")
    return _struct_4IB12d
