(cl:in-package tauv_msgs-msg)
(cl:export '(STAMP-VAL
          STAMP
          M-VAL
          M
          COV_M-VAL
          COV_M
          V-VAL
          V
          COV_V-VAL
          COV_V
          G-VAL
          G
          COV_G-VAL
          COV_G
          B-VAL
          B
          COV_B-VAL
          COV_B
          I-VAL
          I
          COV_I-VAL
          COV_I
          DL-VAL
          DL
          COV_DL-VAL
          COV_DL
          DQ-VAL
          DQ
          COV_DQ-VAL
          COV_DQ
          AM-VAL
          AM
          COV_AM-VAL
          COV_AM
))