(cl:in-package tauv_msgs-msg)
(cl:export '(CTRL_VEL_X-VAL
          CTRL_VEL_X
          CTRL_VEL_Y-VAL
          CTRL_VEL_Y
          CTRL_VEL_Z-VAL
          CTRL_VEL_Z
          CTRL_FIXED_Z-VAL
          CTRL_FIXED_Z
          CTRL_VEL_ROL-VAL
          CTRL_VEL_ROL
          CTRL_VEL_PIT-VAL
          CTRL_VEL_PIT
          CTRL_VEL_YAW-VAL
          CTRL_VEL_YAW
          CTRL_FIXED_YAW-VAL
          CTRL_FIXED_YAW
          CTRL_PIVOT_1-VAL
          CTRL_PIVOT_1
          CTRL_PIVOT_2-VAL
          CTRL_PIVOT_2
          CTRL_PIVOT_3-VAL
          CTRL_PIVOT_3
          CTRL_PIVOT_4-VAL
          CTRL_PIVOT_4
          CTRL_EMAGNET_1-VAL
          CTRL_EMAGNET_1
          CTRL_EMAGNET_2-VAL
          CTRL_EMAGNET_2
          CTRL_EMAGNET_3-VAL
          CTRL_EMAGNET_3
          CTRL_EMAGNET_4-VAL
          CTRL_EMAGNET_4
          CTRL_ARM_JOINT_1-VAL
          CTRL_ARM_JOINT_1
          CTRL_ARM_JOINT_2-VAL
          CTRL_ARM_JOINT_2
          JOY_BUTTON_Y-VAL
          JOY_BUTTON_Y
          JOY_BUTTON_X-VAL
          JOY_BUTTON_X
          JOY_BUTTON_A-VAL
          JOY_BUTTON_A
          JOY_BUTTON_B-VAL
          JOY_BUTTON_B
          JOY_BUTTON_LB-VAL
          JOY_BUTTON_LB
          JOY_BUTTON_RB-VAL
          JOY_BUTTON_RB
          JOY_BUTTON_STICK_LEFT-VAL
          JOY_BUTTON_STICK_LEFT
          JOY_BUTTON_STICK_RIGHT-VAL
          JOY_BUTTON_STICK_RIGHT
          RESET_PWM-VAL
          RESET_PWM
))