(cl:in-package tauv_msgs-msg)
(cl:export '(A_X-VAL
          A_X
          A_Y-VAL
          A_Y
          A_Z-VAL
          A_Z
          A_ROLL-VAL
          A_ROLL
          A_PITCH-VAL
          A_PITCH
          A_YAW-VAL
          A_YAW
          F_X-VAL
          F_X
          F_Y-VAL
          F_Y
          F_Z-VAL
          F_Z
          F_ROLL-VAL
          F_ROLL
          F_PITCH-VAL
          F_PITCH
          F_YAW-VAL
          F_YAW
          USE_F_X-VAL
          USE_F_X
          USE_F_Y-VAL
          USE_F_Y
          USE_F_Z-VAL
          USE_F_Z
          USE_F_ROLL-VAL
          USE_F_ROLL
          USE_F_PITCH-VAL
          USE_F_PITCH
          USE_F_YAW-VAL
          USE_F_YAW
          SETPOINT_Z-VAL
          SETPOINT_Z
          SETPOINT_ROLL-VAL
          SETPOINT_ROLL
          SETPOINT_PITCH-VAL
          SETPOINT_PITCH
          USE_SETPOINT_Z-VAL
          USE_SETPOINT_Z
          USE_SETPOINT_ROLL-VAL
          USE_SETPOINT_ROLL
          USE_SETPOINT_PITCH-VAL
          USE_SETPOINT_PITCH
))