(cl:in-package tauv_msgs-msg)
(cl:export '(VOLTAGE_CURRENT-VAL
          VOLTAGE_CURRENT
          TEMPERATURE_CABIN_CURRENT-VAL
          TEMPERATURE_CABIN_CURRENT
          RM_SPEED_RPM-VAL
          RM_SPEED_RPM
          RM_GIVEN_CURRENT-VAL
          RM_GIVEN_CURRENT
          RM_TOTAL_ANGLE-VAL
          RM_TOTAL_ANGLE
          FB_AUV_PIT-VAL
          FB_AUV_PIT
          FB_AUV_ROL-VAL
          FB_AUV_ROL
          FB_AUV_YAW-VAL
          FB_AUV_YAW
          FB_AUV_DEEP-VAL
          FB_AUV_DEEP
          FB_AUV_DEEP_VEL-VAL
          FB_AUV_DEEP_VEL
          FB_AUV_ANG_VEL_PIT-VAL
          FB_AUV_ANG_VEL_PIT
          FB_AUV_ANG_VEL_ROL-VAL
          FB_AUV_ANG_VEL_ROL
          FB_AUV_ANG_VEL_YAW-VAL
          FB_AUV_ANG_VEL_YAW
          PWM_SET-VAL
          PWM_SET
))