(cl:in-package tauv_msgs-msg)
(cl:export '(FAILURE_LEVEL-VAL
          FAILURE_LEVEL
          ALARMS_NO_FAILURE-VAL
          ALARMS_NO_FAILURE
          ALARMS_PREDIVE_FAILURE-VAL
          ALARMS_PREDIVE_FAILURE
          ALARMS_MISSION_FAILURE-VAL
          ALARMS_MISSION_FAILURE
          ALARMS_CRITICAL_FAILURE-VAL
          ALARMS_CRITICAL_FAILURE
))