; Auto-generated. Do not edit!


(cl:in-package tauv_msgs-msg)


;//! \htmlinclude ReadableAlarmReport.msg.html

(cl:defclass <ReadableAlarmReport> (roslisp-msg-protocol:ros-message)
  ((failure_level
    :reader failure_level
    :initarg :failure_level
    :type cl:string
    :initform "")
   (alarms_no_failure
    :reader alarms_no_failure
    :initarg :alarms_no_failure
    :type (cl:vector cl:string)
   :initform (cl:make-array 0 :element-type 'cl:string :initial-element ""))
   (alarms_predive_failure
    :reader alarms_predive_failure
    :initarg :alarms_predive_failure
    :type (cl:vector cl:string)
   :initform (cl:make-array 0 :element-type 'cl:string :initial-element ""))
   (alarms_mission_failure
    :reader alarms_mission_failure
    :initarg :alarms_mission_failure
    :type (cl:vector cl:string)
   :initform (cl:make-array 0 :element-type 'cl:string :initial-element ""))
   (alarms_critical_failure
    :reader alarms_critical_failure
    :initarg :alarms_critical_failure
    :type (cl:vector cl:string)
   :initform (cl:make-array 0 :element-type 'cl:string :initial-element "")))
)

(cl:defclass ReadableAlarmReport (<ReadableAlarmReport>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ReadableAlarmReport>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ReadableAlarmReport)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name tauv_msgs-msg:<ReadableAlarmReport> is deprecated: use tauv_msgs-msg:ReadableAlarmReport instead.")))

(cl:ensure-generic-function 'failure_level-val :lambda-list '(m))
(cl:defmethod failure_level-val ((m <ReadableAlarmReport>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader tauv_msgs-msg:failure_level-val is deprecated.  Use tauv_msgs-msg:failure_level instead.")
  (failure_level m))

(cl:ensure-generic-function 'alarms_no_failure-val :lambda-list '(m))
(cl:defmethod alarms_no_failure-val ((m <ReadableAlarmReport>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader tauv_msgs-msg:alarms_no_failure-val is deprecated.  Use tauv_msgs-msg:alarms_no_failure instead.")
  (alarms_no_failure m))

(cl:ensure-generic-function 'alarms_predive_failure-val :lambda-list '(m))
(cl:defmethod alarms_predive_failure-val ((m <ReadableAlarmReport>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader tauv_msgs-msg:alarms_predive_failure-val is deprecated.  Use tauv_msgs-msg:alarms_predive_failure instead.")
  (alarms_predive_failure m))

(cl:ensure-generic-function 'alarms_mission_failure-val :lambda-list '(m))
(cl:defmethod alarms_mission_failure-val ((m <ReadableAlarmReport>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader tauv_msgs-msg:alarms_mission_failure-val is deprecated.  Use tauv_msgs-msg:alarms_mission_failure instead.")
  (alarms_mission_failure m))

(cl:ensure-generic-function 'alarms_critical_failure-val :lambda-list '(m))
(cl:defmethod alarms_critical_failure-val ((m <ReadableAlarmReport>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader tauv_msgs-msg:alarms_critical_failure-val is deprecated.  Use tauv_msgs-msg:alarms_critical_failure instead.")
  (alarms_critical_failure m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ReadableAlarmReport>) ostream)
  "Serializes a message object of type '<ReadableAlarmReport>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'failure_level))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'failure_level))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'alarms_no_failure))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((__ros_str_len (cl:length ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) ele))
   (cl:slot-value msg 'alarms_no_failure))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'alarms_predive_failure))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((__ros_str_len (cl:length ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) ele))
   (cl:slot-value msg 'alarms_predive_failure))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'alarms_mission_failure))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((__ros_str_len (cl:length ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) ele))
   (cl:slot-value msg 'alarms_mission_failure))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'alarms_critical_failure))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((__ros_str_len (cl:length ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) ele))
   (cl:slot-value msg 'alarms_critical_failure))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ReadableAlarmReport>) istream)
  "Deserializes a message object of type '<ReadableAlarmReport>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'failure_level) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'failure_level) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'alarms_no_failure) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'alarms_no_failure)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:aref vals i) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:aref vals i) __ros_str_idx) (cl:code-char (cl:read-byte istream))))))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'alarms_predive_failure) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'alarms_predive_failure)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:aref vals i) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:aref vals i) __ros_str_idx) (cl:code-char (cl:read-byte istream))))))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'alarms_mission_failure) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'alarms_mission_failure)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:aref vals i) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:aref vals i) __ros_str_idx) (cl:code-char (cl:read-byte istream))))))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'alarms_critical_failure) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'alarms_critical_failure)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:aref vals i) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:aref vals i) __ros_str_idx) (cl:code-char (cl:read-byte istream))))))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ReadableAlarmReport>)))
  "Returns string type for a message object of type '<ReadableAlarmReport>"
  "tauv_msgs/ReadableAlarmReport")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ReadableAlarmReport)))
  "Returns string type for a message object of type 'ReadableAlarmReport"
  "tauv_msgs/ReadableAlarmReport")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ReadableAlarmReport>)))
  "Returns md5sum for a message object of type '<ReadableAlarmReport>"
  "5420ac12365c08ba46b84a0a6b7db17d")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ReadableAlarmReport)))
  "Returns md5sum for a message object of type 'ReadableAlarmReport"
  "5420ac12365c08ba46b84a0a6b7db17d")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ReadableAlarmReport>)))
  "Returns full string definition for message of type '<ReadableAlarmReport>"
  (cl:format cl:nil "string failure_level~%string[] alarms_no_failure~%string[] alarms_predive_failure~%string[] alarms_mission_failure~%string[] alarms_critical_failure~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ReadableAlarmReport)))
  "Returns full string definition for message of type 'ReadableAlarmReport"
  (cl:format cl:nil "string failure_level~%string[] alarms_no_failure~%string[] alarms_predive_failure~%string[] alarms_mission_failure~%string[] alarms_critical_failure~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ReadableAlarmReport>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'failure_level))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'alarms_no_failure) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4 (cl:length ele))))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'alarms_predive_failure) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4 (cl:length ele))))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'alarms_mission_failure) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4 (cl:length ele))))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'alarms_critical_failure) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4 (cl:length ele))))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ReadableAlarmReport>))
  "Converts a ROS message object to a list"
  (cl:list 'ReadableAlarmReport
    (cl:cons ':failure_level (failure_level msg))
    (cl:cons ':alarms_no_failure (alarms_no_failure msg))
    (cl:cons ':alarms_predive_failure (alarms_predive_failure msg))
    (cl:cons ':alarms_mission_failure (alarms_mission_failure msg))
    (cl:cons ':alarms_critical_failure (alarms_critical_failure msg))
))
